### ISSUE TITLE
Helper methods

### ISSUE THREAD

**Issue by aesopwolf** [bitinn/node-fetch#10]
What are your thoughts on providing helper methods such as ```fetch.post``` and ```fetch.put```? They would just automatically add ```{ method: 'WHATEVER' }``` to the options argument.

**Comment by bitinn** [comment]
I am kinda against introducing API out of fetch spec's scope. It's pretty easy to write a helper library to extend `node-fetch` functionality if you prefer.

Plus it's easier to think of `fetch` as a simple function returning promise, instead of an instance of `Fetch`

**Comment by aesopwolf** [comment]
Gotcha, fair enough!
