### ISSUE TITLE
special port for https

### ISSUE THREAD

**Issue by bongwa** [bitinn/node-fetch#108]
I can use node-fetch to visist https:\\192.168.2.11.
but I can't visit https:\\192.168.2.11:8080.
Is the port fixed to 443 for https?

**Comment by bitinn** [comment]
We don't differentiate http/https request options, Node.js supports non-default port for HTTPS, you probably need a custom http.Agent to make SSL work.

But let us know the code you are using and the full error you are getting...

ref: https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by bongwa** [comment]
![image](https://cloud.githubusercontent.com/assets/11609178/14734960/8e35e6a6-08a0-11e6-8a93-28a438e1feb6.png)
I use wireshark to capture the package.
server return 400(status code).
I think it need certification.
how can i do it?

**Comment by bongwa** [comment]
![image](https://cloud.githubusercontent.com/assets/11609178/14735401/37ae0568-08a3-11e6-8788-b92fad1084c5.png)
I use diffirent server to test it.
Last is haproxy.
This one is nginx.

I must say sorry , https:\\192.168.2.131 is same to https:\\192.168.2.131:8080. not done.

**Comment by bongwa** [comment]
So I think I must save the public certification,and use it to communication with server.
Is it right?

**Comment by bongwa** [comment]
How to do it? thanks

**Comment by bongwa** [comment]
![image](https://cloud.githubusercontent.com/assets/11609178/14737425/8ceb877a-08ae-11e6-8d40-bb7e13cba315.png)
I try to communication with "https://raw.githubusercontent.com/facebook/react-native/master/docs/MoviesExample.json". It done.
compare with me.
different that:
communication with my server,
when finish client key exchange,client want close the connection, so failed.

I don't know why it happen.

**Comment by bitinn** [comment]
Wireshack is too low-level for us to troubleshoot as anything on this level would be a Node.js core issue (if there is one). A much better debug information is (1) your code and (2) the error message you got.

If your certificate is self-signed, or somehow not signed by the list of CA node.js support, you need something like this:

https://github.com/bitinn/node-fetch/issues/15#issuecomment-97368725

**Comment by bitinn** [comment]
no further comment, closing for now...
