### ISSUE TITLE
wrong HTTP error status handling on promise

### ISSUE THREAD

**Issue by skatpgusskat** [bitinn/node-fetch#109]
The Promise returned from fetch() won't reject on HTTP error status even if the response is a HTTP 404 or 500. 

But this node-fetch's Promise is just reject when HTTP status was 500 or 404 etc.

from https://fetch.spec.whatwg.org/#concept-response,

>To process response for response, run these substeps:
>
> -If response's type is "error", reject p with a TypeError and terminate these substeps.

> --Resolve p with a new Response object associated with response and a new Headers object whose guard is "immutable".

( p is promise )

and,

>  response whose type is "error" is known as a network error.
>
> A network error is a response whose status is always 0, status message is always the empty byte sequence, header list is always empty, body is always null, and cache state is always "none".

**Comment by bitinn** [comment]
> The Promise returned from fetch() won't reject on HTTP error status even if the response is a HTTP 404 or 500.

This is what we do, please show us your code and the full error you got.

**Comment by skatpgusskat** [comment]
Oups.... im really sorry i just mistake myself on code. thanks for answer.
