### ISSUE TITLE
`response.json()` does not always return a Promise

### ISSUE THREAD

**Issue by RickWong** [bitinn/node-fetch#111]
When I call a `response.json()` sometimes it returns the decoded content immediately, instead of a Promise. It breaks chaining like `.json().then()`. I'm using node-fetch 1.5.1.

According to MDN `.json()` must always return a Promise. https://developer.mozilla.org/en-US/docs/Web/API/Body/json

**Comment by TimothyGu** [comment]
Can you provide a test case?

**Comment by bitinn** [comment]
Same here, would be pretty interesting if this doesn't return a promise

https://github.com/bitinn/node-fetch/blob/master/lib/body.js#L40-L46

**Comment by RickWong** [comment]
My bad. Some middleware was also decoding JSON somehwere.

Sorry for this time-waste!
