### ISSUE TITLE
Anyway to fetch an XML using, well fetch?

### ISSUE THREAD

**Issue by born2net** [bitinn/node-fetch#113]
Anyway to fetch an XML using, well fetch?

I saw json() cmd, but nothing for xml() or event pure text?

regards

Sean.

**Comment by bitinn** [comment]
You will need to parse XML yourself by piping `res.body` or passing `res.text()` to the parser module of your choice.

ref:
- https://github.com/bitinn/node-fetch#usage
- https://fetch.spec.whatwg.org/

**Comment by born2net** [comment]
tx for the quick response, I have tried .text() but for some reason I get back
Promise { <pending> }
while it is just a pure <XML/> that I get back, odd...

**Comment by jimmywarting** [comment]
Just remove the console.log ;)

**Comment by born2net** [comment]
well I want to display to the user the returned output (its a cmd line utility) but the promise string is pre-appended
