### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by fny** [bitinn/node-fetch#120]
Is there any interest to include TypeScript alongside the node-fetch repo? I've written them for use with an internal project. If not, I'll just make the submission to DefinitelyTyped.

**Comment by bitinn** [comment]
We won't maintain a TypeScript version (or rewrite with TS), I haven't used DefinitelyTyped before, is it the place for people to provide custom TS definition? You are welcomed to provide one to them.

**Comment by nikeee** [comment]
I am using these definitions: https://github.com/Microsoft/TypeScript/issues/4948
