### ISSUE TITLE
HTTP Error codes custom information

### ISSUE THREAD

**Issue by iaptsiauri** [bitinn/node-fetch#122]
When server responds with status 400, it additionally adds custom information why the request was malformed, is there any way I can extract this information?

**Comment by bitinn** [comment]
> additionally adds custom information

- they are status message, headers or response body then you can
- note that status 400 is still resolved, not rejected.

see readme and testcases for examples.

- https://github.com/bitinn/node-fetch#usage
- https://github.com/bitinn/node-fetch/blob/master/test/test.js
