### ISSUE TITLE
POST JSON?

### ISSUE THREAD

**Issue by jamestwiggle** [bitinn/node-fetch#124]
I see that in the repository description it says that the body can be a 
> request body can be a string, buffer, readable stream

Is there anyway that the body can also be JSON format? If not how would you send things like:
```js
{
  token: 'kaljdslfkjasdlkfjalksdjf',
  amount: '832'
}
```

over with `node-fetch`?

**Comment by jimmywarting** [comment]
My guess: it doesn't work in the browser

Solution:
```javascript
JSON.stringify({
  token: 'kaljdslfkjasdlkfjalksdjf',
  amount: '832'
})
```

**Comment by jamestwiggle** [comment]
That doesn't seem to work, I have the following:
I'm sending this from a a server on `localhost:8000` to a server to receive at `localhost:8003`.
```js
        var response = await fetch('http://localhost:8003/charge/', {
          method: 'POST',
          body: JSON.stringify({
            token: 'fasdflakjsdlfkaj',
            amount:832
          })
        });
```

The server returns `undefined` when I try to `console.log(req.body);`

Any clues @jimmywarting ?

**Comment by jimmywarting** [comment]
Are you using express? do you have some bodyParser?

Anyway, res.body is not part of the node-http standard what most module do is: Take the response stream - parse it - and then append it onto res as res.body

so try something like

```javascript
res.on('data', => {
  console.log(data)
})
```

You probably what to pass in this header also...

    {headers: { 'Content-Type': 'application/json' } }

**Comment by jamestwiggle** [comment]
Thank you @jimmywarting! That did the trick 😄

**Comment by jimmywarting** [comment]
yrw
