### ISSUE TITLE
socket hang up when using maxSockets

### ISSUE THREAD

**Issue by pocketjoso** [bitinn/node-fetch#125]
Hi there,
not sure there's anything wrong on `node-fetch`'s side here, but I thought I would ask:

Recently I added `http(s).globalAgent.maxSockets = 5` to my app to prevent making too many concurrent requests to the same domain, after which I started seeing `socket hang up` errors. From what I can understand this error comes from the `http(s)` library itself (that I presume `node-fetch` wraps), and seems to be related to connections being closed incorrectly.

Is there anything that you know of that I can do differently via `node-fetch` to avoid this problem?

I'm on Node 4 or Node 6 (same on both), and on **linux**. Error does **not** appear on osx.

Thanks for any help,
Jonas

**Comment by pocketjoso** [comment]
In case it helps, stacktrace (yes I'm using isomorphic-fetch):

```
at ClientRequest.<anonymous> (.../node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:124:11)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketOnEnd (_http_client.js:300:9)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by pocketjoso** [comment]
Okay nvm, it is working on `Node 6`. I was being tired and looking at the wrong node version (0.12, where this problem does happen - but irrelevant for me).

**Comment by pocketjoso** [comment]
@bitinn Actually this still happens on `Node 6` - wondering if you do have any input that can help resolve this problem (even though I'm aware it most likely has nothing do with the code from this library itself)...

**Comment by pocketjoso** [comment]
Okay, I must be using `maxSocket`s incorrectly. I set it because I was previously making too many concurrent requests towards the same domain (server), which eventually responded with `503`. (default `maxSocket` value in my Node version is `Infinity`). I thought `maxSocket`s was the solutions to this (rather than setting up my own connection pooling).

However now it seems if you set a lower `maxSocket` value and then make more concurrent requests to same domain than that value [then you get this 'socket hang up' error]( https://github.com/Automattic/knox/issues/116#issuecomment-15045187)... Back to square one.

**Comment by bitinn** [comment]
I don't think there is much we can do? You need to make less requests per second I think.

**Comment by bitinn** [comment]
And in case you didn't know this: https://github.com/bitinn/node-fetch/blob/master/index.js#L79-L81

**Comment by pocketjoso** [comment]
> I don't think there is much we can do? You need to make less requests per second I think.

Yep that's what I think too. Thought node was handling that for me via the `maxSockets` option, but yeah doesn't seem so.

**Comment by bitinn** [comment]
Just to make sure you read my other replies: if you only set global agent maxSockets and didn't pass node-fetch a custom agent, it will use connection close header by default. It means no connection pooling.

From my phone,
David
