### ISSUE TITLE
The same FormData Object used multiple times cause process to hang.

### ISSUE THREAD

**Issue by zengfenfei** [bitinn/node-fetch#126]
```javascript
var fetch = require('node-fetch');
var FormData = require('form-data');

var form = new FormData();
form.append('a', 1);
fetch('http://httpbin.org/post', {
		method: 'POST',
		body: form, // The same form used second time here, and process will hang
		headers: form.getHeaders()
	})
	.then(function(res) {
		return res.json();
	}).then(function(json) {
		console.log(json);
	});

fetch('http://httpbin.org/post', {
		method: 'POST',
		body: form,
		headers: form.getHeaders()
	})
	.then(function(res) {
		return res.json();
	}).then(function(json) {
		console.log('The secod form', json);
	});
```

**Comment by bitinn** [comment]
I would think it's related to this (read both replies): https://github.com/bitinn/node-fetch/pull/92#issuecomment-200232648

`form-data` on node.js isn't quite the same as FormData on client, despite similar API, unfortunately.

The easiest way without direct dependency on `form-data` to create that data twice, unfortunately.

**Comment by bitinn** [comment]
Note that even though your `form-data` isn't using stream data, we still pipe it as it's a stream. so you are effectively piping your stream into 2 different source and I bet if one drain faster, you face the stream back-pressure problem.

**Comment by bitinn** [comment]
Closing this as we can't do much with `form-data` module, see replies for workaround.
