### ISSUE TITLE
404 and promise resolved

### ISSUE THREAD

**Issue by arve0** [bitinn/node-fetch#133]
I (intuitively) expected `fetch` to `reject` the Promise on **non** 200 status codes. Is this a part of the spec?

```js
var f = require('node-fetch');
f('http://httpbin.org/404')
  .then((r) => console.log('ok, status: ' + r.status))
  .catch((e) => console.error(e))
```

gives
```
ok, status: 404
```

I expected the `catch`-callback to be called.

I see `res.ok` mentioned in the documentation, but maybe add something like

```
if (!res.ok) {
  throw new Error(`Failed fetching ${res.url} with ${res.status} ${res.statusText}.`);
}
```

?

**Edit:** Or have rejection as an option?

**Comment by bitinn** [comment]
> Is this a part of the spec?

The short answer, if server responds, it's a resolved promise.

The long answer:

- https://github.com/bitinn/node-fetch/blob/master/test/test.js
- https://fetch.spec.whatwg.org/
