### ISSUE TITLE
Add .pipe to Response?

### ISSUE THREAD

**Issue by olalonde** [bitinn/node-fetch#134]
It seems response is not a Node.js compatible read stream. It would be useful if it implemented the Node.js read stream API.

**Comment by bitinn** [comment]
`res.body` is, and that's as close to Fetch Spec as we can get while staying native Node.js stream.

If Fetch Spec changed again to allow piping the whole `res`, we will consider this request.

**Comment by olalonde** [comment]
Oh, wasn't aware of that, thanks.
