### ISSUE TITLE
Unused clone causes stream back-pressure

### ISSUE THREAD

**Issue by ThaNarie** [bitinn/node-fetch#139]
**issue**
Cloning a stream, which you end up not using, causes back-pressure on the original response, preventing it from draining the source.

```js
fetch(url).then(function(res) {

	// unused clone causing back-pressure in the stream
	var clone = res.clone();

	// this will start reading internally, but just 'halts' mid-way and never completes
	res.json().then(function(result) {
		console.log(result);
	});
})
```
re 419597fe131cec0552d5d907f145032df485a2d6

**background**
The reason why this happens is perfectly explained here:
http://www.bennadel.com/blog/2817-the-affect-of-back-pressure-when-piping-data-into-multiple-writable-streams-in-node-js.htm

**use case**
In my project I have some checking in the `then` (status code, etc), and when something 'fails' (or the `res.json()` throws an error because the response is not json for some reason), I want to the error to end up in the chained `catch` handler.
In the `catch` handler I wanted to read the response as `.text()`. When the `.json()` was already used I couldn't do that, so I needed a clone.

So what I ended up doing, was to create a clone before reading the json (scoping it to the 'parent' function, and using that clone to read the `.text()` response in the `catch`.
This means that the clone was only used when an error occurred.

**internal logging**
I ended up adding logs in the `"data"` (https://github.com/bitinn/node-fetch/blob/952aa2a13546532ff612bfa98ec8216dda8a3871/lib/body.js#L105) and `"end"` handlers of the body stream, and if the size was longer than `32768` (in my test case that was 2 chunks), it stopped there, without calling `"end"`.

When, after a timeout, you start reading from the clone, both the clone and original continued until all data was drained.

There seems to be a difference between normal and gzipped requests, normal requests can be larger before the issue occurs.

**workarounds**
Maybe first ask the question if we want to solve this?
Cloning things without using them seems something you don't want to do, but if you do need it later, you can only clone it before you've read it the first time. And I don't think the code should silently 'fail' if for some reason you won't end up using the clone.

There are workarounds, what I've done now is to read the response as `.text()`, and parse that to json manually, so I can use the text response later on _if_ I need it.
But that would become a bit cumbersome when having to do that for blobs, arrayBuffers and formData as well.

**how to solve?**
I'm new to streams, so I'm not sure how to correctly solve this.

One way would be to configure the back-pressure in the PassThrough Stream by setting a higher `highWaterMark` value, but that doesn't really solve anything, as there will always be a response larger than the configured value that will break. Also the app will use more memory.

Another way could be to read the response into a variable before resolving the fetch, and use that as source for every clone. This would technically solve the issue, but uses more memory and performance because it's not making use of streams anymore.
This is how it's done in github/fetch:
https://github.com/github/fetch/blob/03e2ccc33e9024d3c4fabab66951e7dbcbc57754/fetch.js#L198

I have added a normal and gzipped unit test locally to reproduce the issue in this repository as well. Would it help if I opened up a PR with just those tests so someone else could help out fixing it?

**Comment by bitinn** [comment]
`clone` is implemented this way because #105, I don't think it's worth our time to complicate our solution further.

If an API returns non-JSON response randomly, and is out of your control, it's probably worth it to always `clone` and read a `text` response so you can do whatever logging/debugging necessary.

If you are afraid of the extra cost for `text`, pipe `body` to something like `black-hole-stream`, that will clean up your unused clone.

**Comment by bitinn** [comment]
Actually, I don't even think your are running into back-pressure. both the original and the clone body are piped into a pass through stream in our implementation. you shouldn't get back-pressure because they are now 2 different stream.

https://github.com/bitinn/node-fetch/blob/master/lib/body.js#L218-L227

**Comment by ThaNarie** [comment]
> clone is implemented this way because #105, I don't think it's worth our time to complicate our solution further.

I've seen that ticket, and that's the one that will break as well. I've tested this locally in this repository. All the current tests are done with super small reponses; `"hello world"` and `{name: 'value'}`. These will easily fit in the internal buffer of the PassThrough Stream.
If you use a larger response, the `r1.text()` will not complete, because the nested `res.json()` isn't read yet.

> If an API returns non-JSON response randomly, and is out of your control, it's probably worth it to always clone and read a text response so you can do whatever logging/debugging necessary.

That's what i've done now. But that's just a single use case. There could be other reasons (like the #105) where you want a clone, and read it at a (slightly) later moment in time.

It's not behaving like it should, like it's designed in the spec, so if you really feel strongly about not addressing this, you should at least add a big *notice* in the readme, that you cannot safely use clones if you don't read them at the same time.

I spent 5 hours yesterday debugging this issue, and I don't want other developers to 'waste' this much time either.

I this case I'm using 'isomorphic fetch', and the same code works perfectly in the browser. And I think more and more developers will start using fetch, including this library, and will eventually run into this issue.

I have added #142 that shows failing tests (duplicating an existing test, but with a larger response).

**Comment by ThaNarie** [comment]
> Actually, I don't even think your are running into back-pressure. both the original and the clone body are piped into a pass through stream in our implementation. you shouldn't get back-pressure because they are now 2 different stream.

I'm pretty sure it is, all the signs point to it:

1. Both PassThrough Streams are connected to the same source, so they are linked
together. Source streams only drain as fast as the slowest connected sink. And
since the clone is connected to the same source as the original, it can give
back-pressure to the source that influences the original.

2. When commenting out the `body.pipe(p2)` in the clone method (so not connecting
the clone to the source), everything behaves as it should.

3. When starting to read from the clone after a delay, it also starts filling the
original response:
  * clone response
  * read from original
  * original only reads 2 chunks and halts
  * after 500ms, start reading from the clone
  * both the clone and the original continue their output (`"data"` events)

  So when we start reading from the clone, we drain the sink of the PassThrough stream, releasing it of the back-pressure, so all connected streams start flowing again.

4. The [Linked Article](http://www.bennadel.com/blog/2817-the-affect-of-back-pressure-when-piping-data-into-multiple-writable-streams-in-node-js.htm) (have you read or watched it?) also uses the same PassThrough stream, and observes the exact same behaviour:
    ```
    hankhill.pipe( new stream.PassThrough() );
    hankhill.pipe( response );
    ```



The connected PassThrough streams are not holding any data, they are only passing it through (hence the name). They do have their internal buffer though, that can hold a small amount of data, so that's why everything seems to be okay for small responses. But when the response becomes lager, we notice the observed behaviour.

PassThrough streams extend Transform streams, which in turn inherits from Duplex stream, which is made up of a Readable and Writeable stream, with their default options.
A writable stream has an internal buffer of `16 * 1024` bytes:
https://github.com/nodejs/node/blob/be68b68d4863f0d389cc46fdf6f1cbcd1b241d0a/lib/_stream_writable.js#L40
So if that internal buffer is full, it will apply back-pressure, resulting in the observed behavior.


Note: This not only happens when you _don't use_ a clone. This already happens when you use the clone _after_ the original (so not at the same time). In this situation the clone still 'holds up' the original because it's not being drained yet. This behaviour is observed in the #142.


I hope this demonstrates that 1) this actually is a back-pressure issue, which 'breaks' due to the current stream implementation, and 2) this issue can be re-opened because it's worth addressing.

**Comment by bitinn** [comment]
Now, that's agree you are facing back-pressure, I don't think there is a solution where it can satisfy these 2 requirements simultaneously:

1. Not cause memory leaks if you don't use the cloned `res.body`.
2. But also allow you to use cloned `res.body` *whenever you like*.

**Comment by matthieusieben** [comment]
Note that official doc states that memory starvation is an expected side effect of using `Request.clone()` : 
https://developer.mozilla.org/en-US/docs/Web/API/Request/clone
