### ISSUE TITLE
Doesn't handle empty headers

### ISSUE THREAD

**Issue by wheresrhys** [bitinn/node-fetch#14]
If a header is undefined then https://github.com/bitinn/node-fetch/blob/master/lib/headers.js#L34 fails. Not sure what the desired behaviour should be, but probably either a) informative error or b) silently ignore that header

**Comment by bitinn** [comment]
Could you give me an example of how you encounter this problem?

**Comment by bitinn** [comment]
Fixed in v1.1.2 release, and we have more extensive test on supported headers

https://github.com/bitinn/node-fetch/blob/master/test/test.js#L623

**Comment by wheresrhys** [comment]
Excellent - thanks
