### ISSUE TITLE
How to fetch an image

### ISSUE THREAD

**Issue by ychw** [bitinn/node-fetch#143]
Looks like fetch can only download text or json content? Is there a way for me to download an remote image, and receive its binary (without saving to local file system)?

Thanks.

**Comment by jimmywarting** [comment]
you can use `res.body` which is a stream...
So you can pipe it example: `res.body.pipe(dest)`

You now also have the alternativ method to browsers `arrayBuffer` which is called just `buffer` (as of v1.6.0) and it will return a node buffer instance `res.body.buffer()`

**Comment by bitinn** [comment]
I am closing this assuming there isn't any further issues :)
