### ISSUE TITLE
Sending cookies

### ISSUE THREAD

**Issue by papigers** [bitinn/node-fetch#146]
Taken from [`fetch`](https://github.com/github/fetch) documentation:

> Sending cookies
> 
> To automatically send cookies for the current domain, the credentials option must be provided:
> 
> ``` js
> fetch('/users', {
>   credentials: 'same-origin'
> })
> ```
> 
> This option makes fetch behave similar to XMLHttpRequest with regards to cookies. Otherwise, cookies won't get sent, resulting in these requests not preserving the authentication session.
> 
> Use the include value to send cookies in a cross-origin resource sharing (CORS) request.
> 
> ``` js
> fetch('https://example.com:1234/users', {
>   credentials: 'include'
> })
> ```

This functionality should be added to `node-fetch`. I'll explain why I need this:

I'm developing an isomoprhic application which uses react, graphql, and relay. This isomorphic application, upon client requests, renders the view, and fetches the required data using relay on the server, while following requests and renders are done on the client.

As you may or may not know, `relay` uses `isomorphic-fetch` which uses node-fetch on the server. This makes the cookies not available on my graphql endpoint.
My current solution is to set the cookies manually:

``` js
{
  headers:{
    cookie: req.headers.cookie,
  },
}
```

**Comment by TimothyGu** [comment]
node-fetch doesn't have a built-in cookie store, so you have to manually specify where the cookies are for node-fetch to be aware of them. Since GitHub's fetch runs in the browser, it does have access to the browser cookie store. CORS of course [doesn't apply](https://github.com/bitinn/node-fetch/blob/master/LIMITS.md) either.

Yes, we [do](https://github.com/bitinn/node-fetch#motivation) know about isomorphic-fetch.

**Comment by papigers** [comment]
And what about adding a cookie store? (#94)

**Comment by bitinn** [comment]
Cookie store is a big can of worms on server-side. While your request to emulate browser is fair, it's quite likely other people will see cookie store and think of different usages.

I do know 2 scenarios where having a cookie store will help (#8 and #94), but I have been trying to leave implementation to third-party, for example, [a simple solution](https://github.com/valeriangalliat/fetch-cookie) was mentioned in #94.

I understand some developers want isomorphism, but not distinguishing client/server side creates serious dependency problems down the road (client/server implementation need to support the same set of features, on an evolving spec). So I lean more towards having familiar API but knowing the gaps between implementations.

**Comment by jimmywarting** [comment]
I would really want to see the "fetch event" implemented so we can start building cool extensions to node-fetch. Eg stuff like caching, cookie store etc

**Comment by bitinn** [comment]
While events are powerful, I don't think it's something developers are actively looking for, because people tend to 1) prefer simple http requests 2) think in "procedural terms" (which is why `yield` generators and `async/await` exists). Having to deal with events sucks, especially server-side.

**Comment by jimmywarting** [comment]
Let's agree to disagree

**Comment by leebenson** [comment]
I have to agree that events are generally a bad idea server-side. They make it difficult to scope functionality to the context of a specific request. I'd prefer to see something like Koa's middleware that allows composition of functions before/after requests, when implementing extensions.

**Comment by TimothyGu** [comment]
Is this the same issue as #94?

**Comment by bitinn** [comment]
I am pretty sure the cookie side of things are discussed in #94, and Facebook Relay never had a clear intention to give [full server-side rendering support](https://github.com/facebook/relay/issues/136) it seems.

As for OP's question, while solution is a bit ugly, it's already outlined here:

- https://github.com/denvned/isomorphic-relay#how-to-use
- https://github.com/denvned/isomorphic-relay/issues/49

**Comment by papigers** [comment]
@bitinn Just for the record, I (OP) was the one suggesting the ugly solution on [denvned/isomorphic-relay#49](https://github.com/denvned/isomorphic-relay/issues/49). Later, I've posted this issue here to suggest extending node-fetch in order to avoid the not-so-ideal solution mentioned above.
