### ISSUE TITLE
How do you read binary data?

### ISSUE THREAD

**Issue by caub** [bitinn/node-fetch#147]
It seems a few [methods](https://developer.mozilla.org/en-US/docs/Web/API/Response) like `.blob()` are missing  to do so

the idea is just making something similar to:

```
request('some.png', (err, res, body)=>{
	console.log(Buffer.from(body).toString('base64'));
});
```

**Comment by jimmywarting** [comment]
This is more of a [stackoverflow](stackoverflow.com) question and not an issue

---

you can use `res.body` which is a stream...
So you can pipe it. Example: `res.body.pipe(dest)`
or do: 
```javascript
res.body.on('data', chunk => {
   // Got a chunked buffer
}).on('end' () => {
   // end of stream 
})
```

You now also have the alternativ method to browsers `arrayBuffer` which is called just `buffer` (as of v1.6.0) and it will resolve to a node buffer instance `res.body.buffer()`

```javascript
fetch('some.png').then(res => res.body.buffer()).then(console.log)
```

**Comment by caub** [comment]
Great answer, thanks, sorry

**Comment by jimmywarting** [comment]
use buffer instead of arrayBuffer. it's made like that by design

**Comment by bitinn** [comment]
Yeah as documented in known differences and #51, on Node.js there isn't much point in using arrayBuffer.

**Comment by wengeezhang** [comment]
> This is more of a [stackoverflow](stackoverflow.com) question and not an issue or a bug
> 
> you can use `res.body` which is a stream...
> So you can pipe it. Example: `res.body.pipe(dest)`
> or do:
> 
> ```js
> res.body.on('data', chunk => {
>    // Got a chunked buffer
> }).on('end' () => {
>    // end of stream 
> })
> ```
> 
> You now also have the alternativ method to browsers `arrayBuffer` which is called just `buffer` (as of v1.6.0) and it will resolve to a node buffer instance `res.body.buffer()`
> 
> ```js
> fetch('some.png')
> .then(res => res.body.buffer())
> .then(console.log)
> ```

just use res.buffer(), not res.body.buffer(), as follows: 
fetch('some.png')
 .then(res => res.buffer())
 .then(console.log)
