### ISSUE TITLE
Allow to pass all available https options

### ISSUE THREAD

**Issue by emmenko** [bitinn/node-fetch#15]
Currently only a subset of all the available options are supported https://github.com/bitinn/node-fetch/blob/master/index.js#L66-L80

For `https` important options are missing (e.g.: `rejectUnauthorized`, `secureProtocol`, `key`, `cert`, ...)
https://nodejs.org/api/https.html#https_https_request_options_callback

I should be able to pass all of those options.

**Comment by bitinn** [comment]
As this is out of scope for Fetch, I am against exposing `https` options in Fetch API.

You will be much better served by using a module that fully support `http` and `https` options (say [request](https://github.com/request/request), you can find `co-` or thenable version of it); alternatively, use [denodeify](https://github.com/matthew-andrews/denodeify) or [bluebird](https://github.com/petkaantonov/bluebird) to promisify `https.request`.

Our intention to keep `node-fetch` API minimal and close to spec, unless there are very strong use-cases. You can find similar discussion on #11

**Comment by emmenko** [comment]
I see your point. Thanks for clarifying.

So I guess I would have to provide a valid SSL certificate even for local development.

**Comment by bitinn** [comment]
I am not exactly sure what you are trying to achieve, but trying passing a `https.Agent` with your CA configuration using node-fetch's `agent` options might help.

http://stackoverflow.com/questions/21004645/where-is-nodes-certificate-store

**Comment by emmenko** [comment]
Nothing special, just I have a https server for local development with a self-signed certificate and I need of course to allow the request with `rejectUnauthorized: false`.

But yes, I saw I could come around with it by configuring the `globalAgent` https://nodejs.org/api/https.html#https_https_globalagent. I will give it a try.

**Comment by bitinn** [comment]
Or you can just create a https.Agent instance and pass it to node-fetch, instead of changing globalAgent.

see `agent` in https://github.com/bitinn/node-fetch#options

**Comment by emmenko** [comment]
Ok, I'll try that as well. Thanks :+1:

**Comment by emmenko** [comment]
Yep, I did it like this then

```js
const agent = new https.Agent({
  key: fs.readFileSync(`${CERT_PATH}.key`),
  cert: fs.readFileSync(`${CERT_PATH}.crt`),
  rejectUnauthorized: false
})
```

**Comment by mmcgahan** [comment]
the main downside of this is that you can't use use an isomorphic script with `fetch` this way - when it runs in the browser there's no `require('https')`.

I suspect that `node-fetch` will increasingly be used as a shim for `fetch` in universal apps, so it would great if there was a way to pass in `agentOptions` without having to import Node packages.

**Comment by TimothyGu** [comment]
@mmcgahan, you can't set any `agentOptions` in a browser environment even using "traditional" APIs like XMLHttpRequest, since everything is controlled by the browser itself. The whole concept of the agent is something only applicable to the Node.js implementation of the Fetch API.

**Comment by mmcgahan** [comment]
@TimothyGu for sure, but the nice thing about supporting `agentOptions` rather than just `agent` in node-fetch is that you don't have to use a Node-only package (`require('https')`) for the former and therefore the module/script that actually calls `fetch` can be used in the browser or on the server without a environment-conditional imports - native browser implementations of fetch will ignore `agentOptions`, while 'node-fetch' can apply the rules in Node to achieve the desired behavior.

**Comment by sharadJay** [comment]
Any update on this ?

**Comment by ahmadnassri** [comment]
implemented a simple & un-intrusive solution as per notes here in #236 

you can now use the `options.agent` as an object which in turn will internalize creating the `http.Agent` instance.

**Comment by sibelius** [comment]
@emmenko do you have a full example using this with fetch?

**Comment by hsHemant** [comment]
I used this es6 syntax and it worked for me. No need to set node global options.
```typescript
import https from "https";
const agent = new https.Agent({
  rejectUnauthorized: false
});
fetch(myUrl, { agent });
```

**Comment by davidthornton** [comment]
Love `fetch` and everything it stands for — but I just think it’s hilarious that due to how broken the internet is, the justification for not allowing `node-fetch` to use _client_ certificates is because of how closely `node-fetch` is trying to conform to a _client_-side library API... 😂😂😂

**Comment by davidthornton** [comment]
Oop, didn’t see #236 — great work guys 🎉😂
