### ISSUE TITLE
visionmedia/debug?

### ISSUE THREAD

**Issue by PavelVanecek** [bitinn/node-fetch#150]
I am a fan of using [debug module](https://github.com/visionmedia/debug). I am also a fan of using node-fetch (thanks! by the way). Can we have both? I can prepare a PR if you wish.

**Comment by bitinn** [comment]
I don't see the point to have built-in debug reporting as Fetch isn't designed to let you know the details of http request. You can however handle the FetchError we throw anyway you see fit.
