### ISSUE TITLE
Usage of clone stream and backpressure (aka default highWaterMark value)

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#151]
It seems browsers (at least Chrome) are smart enough to _duplicate_ the response stream if users:
1. `clone` the response.
2. resolve the original response completely.
3. and then resolve the cloned response.

Per Fetch Spec's [clone definition](https://fetch.spec.whatwg.org/#concept-body-clone), we should `tee` the stream at step 1, and `tee` is defined in [Stream Spec](https://streams.spec.whatwg.org/#rs-tee). `node-fetch` does this already.

Problem: **we don't know the response body size beforehand**. So when user `clone`, they still risk running into backpressure issue; as on step 2, when data starts flowing for both the original and the cloned stream, and because we are not reading from cloned stream at the time, its internal buffer will fill up, eventually, causing both stream to pause and hence what we called _backpressure_.

It seems Chrome has a higher default buffer size than Node.js, so when users approach this problem with isomorphism, they run into issues where request works on client-side, but failed on server-side.

There are on-going discussion at https://github.com/whatwg/streams/issues/401 and I am asking this again just to be sure https://github.com/whatwg/streams/issues/506

**Comment by thebigredgeek** [comment]
Is this fixed?  Ran into an issue in production where request promises aren't resolving or rejecting on the server due to the use of `clone` in an isomorphic frontend using `react` and `apollo-client`.  Would love to see a fix for this problem

**Comment by bitinn** [comment]
The last time I checked, there is no easy fix for this as it's by design. We can keep increasing the internal stream bucket size but eventually backpressure will kicks in. Users need to be aware of backpressure when working with streams, unfortunately.

(From my phone)

**Comment by DevBrent** [comment]
> Users need to be aware of backpressure when working with streams, unfortunately.

@bitinn I don't know if this is an answer really. I'm fully aware of backpressure due to my use of node-fetch but response.clone()'s implementation makes it physically impossible to fetch large bodies with no known resolution but not to use clone().

Is this an issue where every response copy must be fully read in order for any to read beyond the buffer or is it an issue where it becomes impossible to read beyond the buffer once clone is used at all?

**Comment by bitinn** [comment]
@DevBrent the real problem here is: there is no standard on just how much a consumer of a stream should be willing to hold before it causes back-pressure.

Nodejs has a very small cap, browsers have a large and inconsistent cap. The only safe way is to make sure you don't cause the stream to back-pressure: by giving it some direction to flow to.

See https://github.com/whatwg/streams/issues/506

The browsers are shielding you from this problem. But we prefer you are aware of it (it's a pain, for sure, but a pain we think people should be aware of.)

https://nodejs.org/es/docs/guides/backpressuring-in-streams/

**Comment by xxczaki** [comment]
Fixed by #671 :tada:

**Comment by arizonatribe** [comment]
It ain't fixed until it's published

**Comment by bitinn** [comment]
This is not a bug, you should be resolving both stream in parallel (with promise.all) like forking any stream on node.js; what’s missing is an option to allow caching more data in memory (aka high watermark), that’s a workaround, not solution.

This is one of those cases where browsers just cache more data in memory so dev don’t have to care: guess why everyone is complaining about them sucking up memory?

(From my phone)

**Comment by bitinn** [comment]
I agree in general I prefer to close issues when they are released. But we are working on v3, so can’t hold all issues open until then. Again, don’t change high water mark unless absolutely necessary.

(From my phone)
