### ISSUE TITLE
response.json() undefined for gunzip body

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [bitinn/node-fetch#152]
I have a remote API call that returns a gzip encoded content. With content itself being json.
If I call response.json() this returns undefined

**Comment by bitinn** [comment]
I can't help you much without seeing reduced test case and without you testing your code with http://httpbin.org/

**Comment by sathyakumarseshachalam** [comment]
Hi, My code against [httpbin](http://httpbin.org/)

```
const handleErrors = (response) => {
  if (!response.ok) {
    throw Error(response.statusText);
  }
  return response.json();
}

export const findCollector = (filter) => {
  return fetch('http://httpbin.org/gzip', { method: 'GET', compress: true })
    .then((response) => {
      handleErrors(response)
    })
    .then((response) => {
      console.log(response);
    });
}

```
The last `console.log` just prints `undefined`

**Comment by bitinn** [comment]
you need `return handleErrors(response)` or your promise chain is broken.
