### ISSUE TITLE
Silent failure when given an object as the body

### ISSUE THREAD

**Issue by gertsonderby** [bitinn/node-fetch#153]
During a test of POST requests in which HTTP was mocked out, I noticed that I was not getting a request body as expected. I had set the `body` field on the configuration object to a JS object (to the tune of `{ url: '/fixture.json', list: [1, 2, 3] }` - very complex stuff). Given that this is an unsupported format, I would have expected an error of some kind, but none was issued. Alternatively, if the body had been set to `'[object Object]'` or somesuch, it would have been clear what my mistake was. But the body was simply empty. I'm reporting this because a silent failure like that is a potential error source and intractable to debug.

**Comment by bitinn** [comment]
You need to show us a reduced example for us to investigate further.

But you shouldn't mock http, should mock the whole node-fetch module, because you are not testing our code's tolerance. You are testing your code's correctness.

**Comment by jimmywarting** [comment]
maybe it's json parsing error?
parsing json requires the string to be wrapped in double quotes. Your example isn't

**Comment by gertsonderby** [comment]
If I had mocked out fetch, I would A) never have gotten the code written correctly since I'd have needed to first implement a mock version of fetch, and B) never have found this problem.

As well, mocking out HTTP was really simple, mocking out fetch would never have been. But I didn't come here to argue about my test architecture choices. I came to point out a silent failure that may cause grotesque amounts of trouble for people using your library.

The problem is simple enough to show:
```js
fetch('http://wherever.com/acceptsPost/', { body: { state: 'this is an object, not a string' });
```
No body will be sent. No error or other suspicion-arousing event will occur. This is very surprising behavior, and fails completely silently.

**Comment by bitinn** [comment]
Fair enough, I will get to it soon.

**Comment by jimmywarting** [comment]
Actually that is what happens in chrome & firefox as well, silence no rejection
```javascript
fetch('.', { method: 'POST', body: { foo: 1 } }).then(
    res => console.log("success"),
    err => console.log("failure")
)
```
just success

**Comment by bitinn** [comment]
I will need to check Fetch Spec, no time yet, it's possibly by design.

**Comment by bitinn** [comment]
Yeah, per Fetch spec, we should will silently ignore object, and I have raised a question at https://github.com/whatwg/fetch/issues/371

**Comment by bitinn** [comment]
The consensus is calling `toString` on input, it's a bit weird but that's the standard, we will implement soon.

**Comment by bitinn** [comment]
this has been added in release v1.6.1
