### ISSUE TITLE
Add 'body' header with buffer and you get a silent error

### ISSUE THREAD

**Issue by gauntface** [bitinn/node-fetch#157]
I accidentally set the body as a header rather set it on the options and the result was the promise neither resolved or rejected.

{
    headers: {
        body: Buffer.alloc(16)
    }
}

**Comment by bitinn** [comment]
Thanks for the report, seems like Fetch spec haven't decided on what a valid header value is just yet, we should add a test for Buffer value.

REF: 
- https://fetch.spec.whatwg.org/#concept-header
- https://github.com/bitinn/node-fetch/blob/master/test/test.js#L1121

**Comment by bitinn** [comment]
I am not able to reproduce this locally when trying to create a test for it today, please let me know if you got any sample code for testing.
