### ISSUE TITLE
Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by grayboxpdx** [bitinn/node-fetch#158]
In Safari I'm getting the following error:
```
TypeError: Error.captureStackTrace is not a function. (In 'Error.captureStackTrace(this,this.constructor)', 'Error.captureStackTrace' is undefined)
```
This I believe comes from the FetchError lib. Is it possible to add a conditional to catch if Error.captureStackTrace is defined?

Thanks

**Comment by TimothyGu** [comment]
This module is only supposed to be used in Node.js. Browsers are not supported.

**Comment by jimmywarting** [comment]
https://github.com/github/fetch
