### ISSUE TITLE
Post method redirect does not send cookies further

### ISSUE THREAD

**Issue by RusAlex** [bitinn/node-fetch#159]
When you use `POST` method with `node-fetch` it does not send cookies to the next url. 

Suppose it's not what most users expect. 

Maybe it have to be reflected in documentation ?

**Comment by bitinn** [comment]
Yes it doesn't at this time (because lack of built-in cookie support) and the current workaround is to extract POST headers and manage cookies separately (which you can only do on server-side).

**Comment by RusAlex** [comment]
And what about making some notes in README.md ?

**Comment by bitinn** [comment]
I have added it onto [KNOWN LIMIT document](https://github.com/bitinn/node-fetch/blob/master/LIMITS.md).
