### ISSUE TITLE
POST requests not working

### ISSUE THREAD

**Issue by blim8183** [bitinn/node-fetch#16]
I don't seem to be able to make post requests. I've posted the example in the docs to PostCatcher and it's showing that no data is being sent.

Post catcher URL: http://postcatcher.in/catchers/554104bdc5959603000001bc

My code:

    fetch = require('node-fetch');

    fetch('http://postcatcher.in/catchers/554104bdc5959603000001bc', { method: 'POST', body: 'a=1' })
      .then(function(res) {
          return res.json();
      }).then(function(json) {
          console.log(json);
      });

**Comment by bitinn** [comment]
I would say try our httpbin example to double check first, something like this:

```
fetch('http://httpbin.org/post', { method: 'POST', body: 'a=1' })
    .then(function(res) {
        return res.json();
    }).then(function(json) {
        console.log(json);
    });
```

and add a `.catch` clause to debug yours.

**Comment by bitinn** [comment]
closing for now as I see no further feedback.

**Comment by qubyte** [comment]
We're seeing this problem too, against both requestbin and postcatcher.in.

**Comment by qubyte** [comment]
For example using (and dropping one or both headers):

```javascript
var body = 'hello=world';

var options = {
    method: 'POST',
    body: body,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': new Buffer(body).length
    }
};

fetch('http://requestb.in/<bin>', options).then(console.log, console.error);
```

shows no body data.

**Comment by qubyte** [comment]
Hmm, that said, it does seem to work for postcatcher. The difference seems to be supplying the `content-length` header.

**Comment by bitinn** [comment]
I would debug along those lines too, if it works with `httpbin` and in our tests, I find it hard to explain why does it not work with others. You may try use our test server (in the test folder) to get the exact headers being sent, and try replicating it with `curl` as well.

**Comment by qubyte** [comment]
You're right. Everything appears to be working fine. Apologies. :)

**Comment by AliqueWilliams** [comment]
I'm receiving the same issue. I haven't been able to solve it all day.
http://stackoverflow.com/questions/38885004/posting-data-using-node-fetch-in-a-react-component-malfunction

**Comment by matrus2** [comment]
The same here: 
```
import fetch from 'node-fetch';
import FormData from 'form-data';

const form = new FormData();

form.append('token', 'asdasd');
form.append('ref', 'master');
fetch(`http://httpbin.org/post`, { method: 'POST', body: form, headers:form.getHeaders() })
  .then(res => {
      console.log('Pipeline build created');
  })
  .then(console.log('Next Promise'))
  .catch(e => console.log(e));
```
:(

**Comment by qubyte** [comment]
@matrus2 That's because:

```javascript
.then(console.log('Next Promise'))
```

should be

```javascript
.then(() => console.log('Next Promise'))
```

**Comment by matrus2** [comment]
Thx, removing than to not to leave mess.

**Comment by leicj** [comment]
i had the same error.
the question is: we receive the body data using req.body, it is {}.
could you show the http://httpbin.org/post source code, let me see why you could return the data?

**Comment by bitinn** [comment]
@leicj see https://github.com/bitinn/node-fetch/issues/16#issuecomment-97489994

If you got `json()` working, there is no reason for body to be empty, you are mixing up something.

**Comment by Uzebeckatrente** [comment]
@leicj did you ever figure this out? I've been trying to fix the same but as you for the past 5 hours. The post request works when I call it from a form action but not using node-fetch, which is really what I need (or some other asynchronous post library...)

**Comment by ashishmangla0** [comment]
hello to all i am trying to post data using node Fetch but i am geeting error
here is my code 
app.get("/savefdfordemo",function (req,res) {
    res.render('demo/demo1.html')
})

app.post("/savefdfordemo/demo",function (req,res) {

    fetch('http://149.56.37.27:3000/savefdfordemo', { method: 'POST', body: JSON.stringify(req.body),headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    } })
        .then(function(res) {
            return res.json();
        }).then(function(json) {
        console.log(json);
    }).catch(function(err) {
        console.log(err);
    });
    res.render('errors/404.html')

})

why body is empty dont know

**Comment by Elliot128** [comment]
Seeing the same issue with failing to send a post method. Tried with `application/json` content-type, and with a body. 
```
fetch(URL, {method: 'POST'})
```
