### ISSUE TITLE
Redirects not followed when 'follow' option is provided but non-zero 'counter' is not

### ISSUE THREAD

**Issue by GalenWarren** [bitinn/node-fetch#161]
If you supply an integer for the 'follow' option but don't supply a nonzero 'counter' option, counter is initialized to the value of follow in the Request constructor and so redirects aren't followed.

**Comment by bitinn** [comment]
No, you shouldn't set `counter` directly. It's an internal counter for maximum redirect limit.

**Comment by GalenWarren** [comment]
Yeah, perhaps the title of the issue wasn 't the best here, sorry if it was confusing. But the issue is real, I think. What I'm saying is that if you *do* supply a value in options for follow (say follow=20) but *don't* supply an explicit non-zero value for 'counter' in the options (so, if you either omit 'counter' entirely, as you point out one should, or if you were to explicitly pass counter=0), then 'counter' winds up getting initialized to the value of 'follow' -- in this example, 20. This means it will not follow redirects since 'counter' already equals 'follow'.

I found this while trying to use this library as a polyfill for aurelia-fetch-client, which does pass in a value for 'follow' but not for 'counter', and in that case it doesn't follow redirects. With the change in the pull request, it behaves as expected (follows redirects).'

**Comment by bitinn** [comment]
You are right, don't know how `input.follow` got in there, will be fixed later today.

**Comment by bitinn** [comment]
fix released as v1.6.1

**Comment by GalenWarren** [comment]
Thanks!
