### ISSUE TITLE
Error handling examples...

### ISSUE THREAD

**Issue by dandv** [bitinn/node-fetch#163]
...would help the README. Thanks!

**Comment by bitinn** [comment]
Yeah I agree, will do that soon.

Though it's quite simple, `fetch('/api').catch(function(err))`.

**Comment by bitinn** [comment]
updated

**Comment by DDChiang** [comment]
How would we go about handling server errors (4xx- 5xx errors) since the catch function doesn't "catch" those?

**Comment by bitinn** [comment]
@DDChiang you don't, because 4xx-5xx are not errors in Fetch Spec.

use [res.ok](https://github.com/bitinn/node-fetch#responseok) to easily distinguish 2xx and other responses.
