### ISSUE TITLE
VPN getaddinfo ENOTFOUND

### ISSUE THREAD

**Issue by milesthedisch** [bitinn/node-fetch#164]
This is a issue regarding node-fetch through a VPN.

Right now Im using a server to fetch some data through a VPN.

The error that im getting is `reason: getaddrinfo ENOTFOUND`.

When I hit the URL in the browser the request comes back with the right data. Its only when i hit the endpoint with node-fetch it gives me that error.

Any suggestions?

**Comment by bitinn** [comment]
It's from system (core Node.js), not us, and that error usually means DNS problem (node-fetch doesn't handle DNS, core Node.js does that).

**Comment by milesthedisch** [comment]
@bitinn 👍
