### ISSUE TITLE
Expose and document Response and Headers

### ISSUE THREAD

**Issue by wheresrhys** [bitinn/node-fetch#17]
I'm working on a utility for making unit testing code that uses fetch easier https://github.com/wheresrhys/fetch-mock. I'm relying on your `Response` and `Headers` classes, but as these are not exposed directly I'm having to include them via `require('node-fetch/lib/Response'). I'd be a lot more comfortable relying on them if the path to these files was documented or they were exposed as properties on the Fetch constructor. Would you be open to doing this?

**Comment by bitinn** [comment]
I am ok with exposing them, browsers are doing that already. But they won't be substitutable like `Fetch.Promise` (and hopefully there isn't a reason to do so).

**Comment by wheresrhys** [comment]
Great - see PR above

**Comment by bitinn** [comment]
released as v1.2.0

**Comment by wheresrhys** [comment]
... and several hours later this was born https://www.npmjs.com/package/fetch-mock. Thanks for your help
