### ISSUE TITLE
Only absolute urls are supported

### ISSUE THREAD

**Issue by riteshatsencha** [bitinn/node-fetch#171]
Hi,

I am developing a vscode extension and keep receiving "Only absolute urls are supported" in node-fetch module. 

file : index.js
line # : 54

```
// wrap http.request into fetch
	return new Fetch.Promise(function(resolve, reject) {
		// build request object
		var options = new Request(url, opts);

		if (!options.protocol || !options.hostname) {
			throw new Error('only absolute urls are supported');
		}
```

Any idea?

Thank you

**Comment by bitinn** [comment]
That's too little information, you need to show us the full trace stack and let us know what you are using `node-fetch` for.

**Comment by riteshatsencha** [comment]
Ah, thanks for a quick response. Issue was at my end. My bad! I will be closing the thread.
