### ISSUE TITLE
Cloned body stream got stuck somehow?

### ISSUE THREAD

**Issue by emirotin** [bitinn/node-fetch#172]
I'm not sure if I can create an isolated test case for this (but I'd try).
But here's the explanation of the issue I've been fighting for a couple of days.

I have a method that:
- starts the request
- pipes the body trough a series of streams (like estimate size, unzip, etc)
- returns the final stream everything is piped to
- and also attaches the original response object as a property to the output fo further examination by the caller code.

I have to note that I was working on migrating the original codebase (written by another person) from `request` to `fetch`, so my intent was to keep methods close to the original implementation and keep the test suite mostly unchanged.

So as I was also returning the original response to the outer world I decided it would be safe to clone it before piping.

My code then looked roughly like that:

```
  output = new stream.PassThrough()
  output.response = response

  responseStream = response.clone().body // <!--
  responseStream.pipe(progressStream).pipe(gunzip).pipe(output)
  return output
```

The caller code was then piping it to the fs writable stream.
It always used to write ~4.1Mb and nothing happened then (the real download is quite big, about 1Gb).
As soon as I've removed the clone call in the marked line things started working as expected.

Any idea from the top of your head why that could happen?

**Comment by bitinn** [comment]
see #151, you will need to resolve both stream, not one and the other.

**Comment by emirotin** [comment]
Thanks. I saw a couple of mentions of back-pressure and assumed it's related but didn't understand it fully.
When you say resolve do you mean draining it? If so it means I cannot read the stream myself and return it for further usage by the caller that is out of my control, right?

**Comment by bitinn** [comment]
> When you say resolve do you mean draining it?

Yes drain it in parallel, not in sequence. Because when you start reading one of them, the other will be have to "flow" as well. So internal buffer (of pass through stream) will fill up and eventually block both streams.

Better explanation here: https://github.com/substack/stream-handbook

**Comment by emirotin** [comment]
Yeah, than handbook is in my to-read list :)
Thanks for the answer, I still have to wrap my head around the paradigm.
