### ISSUE TITLE
response.json return an object with whatwg fetch, but return a promise with node-fetch 

### ISSUE THREAD

**Issue by funkjunky** [bitinn/node-fetch#178]
This incompatibility messes with isomorphic-fetch.

**Comment by bitinn** [comment]
An example would help.

Also response.json() should always return a promise.

**Comment by funkjunky** [comment]
Ya sorry for the lack of example.

On the client the following would print out the data as an object:

    fetch('localhost:8000/api/articles').then((r) => r.json).then(console.log);

On the server, the above doesn't work. I had to add to CALL the r.json function. Ie.:

    fetch('localhost:8000/api/articles').then((r) => r.json()).then(console.log);

TBH I haven't tried the second example on the client side yet, because I've been focusing wholly on getting the server side to work at the moment and therefor have ignored client for a bit.

**Comment by jimmywarting** [comment]
Whoot?? the first example is wrong... `r.json` is a function and should be called as a function.

It's weird that it returns a object. It should log a function like it dose on any other website
```javascript
fetch('localhost:8000/api/articles').then((r) => r.json)
.then(console.log); // function json() { [native code] }
```

**Comment by funkjunky** [comment]
I agree... ya know what, Imma close this, because I have a feeling returning r.json() well work on the client. If there is a bug, it would be in the poly-fill whatwg and it would be only an un-intended feature, rather than something not working.

If r.json() doesn't work on client, I'll ask again. I realize my mindset was wrong when I asked about this.

**Comment by funkjunky** [comment]
I just want to mention it worked find client side.

So the only risk here is the gotchya that anyone else may try to simply return response.json without calling it, have it work on client, and get confused on server.

**Comment by bitinn** [comment]
> I just want to mention it worked find client side.

It's not part of the standard, you shouldn't use it, and we are not here to support every possible unknown features that browser potentially support.

And user should return a promise, that's how you handle a promise chain.
