### ISSUE TITLE
Charset detection

### ISSUE THREAD

**Issue by TimothyGu** [bitinn/node-fetch#184]
Originally reported by @gwicke in gwicke/node-fetch-polyfill#1.

Currently, node-fetch attempts to automatically detect the encoding of the input source, and [convert](https://github.com/bitinn/node-fetch/blob/e926483448c675b7443d2c085c49cee9d4619120/lib/body.js#L147) it to UTF-8. However, the [Fetch Standard](https://fetch.spec.whatwg.org/#concept-body-package-data) says that only a plain UTF-8 decode should be performed, regardless of the actual input encoding. As written in the referenced issue and confirmed by myself, the spec behavior is what's implemented by the browsers.

A few options:

1. Keep the current behavior
2. Remove conversion process
3. Use an option (e.g. `res.text({ convert: true })`)
4. Make a new method (e.g. `res.textConverted()`)

I'm leaning towards 4. 1 makes this module incompatible with the browser (something I don't want to do), 2 makes transition to v2 more difficult for people already using this library, and I'm reluctant to modify the behaviors of a well-defined function such as `.text()`.

Thoughts?

**Comment by bitinn** [comment]
Option 4 would be convenient for developers, but I do wonder if we should keep the API out of Response Class, could it be Fetch.toUTF8?

(I remember myself asking about it on whatwg github and they offer a simple workaround to me.)

From my phone,
David

**Comment by bitinn** [comment]
OK I just checked, it's not worth going through this:

https://github.com/whatwg/fetch/issues/353#issuecomment-237476765

I support option 4.

**Comment by TimothyGu** [comment]
Fixed by #188.
