### ISSUE TITLE
Switch to a new coverage tracker

### ISSUE THREAD

**Issue by TimothyGu** [bitinn/node-fetch#186]
Coveralls is often buggy, causing false positive test results like https://travis-ci.org/bitinn/node-fetch/jobs/167229741#L960. In my experiences I've used [Codecov](https://codecov.io), which is a more solid solution I feel (which is why I started transitioning things for Pug to Codecov).

**Comment by bitinn** [comment]
I have never used codecov before so can't provide a good argument for/against it.

**Comment by TimothyGu** [comment]
Codecov enabled in v2. Check it out at https://codecov.io/gh/bitinn/node-fetch

**Comment by bitinn** [comment]
Yep codecov does seem to provide more info, so good job on adding it.
