### ISSUE TITLE
Failed JSON sending

### ISSUE THREAD

**Issue by AMalininHere** [bitinn/node-fetch#190]
Sometimes promise received from following code can't be processed.
Same code works fine in Chrome 53.

```js
fetch(`${host}/some`, {
  method: 'post',
  headers: {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${auth.access_token}`
  },
  body: JSON.stringify({
    front: frontId,
    side: sideId
  })
});
```

Equivalent written in `request-promise` works fine.

```js
rp({
  method: 'POST',
  uri: `${host}/some`,
  body: {
    front: frontId,
    side: sideId
  },
  headers: {
    'Authorization': `Bearer ${auth.access_token}`
  },
  json: true
})
```

**Comment by bitinn** [comment]
This does not provide us with the most important information: what error are you getting? what response are you getting?

**Comment by AMalininHere** [comment]
@bitinn. No errors. Callbacks registered by `.then` NEVER triggers. When I remove one header that code works fine.

**Comment by bitinn** [comment]
> Callbacks registered by .then NEVER triggers

When there is an error, you need to `catch()` it. Node.js http.request cannot stall forever, if it does then it's a core-level bug.

ref:
- https://github.com/bitinn/node-fetch#usage
- https://github.com/bitinn/node-fetch/blob/master/ERROR-HANDLING.md

**Comment by AMalininHere** [comment]
I know that `.then` has two arguments: on success and error (see [promise on MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)). So neither first nor second doesn't trigger.

**Comment by bitinn** [comment]
Closing this as there is no sample code to reliably reproduce this error.
