### ISSUE TITLE
https error - ec_GFp_simple_oct2point:point is not on curve

### ISSUE THREAD

**Issue by diginfo** [bitinn/node-fetch#191]
Hi;

This is on arm raspberry pi, when I attempt to connect to a secure https url I get the following error:

```
"write EPROTO 1889480704:error:1006706B:elliptic curve routines:ec_GFp_simple_oct2point:point is not on curve:../../third_party/node/deps/openssl/openssl/crypto/ec/ecp_oct.c:417:
1889480704:error:1408D132:SSL routines:ssl3_get_key_exchange:bad ecpoint:../../third_party/node/deps/openssl/openssl/ssl/s3_clnt.c:1869:"
```

Connecting to the exact same host using http and not https is fine, any suggestions on what the cause or fix may be ?

**Comment by TimothyGu** [comment]
That sounds like an HTTPS error. Does using other tools, like curl or `https` module directly, work?

**Comment by diginfo** [comment]
Thanks for helping, I can use curl successfully from the command line to get both https and http request ?!

**Comment by TimothyGu** [comment]
How about <code><a href="https://nodejs.org/api/https.html#https_https_request_options_callback">https.request</a></code>?

**Comment by TimothyGu** [comment]
Timed out.
