### ISSUE TITLE
FormData not recognized? 

### ISSUE THREAD

**Issue by goodhyun** [bitinn/node-fetch#192]
We are building an electron app, and tried to use node-fetch, as the native fetch's "origin: null" is not accepted by some of our server-sides. 
However, FormData doesn't seem to be properly recognized.
![2016-10-21 2 07 36](https://cloud.githubusercontent.com/assets/4727708/19570716/257c97c0-9736-11e6-89d0-47357efd81f1.png)

Our code is nothing special and it works well with the built-in fetch.

```
let fd = new FormData()
fd.append('title', params.title);
fd.append('content', params.content);
for (var i=0; i<images.length; i++)
        fd.append('media[]', images[i], filenames[i]); 
let res = await fetch('http://httpbin.org/post', {
        method: requestMethod,
        headers: {
          Authorization: "Bearer " + token.accessToken,
        },
        body: fd,
      })
let data = await res.json()
```

FormData is also a built-in one, but I tested with the node form-data and ended up with the same result.

Isn't it really weird?

**Comment by TimothyGu** [comment]
It _should_ work with Node.js FormData, and we have [tests](https://github.com/bitinn/node-fetch/blob/master/test/test.js#L677-L695) to test both form-data@2 and form-data@1. What version of Node.js form-data module are you testing? Browser FormData unfortunately will not work.

**Comment by goodhyun** [comment]
Thanks for the comment,
Looks like node form-data wasn't kicked off at all at the webpack environment, and fell back to the browser one. 
[https://github.com/form-data/form-data/issues/252](url)

I simply removed the `browser` line from package.json of form-data, and it kinda worked.

**Comment by goodhyun** [comment]
only if I removed these lines: 
```
for (var i=0; i<images.length; i++)
        fd.append('media[]', images[i], filenames[i]); 
```

These will produces 
`source.on is not a function`

**Comment by TimothyGu** [comment]
Okay, I guess it's not our bug then.
