### ISSUE TITLE
Not automatically decompressing Twitter bearer token

### ISSUE THREAD

**Issue by brandon-arnold** [bitinn/node-fetch#193]
I am sure I am missing something, but searching the doc and Google a while, I'm stuck.

The snippet below performs a request to Twitter's API for a bearer token:

```javascript
  let twitterCreds = btoa(auth.twitter.key + ':' + auth.twitter.secret);
  const oauthBearerUrl = 'https://api.twitter.com/oauth2/token';
  const oauthBearerMsg = {
    method: 'POST',
    headers: {
      'Authorization': 'Basic ' + twitterCreds,
      'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
    },
    body: 'grant_type=client_credentials',
    // 'accept-encoding': 'gzip,deflate',
    // compress: true,
  };

  const twitterBearer = await fetch(oauthBearerUrl, oauthBearerMsg);
```

The eventually output of this SHOULD be as follows, as I'm getting from Postman with the same request:

```json
{
  "token_type": "bearer",
  "access_token": "..."
}
```

Furthermore, `fetch` is getting a response with "Status: 200" from Twitter. The problem is it seems to still be uncompressed, as the `Body` member has child `Gunzip`. But I thought node-fetch was supposed to automatically decompress it. I have tried changing the `accept-encoding` and `compress` parameters as above to no avail.

**Comment by bitinn** [comment]
If the body is not decompressed correctly, you should be getting parser error during `.json()`, what did you get in the end?

**Comment by brandon-arnold** [comment]
Thanks, @bitinn. The result of `console.log(res.headers.get('content-type');` is `application/json;charset=utf-8` with encoding `gzip`. The result of `console.log(res.json())` is 

```json
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
```

**Comment by brandon-arnold** [comment]
The lines to print the above are as follows:

```javascript
  const twitterBearer = fetch(oauthBearerUrl, oauthBearerMsg).then(
    (res) => {
      console.log(res.headers.get('content-type'));
      console.log(res.json());
      return res;
    });
```

**Comment by bitinn** [comment]
`res.json()` is a promise API, meaning, you need to then/yield/await it.

**Comment by bitinn** [comment]
just checkout out readme: https://github.com/bitinn/node-fetch#usage

**Comment by brandon-arnold** [comment]
Ah, that was the ticket. Sorry for the inconvenience! Thanks!
