### ISSUE TITLE
Add ENV http_proxy support

### ISSUE THREAD

**Issue by gajus** [bitinn/node-fetch#195]
Basically, every time I use this package, the first thing that I need to do is to write an abstraction that enables use of HTTP_PROXY env variable.

Something like this:

```js
import fetch from 'node-fetch';
import HttpsProxyAgent from 'https-proxy-agent';

export default (url: string, options: Object = {}) => {
  const instanceOptions = {
    ...options
  };

  if (!options.agent && process.env.HTTP_PROXY) {
    instanceOptions.agent = new HttpsProxyAgent(process.env.HTTP_PROXY);
  }

  return fetch(url, instanceOptions);
};
```

I'd like this package to support it out of the box.

Using `HTTP_PROXY` and `HTTPS_PROXY` variables to configure proxy setting of an application is a well establish convention, https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=http_proxy%20environment%20variable.

**Comment by TimothyGu** [comment]
Unfortunately I think that's a different level of abstraction than node-fetch. The Fetch Standard says nothing about this, and similar modules like `request` or `got` don't have any special handling for the environmental variable either.

You might find the [global-tunnel](https://github.com/salesforce/global-tunnel) module helpful.

**Comment by gajus** [comment]
> and similar modules like request or got don't have any special handling for the environmental variable either.


They do:

* https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
* While Got is in a process of adding it, https://github.com/sindresorhus/got/issues/79

**Comment by bitinn** [comment]
@gajus I would encourage you to package it as a module, I think there is a good use case for it, in fact, there may be packages out there already.

**Comment by gajus** [comment]
> @gajus I would encourage you to package it as a module, I think there is a good use case for it, in fact, there may be packages out there already.

Package what as a model?

**Comment by gajus** [comment]
This is so annoying. It must be the 10th time I am coming back to this post just to copy that fragment. There is absolutely no reason not to support it.

**Comment by gajus** [comment]
https://github.com/gajus/xfetch

**Comment by jamesseanwright** [comment]
I have to agree with @gajus on this. In fact I feel that supporting `HTTP_PROXY` is ideal as it doesn't break the modules contract, which of course is modelled upon the WHATWG spec.

I would migrate to his module but the codebase on which I'm working is using isomorphic-fetch, which unfortunately provides yet another level of abstraction.

Do you ever envisage supporting this?

**Comment by ilanc** [comment]
Thanks @gajus. Now I can see my node-fetch requests in Fiddler in Windows.

Useful blog article on the topic: https://weblogs.asp.net/dixin/use-fiddler-with-node-js
thanks @Dixin

```
var fetch = require('node-fetch');
const _fetch = fetch; // for fiddlerProxyOn / fiddlerProxyOff
const HttpsProxyAgent = require('https-proxy-agent');

fiddlerProxyOn();

console.log('-----------------------------------');
console.log('manual form data');
console.log('-----------------------------------');

fetch('http://httpbin.org/post', { method: 'POST', body: 'a=1&b=2' })
  .then(function (res) {
    return res.json();
  }).then(function (json) {
    console.log(json);
  });

const FormData = require('form-data');

//fiddlerProxyOff();

const form = new FormData();
form.append('a', 1);
fetch('http://httpbin.org/post', { method: 'POST', body: form })
  .then(res => res.json())
  .then(json => {
    console.log('-----------------------------------');
    console.log('form-data');
    console.log('-----------------------------------');
    console.log(json)
  });

// Fiddler support
// https://weblogs.asp.net/dixin/use-fiddler-with-node-js
// https://github.com/bitinn/node-fetch/issues/195

function fetchViaProxy(url, options) {
  let instanceOptions = options;

  if (!options.agent && process.env.HTTP_PROXY) {
    instanceOptions = Object.assign({}, options);
    instanceOptions.agent = new HttpsProxyAgent(process.env.HTTP_PROXY);
  }

  return _fetch(url, instanceOptions);
}

function fiddlerProxyOn() {
  var proxyUrl = "http://127.0.0.1:8888";
  fetch = fetchViaProxy;
  process.env.HTTP_PROXY = proxyUrl;
  process.env.HTTPS_PROXY = proxyUrl;
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
}

function fiddlerProxyOff() {
  fetch = _fetch;
  process.env.HTTP_PROXY = "";
  process.env.HTTPS_PROXY = "";
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "";
}
```

Fiddler view:
![image](https://user-images.githubusercontent.com/1793957/27560597-164ff0fa-5ac5-11e7-9dca-96d1efd24af5.png)

**Comment by tstibbs** [comment]
What a shame this request was dismissed so quickly. Yes, I can use global-tunnel, but having to copy around snippets of proxy config into _every single node script I write_ really should not be required. Env vars are a well-established way to pass proxy config to programs, it makes a lot of sense to implement it at the core of the module making the requests - even if it isn't mentioned in the spec.

**Comment by bitinn** [comment]
I should note that there are already ways to achieve what you want:

- You can pass in a http proxy agent to node-fetch: https://www.npmjs.com/package/http-proxy-agent
- You can just replace the global http agent.

I have argued for a global proxy setting inside nodejs core (which should be respected by `http.request` so all module get the benefit, instead of each module doing they own proxy setting handling), but there are many ways to setup a proxy or a tunnel, nodejs team doesn't feel like adding it:

- https://github.com/nodejs/node/issues/1490

So the status quo is: **no universal proxying in nodejs**. You have to setup your own with your favorite http library.

Plus, environment variable is something a *program* (be it command line or app) would respect, not something a *library* would normally do. `got` never got around to implement it neither. So I think it's safe to say `request` is taking on more burden than a http library would need.

To end, I feel your pain, I live in China and the network there really sucks, but it's not something a http library should help fix.

**Comment by zicklag** [comment]
For anybody who stumbles on this issue like I did, the easiest way to support http proxies that I've found so far is to use [`global-agent`](https://github.com/gajus/global-agent). It's super easy to install and worked for me so far.
