### ISSUE TITLE
No way to disable Agent with options

### ISSUE THREAD

**Issue by voodootikigod** [bitinn/node-fetch#196]
Due to the shortcutting in line: https://github.com/bitinn/node-fetch/blob/master/lib/request.js#L51 one cannot opt out of the pooling provided by the http/https library. Setting `options.agent = false` causes this to operate and use the other side of the `||` statement, which is undefined, opting into the pooling and using the global agent.

This can cause use cases that aren't as expected and aren't in accordance with the node.js http documentation. https://nodejs.org/api/http.html#http_class_http_agent

**Comment by bitinn** [comment]
Actually there is one way, don't pass in the `connection: keep-alive` header, which is a default.

https://github.com/bitinn/node-fetch/blob/master/index.js#L79-L81

**Comment by TimothyGu** [comment]
As #197 is closed, I assume this issue is not applicable either.
