### ISSUE TITLE
What is the proper way to abort an infinite response?

### ISSUE THREAD

**Issue by voxpelli** [bitinn/node-fetch#203]
When doing a request against a realtime API that returns an infinitely long API response, such as a newline delimited stream of JSON objects representing new activities in a system, what is the proper way to abort it if one no longer wants to listen to it?

Just stopping the consumption of the stream doesn't abort the request, at the moment at least. Something more is needed and if I remember correctly then the proper Node.js way of aborting would be to call `.destroy()` on the response `IncomingMessage`, as described in eg. [the node.js docs](https://nodejs.org/api/http.html#http_message_destroy_error).

Calling `.destroy()` isn't currently doable though as the `IncomingMessage` isn't exposed in the `Response` and thus not reachable for any code outside of node-fetch itself.

The way to cancel the response in the browser would seemingly instead be to call `.cancel()` on the  `ReadableStream`, as specified by [the streams spec](https://streams.spec.whatwg.org/#rs-cancel) and eg. [described by Jake Archibald](https://jakearchibald.com/2015/thats-so-fetch/#streams), but neither that is implemented,

Maybe the proper solution to this would be to implement the `.cancel()` and have that call, among perhaps other things, the `.destroy()` on the `IncomingMessage`?

This is probably similar to #95

**Comment by bitinn** [comment]
I have replied in #204 about the status quo of cancellable fetch (TL;DR: not great).

But if you must use Fetch API for JSON streaming, let's see if there are other workarounds:

- Can you use a [custom agent](https://nodejs.org/api/http.html#http_agent_destroy) to destroy the socket? `node-fetch` allow passing an agent for this kind of purpose.

- Can you set a long `timeout` so that you can consistently re-initiate the request?

(Note that only `node-fetch` supports these, as [client-side development on these are not yet in progress](https://github.com/whatwg/fetch/issues/180).)

**Comment by bitinn** [comment]
And note that the whole Fetch mental model is:

- If your response is complete, promise is fulfilled (even if response is 404).
- If your response is running, promise is pending.
- If your network/remote-server is down, promise is rejected (even if you terminate it manually).

So if you use Fetch with JSON streaming, you should expect promise handling to be a bit weird in your code.

**Comment by voxpelli** [comment]
Answered in #204, but core take away: This is about canceling responses, not requests. The requests are successful and the promises are fulfilled, but as the responses are infinite there's a need to cancel them as well because they will never finish on their own.

**Comment by TimothyGu** [comment]
As far as HTTP is concerned, "cancelling the response" means the same thing as discarding the rest of the response and close the socket. Both of these things are accomplished in Node.js with `req.abort()` -- aborting the request itself.

I'll merge this with #95.
