### ISSUE TITLE
timeout option does not seem to work

### ISSUE THREAD

**Issue by andrelevi** [bitinn/node-fetch#207]
Hi,

My usage looks like:

```
    fetch(ENDPOINT, {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: ...,
        timeout: 3000
    })
```

but the fetch never successfully times out. It just hangs forever.

Do I need to accompany my `timeout` property with another related property for it to work?

Thanks!

**Comment by bitinn** [comment]
Nope, timeout is enough, and only thing that extends it is server redirect. Test out your request with httpbin.

(From my phone)

**Comment by andrelevi** [comment]
Sorry, this ended up being an issue with code! Thanks for your help.
