### ISSUE TITLE
Releasing v2.0

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#209]
There are enough authors in the original issue #8, I don't want to spam them until we are ready.

So, remaining tasks in my head:

- [x] Get back to 100% coverage (we are close, but not there yet).
- [x] Write up an upgrade guide (important for people willing to test 2.0-alpha).
- [x] Changelog and Readme update.

I have added @TimothyGu to npm owner list, many thx for his work to drive v2.0. Also special thx to @jimmywarting and others for collaborating.

Now, please let me know if I have missed anything.

**Comment by TimothyGu** [comment]
Okay, great. Unfortunately I still have a bit of homework to finish before I can work on this, but do you think #177 can be merged into master at this point?

**Comment by bitinn** [comment]
Feature-wise it's a great leap forward, I personally would be more comfortable with improved test coverage and a changelog update.

Is it a good idea publish alpha with a custom branch? I admit I haven't done much alpha releases with npm. I will listen to best practices.

**Comment by TimothyGu** [comment]
Okay, I'll proceed by improving test coverage first.

Releases on npm don't really correspond to a GitHub branch, so no worries on that end.

**Comment by jimmywarting** [comment]
Would really like to see the v2 released on npm soon 😕
