### ISSUE TITLE
progress indicator

### ISSUE THREAD

**Issue by aeosynth** [bitinn/node-fetch#21]
i'd like to see the current progress of my requests, to check if they've stalled. there doesn't seem to be an official solution for this.

**Comment by bitinn** [comment]
This is probably out of scope for `node-fetch`, but by using `res.body`, which is a stream, you can probably achieve the same thing?

see example like:
https://github.com/freeall/progress-stream
https://github.com/tj/node-progress

**Comment by slang800** [comment]
yeah, this should be closed... send requests for spec changes to https://fetch.spec.whatwg.org/ if you cannot implement request progress using the exposed api.
