### ISSUE TITLE
Expected fragment to be removed

### ISSUE THREAD

**Issue by jimmywarting** [bitinn/node-fetch#211]
Differs from node-fetch and browsers (spec)
```js
var request = new Request('http://example.com#foo')
var expected = 'https://example.com/'
console.assert(expected === request.url, 'excepted url to remove fragment')
```

**Comment by TimothyGu** [comment]
Are there any indications that the spec demands the fragment to be removed? I only see fragments being mentioned in the Response section in the spec.

**Comment by jimmywarting** [comment]
Not sure it's a fetch spec per say...

XMLHttpRequest, fetch, link.href, script.src, a.href, img.src all remove fragments on every request

Fragments never gets sent to the server it only sticks around in the navigation bar

**Comment by bitinn** [comment]
I think the question is whether fragment is stripped downstream (by http.request), I have never tried it. I don't think Fetch Spec explicitly require Request class to strip `req.url`?

**Comment by jimmywarting** [comment]
But it dose so in the browser... 😕

**Comment by bitinn** [comment]
You have to extinguish the _actual request_ from the _Request_ object. I understand the actual request won't have fragments. Does Fetch API on major browsers strip fragment in `req.url` on `new Request()` consistently?

**Comment by jimmywarting** [comment]
Opera, Firefox, Chrome on Mac all stripped the fragment from the url. Safari don't have fetch yet

    new Request("https://example.com#foo").url -> "https://example.com/"

**Comment by TimothyGu** [comment]
@jimmywarting, can you run this through WHATWG and see what they have to say about this? https://github.com/whatwg/fetch

**Comment by bitinn** [comment]
Provided for context:

- https://github.com/whatwg/fetch/issues/214
- https://github.com/whatwg/fetch/issues/84

**Comment by bitinn** [comment]
And seems like Firefox tried to expose fragment: https://bugzilla.mozilla.org/show_bug.cgi?id=1264178

**Comment by TimothyGu** [comment]
I believe right now the situation is:

- The spec says Request should have fragment but Response should not
- Both Firefox and Chrome do not have fragments for either Request or Response
- Firefox has just changed their Request to have fragments

**Comment by bitinn** [comment]
If you look at [the last link](https://github.com/w3c/ServiceWorker/issues/910) though, author of Fetch Spec incline to allow fragment, and there are other component that sends fragment to server.

I will say we put this on hold.

**Comment by jimmywarting** [comment]
> I will say we put this on hold.

Agree - it's confusing atm

**Comment by TimothyGu** [comment]
Both Chrome and Firefox now returns a URL **with** fragment for `new Request('http://example.com#foo').url`, consistent with the spec. I don't think this is an issue anymore.
