### ISSUE TITLE
Uploading Streaming Binary Data using Node Fetch

### ISSUE THREAD

**Issue by pianeer** [bitinn/node-fetch#213]
I have a question on how to go about uploading content to an endpoint that accepts only binary data. I have the file on disk and want to stream the content as binary but am having difficulties using `node-fetch`. Here is some sample code of what I'm trying to do. Any pointers would help, I don't know if this is an issue with node fetch not being able to support binary streams or my usage of it not being accurate:

```js
  const bodyData = fs.createReadStream(req.file.path) // file stored locally on disk
  return fetch(uploadEndpoint, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': req.file.mimetype
    },
    body: bodyData
  })
```

Any pointers would help!

**Comment by TimothyGu** [comment]
This *should* work, and we even have a [test](https://github.com/bitinn/node-fetch/blob/4d944365dfeff3ab0cb8b978c1e6fa9e3b640e2e/test/test.js#L679-L696) that makes sure POST requests work with body data.

What kind of issues are you seeing?

**Comment by pianeer** [comment]
Do I need to use something like `resumer`? My problem is that the endpoint reports not receiving binary data. So for example, I'm trying to upload a PDF document that's about 218 KB but the endpoint reports receiving it with the content length of 597 bytes which doesn't make sense since it should be 218882 bytes(~218 KB). Do you think `bodyData` above is not binary content?

**Comment by bitinn** [comment]
> Do I need to use something like resumer?

Nope, just a normal stream.

I think you need to first figure out if you are indeed passing it a stream and if your endpoint supports `chunked` encoding. If you are doing streaming upload, the content-length shouldn't be set, because we are using `transfer-encoding: chunked`.

**Comment by pianeer** [comment]
Yes the endpoint does support chunked encoding and I'm not explicitly setting the `content-length` header. Also, do you think I need to `pipe` the stream via `fetch`? I'm not quite sure what that would look like though.

**Comment by bitinn** [comment]
If you can, try a simple example like our test cases first, isolate your problem.

**Comment by pianeer** [comment]
I've tried your test case but I finally ended up using a promisified `request` since it had streaming built right in and I needed streaming for my use case with an `fs.createReadStream`

**Comment by TimothyGu** [comment]
@pianeer, you have to give more details than that to help us debug this issue. Can you please give a test case?

**Comment by TimothyGu** [comment]
Timed out.
