### ISSUE TITLE
SNI connection

### ISSUE THREAD

**Issue by gusdaud** [bitinn/node-fetch#218]
Does the library supports SNI when connecting to TLS ?

Here's what I'm trying to do and it doesn't work:

```
      // Options for the HTTPS agent, adds certificate if available
      var agentOptions = {
        rejectUnauthorized: false,
        cert: myCertificateString,
        key: myKeyString,
        passphrase: 'password'
      };

      // Options for the fetch call
      var options = {
        servername: 'myserver.com',
        credentials: 'same-origin',
        body: '{"send":true}',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization = 'Basic ' + btoa('use-token-auth:' + item.token);
        },
        agent: new https.Agent(agentOptions)
      }

      // Cals the API
      fetch('https://myserver.com/myapi', options)
```

It seems that servername variable is not being passed on but I'm not sure if it's the only issue.

**Comment by bitinn** [comment]
We don't support the servername keyword in our API, see readme. I don't see why you need to specify servername though, unless nodejs core doesn't support SNI.

(From my phone)

**Comment by gusdaud** [comment]
Hi, I'm having some trouble connecting with a server that requires SNI and I've found this article that says that servername might help solving it:
http://www.thedreaming.org/2016/09/27/nodejs-ssl/

**Comment by bitinn** [comment]
That `servername` keyword should be used in your Agent, and past in as the `agent` option.

https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by gusdaud** [comment]
Thanks, I'll try that

**Comment by Hornobster** [comment]
> That `servername` keyword should be used in your Agent, and past in as the `agent` option.
> 
> https://nodejs.org/api/https.html#https_https_request_options_callback

Hi, maybe I've misinterpreted your answer, but it seems that, even from the link you've posted, the `servername` option should be specified in the request options not in the agent options (after all, it's a property of the single request).

Is there a way to pass the `servername` options to tls.connect using `fetch`?
