### ISSUE TITLE
Header values in array?

### ISSUE THREAD

**Issue by karpikpl** [bitinn/node-fetch#219]
Hey,
here's the code that I have for both node-fetch and http:
```javascript
const options = {
            host: this.serverUrl,
            port: this.serverPort,
            path: `${Config.get('/bitbucket/path') || ''}/rest/api/1.0/projects/${project}/repos/${repository}/pull-requests/${id}`,
            method,
            headers: {
                'Authorization': this.auth,
                'Content-Type': 'application/json'
            }
        };

// Fetch
const opts = { method: 'GET', headers: options.headers };
        Fetch(`https://${options.host}:${options.port}${options.path}`, opts)
            .then((res) => {
                return res.json();
            });

// http
const req = Https.request(options, (res) => {
   // ...
}
```

I'm using Nock for testing and Fetch request is not matched, but http one is. My investigation found that headers differ:
Fetch:
```
path: /rest/api/1.0/projects/PROJECT_1/repos/rep_1/pull-requests/25
headers: { authorization: [ 'Basic XXXXXXX' ],
  'content-type': [ 'application/json' ],
  'accept-encoding': [ 'gzip,deflate' ],
  'user-agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
  connection: [ 'close' ],
  accept: [ '*/*' ],
  host: 'stash.host.here:443' }
```

Http:
```
path: /rest/api/1.0/projects/PROJECT_1/repos/rep_1/pull-requests/25
headers: { authorization: 'Basic XXXXXXX',
  'content-type': 'application/json',
  host: 'stash.host.here' }
```

Is that intentional that header values are wrapped into arrays?
Or maybe there's something wrong with the opts object?

**Comment by bitinn** [comment]
In short: yes, using Fetch will change your header into arrays.

In full:

- The spec never define what data structure we should use to implement Fetch, so you should never rely on it being a `string` or an `array`. However, when making the actual request they will be the same byte sequence in the actual http request.
- If you are doing tests, you want to check the headers you send contains a certain name/value, not the raw headers, see above reasoning.
