### ISSUE TITLE
Absolute url isn't recognied as an absolute url

### ISSUE THREAD

**Issue by krainboltgreene** [bitinn/node-fetch#221]
```
 Requesting from API http://decoraid:3002/api/v0.1
 { url_parsed:
    Url {
      protocol: 'http:',
      slashes: null,
      auth: null,
      host: null,
      port: null,
      hostname: null,
      hash: null,
      search: null,
      query: null,
      pathname: '/decoraid:3002/api/v0.1/pending-designer-project-invitations',
      path: '/decoraid:3002/api/v0.1/pending-designer-project-invitations',
      href: 'http:/decoraid:3002/api/v0.1/pending-designer-project-invitations' } }
```

Any ideas on why url.parse would fail to recognize this kind of url?

**Comment by bitinn** [comment]
You should double check, URL parse shouldn't give you *http:/decoraid:3002/api/v0.1/pending-designer-project-invitations*

(From my phone)

> 在 2017年1月10日，10:29，Kurtis Rainbolt-Greene <notifications@github.com> 写道：
> 
> http:/decoraid:3002/api/v0.1/pending-designer-project-invitations

**Comment by krainboltgreene** [comment]
Yeah, it was something an upper level from node-fetch, sorry for wasting your time!
