### ISSUE TITLE
Body is not sent when using DELETE

### ISSUE THREAD

**Issue by vinceprofeta** [bitinn/node-fetch#223]
I have code using DELETE method and the body is not getting attached. When I use the same code with normal fetch, everything works fine.

**Comment by ahmadnassri** [comment]
@vinceprofeta can you provide any examples / steps to re-produce?

**Comment by vinceprofeta** [comment]
@ahmadnassri I am using node fetch to handle my server side rendering for a react app. When the client handles the request to DELETE, the body does not get sent up and I get a Bad Request error from the server. This same code using es6 fetch it works fine. I have a workaround where I use node fetch for the server rendering but when the client takes over I use es6 fetch
```
 await nodeFetch(url, {
      method,
      body: data ? JSON.stringify(data) : null,
      credentials: false,
      headers: {
        'Content-Type': 'application/json',
      }
  });
```

**Comment by TimothyGu** [comment]
Can't reproduce here on Node.js v7.6.0 (with native async functions)

```js
const nodeFetch = require('node-fetch');
const data = {
  key: 'data'
};
const url = 'https://httpbin.org/delete';
const method = 'DELETE';

(async () => {
  const res = await nodeFetch(url, {
    method,
    body: data ? JSON.stringify(data) : null,
    credentials: false,
    headers: {
      'Content-Type': 'application/json',
    }
  });
  const json = await res.json();
  console.log(json.json.key);
})();

// Correctly prints "data"
```

**Comment by vinceprofeta** [comment]
@TimothyGu I will try and upgrade to node 7 and let you know.

**Comment by yuchuan1** [comment]
I tried this with node v7.7.0 and the body was not attached.
`fetch(serverUrl + '/stuffToDelete/', { method: 'DELETE', body: payload, credentials: false, headers:"'Content-Type': 'application/json','Content-Length':" + payload.length})`

**Comment by bitinn** [comment]
A few things we would need to know:

- using node-fetch 1.x or 2.x alpha?
- as long as the data type is *supported*, `node-fetch` should always pass on the body for `DELETE`, so the question becomes, what data type is your payload/data. 
- it might be a good idea to use something like http://httpbin.org to verify this problem.

**Comment by yuchuan1** [comment]
node-fetch version: 1.6.3

```
var payload = [1, 2, 3];

fetch('http://httpbin.org/delete', { method: 'DELETE', body: JSON.stringify(payload), credentials: false, headers:"'Content-Type': 'application/json','Content-Length':" + videoIds.length})
.then((response) => {
  if (!response.ok) {
    console.error(response.statusText)
  }
  return response
})
.then((response) => {
  return response.json()
}).then(function(json) {
    console.log(json);
})
.catch((e) => dispatch(
  console.error(e)
));
```

tested on httpbin.org
this is what it returns
Object {args: Object, data: "", files: Object, form: Object, headers: Object…}

**Comment by bitinn** [comment]
@yuchuan1 I will try it later today, but first of all, I don't think you need to do `content-length` manually and if you do, you should use length of the JSON string, not the array.

**Comment by TimothyGu** [comment]
With both node-fetch v1 and v2, with the `headers` option changed to be an object, the code provided by @yuchuan1 works as expected.

**Comment by sylwekg** [comment]
I have the same issue, can you give brief example how the headers should be configured ? Thanks

**Comment by scott-cornwell** [comment]
This does not work on node 8.9.4 with node-fetch 2.1.2.

**Comment by pugnascotia** [comment]
Also observing this with node 10.16.0, node-fetch 2.6.0
