### ISSUE TITLE
Rethink spec compliance

### ISSUE THREAD

**Issue by TimothyGu** [bitinn/node-fetch#224]
In #181, I laid out the reasons for specific choices in spec compliance (or lack thereof). The most significant factor in my decisions was compatibility with existing implementations (github/fetch, Chrome, and Firefox).

However, github/fetch has recently adopted the new spec behavior in _their_ v2 release (see github/fetch#429); so has Firefox in v52 (see [release notes](https://developer.mozilla.org/en-US/Firefox/Releases/52#Service_Workers_and_Fetch)), which will ship in March 2017.

I think we should remove the global `FOLLOW_SPEC` option and make it the only behavior.

**Comment by bitinn** [comment]
Seem reasonable, v2.0 alpha is a good time to do that.

(From my phone)
