### ISSUE TITLE
Document (or remove) user-agent header

### ISSUE THREAD

**Issue by gajus** [bitinn/node-fetch#226]
It is not expected that the HTTP library is sending a user-agent header by default.

We only observed this when analysing the logs.

For others reference, `note-fetch` adds:

```
user-agent:       node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
```

header to all requests, unless overwritten.

This can be a major privacy, security concern.

**Comment by bitinn** [comment]
Check curl, and wget. Lots of sites prevent agent without UA from accessing. And this is not a security or privacy concern, this is good practice, you can always replace it with your custom name.

(From my phone)

**Comment by gajus** [comment]
Can we agree on that it should be documented?

**Comment by bitinn** [comment]
Yeah, we should, I will take a PR (busy at the moment, sorry)

**Comment by jimmywarting** [comment]
> Can we agree on that it should be documented?

I think so, not only how you can replace it but also how you can remove/disable it

**Comment by TimothyGu** [comment]
See https://fetch.spec.whatwg.org/#concept-http-network-or-cache-fetch step 12. A `User-Agent` header is basically mandatory according to the spec, so there isn't (nor shouldn't be) a way to remove it. I'm okay with a PR that helps document this though.

**Comment by ahmadnassri** [comment]
@bitinn made a PR with suggested change to README as well as added other default header values
