### ISSUE TITLE
What is changing in v2?

### ISSUE THREAD

**Issue by gajus** [bitinn/node-fetch#227]
I see that there is v2.0.0-alpha.1 tag.

Whats changing?

**Comment by TimothyGu** [comment]
Check https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md#2x-release (especially the "major" points). The [upgrade guide](https://github.com/bitinn/node-fetch/blob/master/UPGRADE-GUIDE.md) is helpful too, as it outlines the most important changes.

**Comment by gajus** [comment]
Thank you! Sorry, I have missed it.
