### ISSUE TITLE
Fetch fails with non-ascii Unicode (eg accented) characters in url 

### ISSUE THREAD

**Issue by chrisveness** [bitinn/node-fetch#233]
If a URL includes accented characters `node-fetch` returns 404 Not Found.

These work correctly using native `fetch` in Chrome Developer Tools.

Eg:

    fetch('http://www.movable-type.co.uk/test/test.txt').then(response => console.log(response.status))

returns 200 in both DevTools and node repl.

However,

    fetch('http://www.movable-type.co.uk/test/épreuve.txt').then(response => console.log(response.status))

returns 200 in DevTools, but 404 in node repl.

These example URLs can be used to replicate the issue.

**Comment by chrisveness** [comment]
![node](http://www.movable-type.co.uk/test/test-node.png)

![devtools](http://www.movable-type.co.uk/test/test-devtools.png)

**Comment by bitinn** [comment]
Accented character in url is not valid, browser automatically handles the encoding (for convenience I believe).

I don't think we should do the same in server environment.

**Comment by chrisveness** [comment]
Of course I should be encoding the URL - sorry about the brainstorm, end of a long day!

**Comment by TimothyGu** [comment]
@chrisveness, if you are using Node.js v7, you can use the built-in WHATWG URL parser for maximum compatibility with the browser's behavior; or if not, [whatwg-url](https://www.npmjs.com/package/whatwg-url) package would work as well.

```js
const { URL } = require('url');

fetch(new URL('http://www.movable-type.co.uk/test/épreuve.txt')).then(/* ... */);
```

**Comment by chrisveness** [comment]
@TimothGu, thanks for that steer – I wasn't aware of the URL API.

It looks really useful, and good to have the same API in both Node and browser. I'll never have to use `encodeURI` again!

**Comment by chrisveness** [comment]
The [MDN URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) entry seemed a little bare, so I've added a [_Usage_](https://developer.mozilla.org/en-US/docs/Web/API/URL#Usage) section. If there are any errors, let me know and I will correct.
