### ISSUE TITLE
exception when parsre response body content to JSON object. 

### ISSUE THREAD

**Issue by jackey** [bitinn/node-fetch#234]
i think it's better if add exception handle [here](https://github.com/bitinn/node-fetch/blob/master/src/body.js#L88) .

**Comment by TimothyGu** [comment]
What do you mean?

**Comment by jackey** [comment]
@TimothyGu 
like this:
try { return JSON.parse(buffer.toString()) }  
```
json() {
  return this[CONSUME_BODY]().then(buffer => {
    // handle exception can make server more stable 
    try {
      return JSON.parse(buffer.toString());
    }
    catch(e) {
      // handle exception
    }
  });
}
```

**Comment by bitinn** [comment]
We don't do exception handling because it's defined by Spec. And it's far more likely developers want to handle this problem themselves (find a workaround for broken API).
