### ISSUE TITLE
charset 'gb2312' force to gb18030

### ISSUE THREAD

**Issue by coyool** [bitinn/node-fetch#242]
body.js line 214
      
               many webs user gb2312 correctly, so please give a warning or something to exclude the following 

               // prevent decode issues when sites use incorrect encoding
		// ref: https://hsivonen.fi/encoding-menu/
		if (charset === 'gb2312' || charset === 'gbk') {
			charset = 'gb18030';
		}

**Comment by TimothyGu** [comment]
Can you provide an example URL for when this doesn't work?

**Comment by TimothyGu** [comment]
Specifically, according to https://www.zhihu.com/question/19677619

> GB 18030 与 GB 2312-1980 和 GBK 兼容

**Comment by coyool** [comment]
这是个例子.估计是这个系统比较奇葩?

**Comment by bitinn** [comment]
Fetch API always output in UTF-8.

Fetch Spec doesn't really support encoding beyond UTF-8. So if you are specifically dealing with non UTF-8 encoding, decode res.body yourself is safer.

Also note that, in 2.x we have changed text() to only decode UTF-8.

(From my phone)

**Comment by TimothyGu** [comment]
Timed out.
