### ISSUE TITLE
Drop node 4.x and have native ES2015 for 2.x?

### ISSUE THREAD

**Issue by tinovyatkin** [bitinn/node-fetch#243]
`node-fetch 2.x` now have just two dependencies left - `encoding` and :tada: `babel-runtime`. And second one looks pretty weird for any 2017 node module. Why not to drop `4.x` and use ES2015 natively? From the most optimistic news from node team, ES6 modules `import/export` support is not coming at least in a year, and even node 6 supports `ES2015` almost completely, so we can have next major version written in native ES2015 code without any transpiling side effects... 
So, what's the thing to support `node 4.x` while doing major update?

**Comment by TimothyGu** [comment]
babel-runtime dropped. It became unnecessary when I skipped several Babel transforms without which Node.js v4 would still work, but not be 100% compliant. We don't need that level of compliance anyway.
