### ISSUE TITLE
URL is not encoded as UTF-8

### ISSUE THREAD

**Issue by kumar303** [bitinn/node-fetch#245]
I think `node-fetch` is not encoding non-ascii URLs (which are JavaScript `strings`) as UTF-8, such as: `https://some-server.net/api/thing/diccionario-español/`. Making a GET request with `fetch()` in Firefox/Chrome works as expected but making a GET request on a NodeJS (6.9.4) server with `node-fetch` does not encode the URL properly. I haven't investigated what the exact discrepancy between the two is but when I added [utf8.encode(url)](https://www.npmjs.com/package/utf8) to my NodeJS code, it worked.

**Comment by TimothyGu** [comment]
Now that we have dropped support for Node.js 0.1x, we can use whatwg-url (or Node.js v7's `require('url').URL` now which more closely follows browser's behavior.

**Comment by kumar303** [comment]
I was slightly confused to learn that the browser's `fetch()` will always attempt to encode the URL path, even if it's already encoded. I guess that's either a bug or maybe it's not possible to distinguish byte strings from Unicode "strings" in Javascript so easily.

In other words, this workaround doesn't work in the browser:

```js
import 'isomorphic-fetch';
import utf8 from 'utf8';

fetch(utf8.encode('http://site/my-possibly-non-ascii-path'));
```

The workaround has to look like this:

```js
const url = 'http://site/my-possibly-non-ascii-path';
if (codeIsRunningInNodeJs) {
  fetch(utf8.encode(url));
} else {
  fetch(url);
}
```

In case it's useful to anyone else, here is a simple `server.py` script I was using to figure it out:

```python
import urllib
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer

class RequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        path = urllib.unquote(self.path)
        print u'** path (Byte string): {}'.format(repr(path))
        print u'** path (UTF8 decoded): {}'.format(path.decode('utf8', 'replace'))
        self.send_response(200)
        self.send_header('Content-type', 'text')
        self.end_headers()
        self.wfile.write("Response from server.py")

httpd = HTTPServer(('', 9001), RequestHandler)
print 'Starting server at http://localhost:9001 ...'
httpd.serve_forever()
```

The confusing part was that my server was able to figure out the double encoding and cope with it but only for simple Unicode characters, not double wide characters.

**Comment by iggyfisk** [comment]
I'm working around this issue right now in a Next.js project for the Scandinavian market. Lots of ÅÄÖ, node and browser treat them differently.

**Comment by TimothyGu** [comment]
@iggyfisk If you pass a URL object (through either the builtin `require('url').URL` or whatwg-url module) into node-fetch, you would no longer have this problem.

**Comment by bitinn** [comment]
@TimothyGu Is there anything we need to do on our end? Do we need to support non-ascii url string  in the core somehow?

Basically, should users use the recommended native modules or should we provide this by default? Seems like this can be easily solved if we just put a code snippet here or in the readme?

**Comment by TimothyGu** [comment]
I'm targeting this issue for node-fetch v3.x. We plan on dropping Node.js v4.x support in the next major version, and the WHATWG URL parser is in the latest versions of all release branches >= v6.x.

**Comment by Richienb** [comment]
Fixed in https://github.com/bitinn/node-fetch/commit/f3b00aaf8ed847fd3f30b1b7182cdafa411d02f0.
