### ISSUE TITLE
Host header includes port when making 80 request

### ISSUE THREAD

**Issue by gajus** [bitinn/node-fetch#246]
Some servers will fail if the request Host header includes the port number when making a request on port `:80`. Now `node-fetch` (or rather the underlying Node.js module) includes Host header that includes the port.

I have fixed this using a wrapper.

https://github.com/gajus/xfetch/commit/3e8a7979df37e8a8b94e080e2145619aa90c6d03

**Comment by TimothyGu** [comment]
I don't see this happening:

```js
> fetch('https://httpbin.org/headers').then(r => r.json()).then(j => console.log(j.headers.Host))
Promise { <pending> }
> httpbin.org
```

Can you give a more specific method for reproduction?

**Comment by gajus** [comment]
You will need to intercept the request, e.g. using mitmproxy.

<img width="1920" alt="screen shot 2017-02-27 at 17 33 49" src="https://cloud.githubusercontent.com/assets/973543/23372292/e967203c-fd12-11e6-9d28-852a8752c277.png">

**Comment by gajus** [comment]
Right. Now I understand why I felt deja vu while working on this.

I have already raised an issue about this in the past with `https-proxy-agent`.

https://github.com/TooTallNate/node-https-proxy-agent/issues/22

Sorry, not related to `node-fetch`.
