### ISSUE TITLE
Add support for TypedArray, DataView, and ArrayBuffer as body

### ISSUE THREAD

**Issue by TimothyGu** [bitinn/node-fetch#247]
The Fetch Standard [allows](https://fetch.spec.whatwg.org/#bodyinit) `BufferSource` as a `BodyInit`, which is [defined](https://heycam.github.io/webidl/#BufferSource) to include all TypedArray types, DataView, and ArrayBuffer.

**Comment by gr2m** [comment]
I _think_ I run into a problem because of the lack of `ArrayBuffer` support, with a test that runs in the browser but fails in Node.

Can I work on this? Could you give me pointers on where to start?

**Comment by TimothyGu** [comment]
@gr2m Seems like you figured it out :)

For any other people interested in this, one could do the same thing in #408, but for the remaining BufferSource types (TypedArray and DataView).
