### ISSUE TITLE
Bulletproof way to download files

### ISSUE THREAD

**Issue by daviestar** [bitinn/node-fetch#249]
Hello, I've been reading about the best way to download files using `node-fetch`.  I have to download a large number of files and have been running into issues with silent failures.  I'm a bit of a n00b when it comes to streams.. would this be a recommended way to handle download streams?  Is there a more bulletproof/elegant solution?

```js
fetch(url, {timeout: RESPONSE_TIMEOUT})
  .then((res) => res.ok ? res
    : Promise.reject({reason: 'Initial error downloading file', meta: {url, error: res.error}})
  )
  .then((res) => new Promise((res, rej) => {
    const stream = fs.createWriteStream(destPath)
    let timer
    res.body.pipe(stream)
      .on('open', () => {
        timer = setTimeout(() => {
          stream.close()
          rej({reason: 'Timed out downloading file', meta: {url}})
        }, FILE_DOWNLOAD_TIMEOUT)
      })
      .on('error', (error) => {
        clearTimeout(timer)
        rej({reason: 'Unable to download file', meta: {url, error}})
      })
      .on('finish', () => {
        clearTimeout(timer)
        res(destPath)
      })
  }))
```

**Comment by jimmywarting** [comment]
lgtm. One thing maybe would be to check the response status?

```js
  .then((res) => new Promise((res, rej) => {
    if (!res.ok) {
      // exit early
    }
    const stream = fs.createWriteStream(destPath)
```

**Comment by daviestar** [comment]
Thanks @jimmywarting, re. `!res.ok` I over-simplified my example code.. I handle the initial response elsewhere, I've updated the code sample above.

Re. extracting the filename - I do that for some endpoints when I have to, for example  a call to url `domain.com/hash3483240934` and the response is a forced download of `domain.com/some-doc-name.pdf`.  That's a nice suggestion to do this by default when downloading files - at least for error reporting.

Setting up a timer inside the stream feels a bit like re-inventing the wheel..

**Comment by jimmywarting** [comment]
res.ok is only true when status code is 200-299 (false otherwise)

**Comment by daviestar** [comment]
👍  updated

**Comment by TimothyGu** [comment]
@daviestar 

1. Your `res` variable is shadowed (it means both "response" and "resolve"). You have to use another variable name for one of them.
2. `res.body`'s `'error'` event is not automatically propagated to the file write stream. You have to handle it individually. 
3. The `timeout` option is only effective if you use one of the `res.*()` convenience methods.
4. `res.error` does not exist. You might be looking for `new Error(res.statusText)`.

Less important changes:

1. Moved error handling into a unified function.
2. Moved `clearTimeout` to after the inner promise to make 100% sure it is actually followed.
3. Removed an unneeded promise for `res.ok` check

```js
fetch(url)
  .then((res) => res.ok ? res
    : Promise.reject({reason: 'Initial error downloading file', meta: {url, error: res.error}})
  )
  .then((res) => {
    if (!res.ok) {
      return Promise.reject({
        reason: 'Initial error downloading file',
        meta: {url, error: new Error(res.statusText)}
      })
    }

    const stream = fs.createWriteStream(destPath)
    let timer

    return new Promise((resolve, reject) => {
      const errorHandler = (error) => {
        reject({reason: 'Unable to download file', meta: {url, error}})
      };

      res.body
        .on('error', errorHandler)
        .pipe(stream)

      stream
        .on('open', () => {
          timer = setTimeout(() => {
            stream.close()
            reject({reason: 'Timed out downloading file', meta: {url}})
          }, FILE_DOWNLOAD_TIMEOUT)
        })
        .on('error', errorHandler)
        .on('finish', () => {
          resolve(destPath)
        })
    }).then((destPath) => {
      clearTimeout(timer)
      return destPath
    }, (err) => {
      clearTimeout(timer)
      return Promise.reject(err)
    })
  })
```

I'll close this issue, but feel free to continue commenting.

**Comment by daviestar** [comment]
@TimothyGu thanks for the clarification on this.. most of the issues came from me hastily copy/pasting chunks from a more modular codebase, apologies.

Since streams are the preferred method for downloading files in Node, do you think this is a good use case for a stream wrapper built into `node-fetch` with configurable timeout, which defaults to a sensible setting?

Since Fetch has a promise-based API, and streams are managed via events, as above this leads to creating new Promises within Promises to accomplish safely downloading files.. perhaps `node-fetch` could make this simpler for the end user?

**Comment by daviestar** [comment]
Perhaps an API like this:
```js
fetch(url)
  .then((res) => res.ok ? res
    : Promise.reject({reason: 'Initial error downloading file', meta: {url, error: res.error}})
  )
  .then((res) => res.body.writeStream(destPath, {timeout: 10 * 1000}))
```

**Comment by bitinn** [comment]
@daviestar It's quite likely we want to stay with Fetch Spec.

Also I am not sure why you can't use `pipe`? `res.body` is a normal Node Stream.

**Comment by daviestar** [comment]
Hello @bitinn, just had a look through the spec there, and AFAICS there's nothing about writing files to disk, which is specific to `node-fetch`.  I'm suggesting a simple convenience method (in my example, a method on `res.body`named `writeStream`) which accomplishes roughly:

```js
function writeStream(destPath, opts) {
  const stream = fs.createWriteStream(destPath)
  let timer
  
  return new Promise((resolve, reject) => {
    const errorHandler = (error) => {
      reject({reason: 'Unable to download file', meta: {url, error}})
    };

    this
      .on('error', errorHandler)
      .pipe(stream)

    stream
      .on('open', () => {
        timer = setTimeout(() => {
          stream.close()
          reject({reason: 'Timed out downloading file', meta: {url}})
        }, opts.timeout || 10 * 1000)
      })
      .on('error', errorHandler)
      .on('finish', () => {
        resolve(destPath)
      })
  }).then((destPath) => {
    clearTimeout(timer)
    return destPath
  }, (err) => {
    clearTimeout(timer)
    return Promise.reject(err)
  })
}
```
which would a) make the download mechanism promise-based, while still having the advantages of a stream under-the-hood, and b) reject on a timeout instead of failing silently.

I believe without these types of conveniences, end users are likely to start using wrapper modules around fetch which provide them, which kind of defeats the purpose of fetch.. IMHO.

**Comment by bitinn** [comment]
> I believe without these types of conveniences, end users are likely to start using wrapper modules around fetch which provide them.

This is what Fetch is designed to be, a low level HTTP API, not a high-level API.

But we do have response timeout built-in, take a closer look at readme. https://github.com/bitinn/node-fetch#options

**Comment by daviestar** [comment]
@bitinn Thanks, yes I use it in my original example at the top, but what lead me to create this issue was silent failures when downloading large files.

Ok, I thought fetch was designed to be a simple API, soon baked into every JS environment, which meant no more 'ajax libs'.  Even if it's not designed that way, that's how I'm using it.  

Maybe what the world needs is a `timeoutable-stream-promise` module to accomplish this task :)  Thanks for the discussion.

**Comment by Bonjur** [comment]
> @bitinn Thanks, yes I use it in my original example at the top, but what lead me to create this issue was silent failures when downloading large files.
> 
> Ok, I thought fetch was designed to be a simple API, soon baked into every JS environment, which meant no more 'ajax libs'. Even if it's not designed that way, that's how I'm using it.
> 
> Maybe what the world needs is a `timeoutable-stream-promise` module to accomplish this task :) Thanks for the discussion.

You ever finished your code with resume support? I am also n00b with streams right now
