### ISSUE TITLE
Abstract Headers class into a separate NPM module whatwg-headers

### ISSUE THREAD

**Issue by gajus** [bitinn/node-fetch#250]
This would reduce duplication of the code between projects who are implementing parts of the spec or extending `node-fetch`, like https://github.com/gajus/xfetch.

**Comment by jimmywarting** [comment]
I tried to make them do it some time ago.
But they didn't want to. anyway, here is my attempt: [fetch-headers](https://www.npmjs.com/package/fetch-headers)

**Comment by TimothyGu** [comment]
I prefer not to deal with the complexity of having an additional dependency. Concurrent changes in Headers and rest of node-fetch would be greatly complicated if it is an additional dependency. And it would be overkill to use something like [lerna](https://www.npmjs.com/package/lerna) for a two-package repo.

> Think mine is a bit more modern since mine uses generator function

That would go against the [Web IDL spec](https://heycam.github.io/webidl/#es-default-iterator-object) which as it currently stands I would like to continue to adhere to.

**Comment by gajus** [comment]
> Concurrent changes in Headers and rest of node-fetch would be greatly complicated if it is an additional dependency

How so?

If anything, it would only enable greater transparency about changes.

**Comment by bitinn** [comment]
Until Fetch Spec stabilise we really have no plan to make this more complicated. I think node-fetch is *lightweight enough* for most use-cases.

And I plan to drop `encoding` as well in order to keep `node-fetch` more lightweight. see #273
