### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by ekkis** [bitinn/node-fetch#255]
at the console I can type:

`curl -H "Basic bmVvNGo6bmVvNGo=" http://AppStore:7474/neo4j/user`

and get back:

```
{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.Unauthorized",
    "message" : "No authentication header supplied."
  } ]
}
```

from node I can do it too:

`# node -e 'var http=require("http"); http.get({host: "AppStore", port: 7474, path: "/neo4j/user", headers: {Authorization: "Basic bmVvNGo6bmVvNGo="}}, res => { console.log(res); })'
`

but using node-fetch:

`node -e 'f=require("node-fetch"); f("http://AppStore:7474/neo4j/user", {Authorization: "Basic bmVvNGo6bmVvNGo="}).then(res => { console.log(res); }).catch(e => { console.log(e); })'
`

 I crash:

```
{ Error
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1034:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://AppStore:7474/neo4j/user failed, reason: getaddrinfo ENOTFOUND appstore appstore:7474',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
```

am I formulating the request incorrectly? or is there a problem with the module?  ENOTFOUND indicates a DNS resolution issue.  it can't find the host.  but the DNS server used should be the same no?

**Comment by ekkis** [comment]
incidentally, this works fine in OSX but it's failing in Ubuntu 16.04 LTS with node v7.7.3

**Comment by bitinn** [comment]
There isn't much we can do as ENOTFOUND is from upstream (nodejs core).

From what I see, it's not a crash, it's just a normal error output `catch` by your code. Promise catch isn't handling a crash, but a rejection.

**Comment by ekkis** [comment]
yes but it is happening within your code only.  as I have pointed out, the `http` library doesn't suffer from the same problem

**Comment by bitinn** [comment]
You want to try `http.request`, which our code wraps around.

Also think along this line: our code doesn't differentiate platforms, if it only fails on Ubuntu, that's likely upstream issue as well.

**Comment by ekkis** [comment]
yes, I've removed my dependence on this module and implemented the functionality with the standard `http` already.  my point is merely that it's not Node's problem, nor is it an environmental issue.  if `http.get()` works and your module doesn't, it has an issue

**Comment by bitinn** [comment]
To put it more clearly, you haven't tried *parsing url*, which we do.

**Comment by ekkis** [comment]
yes, in my case I cannot use the string signature of `http.get()` because I need to pass headers, so there's no call to `url.parse()`.  that, however, is an implementation detail of your module

**Comment by ekkis** [comment]
I've confirmed your suspicion that the problem lies with parsing the url.  specifically, the *hostname* comes back in lowercase and queries to such fail with the aforementioned error (using `http.request`).  this seems to me anomalous behaviors as DNS lookups are case-insensitive.  so I think it's something that I should report... but I'm not sure to whom

**Comment by ekkis** [comment]
and, actually, now that I think about it a bit more, this is more likely a problem with Docker (I'm doing this work inside containers) since the name resolution is done by their own DNS mechanism (which defines names for docker containers).  they've broken the agreement because their name lookups seem to be case-sensitive and Node and the underlying layers know nothing of this

**Comment by ekkis** [comment]
all right.  for the sake of any other poor sods that find their way to my conundrum, I've posted the issue here: https://forums.docker.com/t/dns-breaks-contract/30302

thanks for all your help

**Comment by Strandedpirate** [comment]
I'm having the same error and running in docker containers under kubernetes too. I'll post any findings I have in my investigation.

**Comment by Jiia** [comment]
For the record, I had this same issue and it was caused by creating too many simultaneous fetch requests in a loop, 4200 of them. I ended up queuing the requests. The error ENOTFOUND was really misleading in my case.

**Comment by srussell123** [comment]
I may be looking at the same issue as you @Jiia, iterating over a list of several hundred items and making requests for each; have you had any luck finding a sort of limit for this?

**Comment by jgdodson** [comment]
> For the record, I had this same issue and it was caused by creating too many simultaneous fetch requests in a loop, 4200 of them. I ended up queuing the requests. The error ENOTFOUND was really misleading in my case.

Yes, this is my case. I get the ENOTFOUND error only when making a high volume of concurrent requests. I'm using the queue object from [coalan/async](https://github.com/caolan/async) with a concurrency level of 10.

Does anyone have any insight as to the origin of this behavior?

**Comment by francis-li** [comment]
I was also seeing inconsistent behavior when making node-fetch GET requests in a Docker container. These requests (~30) were fired off in parallel using `async.parallel`. The requests appeared to randomly fail every so often with ENOTFOUND (see end of post for actual error and stack trace). The requests worked consistently via cURL on the same host machine.

Host machine: Ubuntu 16.04 / Docker image: node:10.19.0-alpine3.10

Interestingly, I was not able to reproduce the issue when running the Docker container on Mac OS (my local machine).

**What worked for me**: Switching to sequential requests solved the issue I was seeing on the host machine (thanks to @Jiia's comment about concurrency). 

Original error:
```
"err": {
  "type": "FetchError",
  "message":"request to <url> failed, reason: getaddrinfo ENOTFOUND <host> <host>:<port>",
  "stack":"FetchError: request to <url> failed, reason: getaddrinfo ENOTFOUND <host> <host>:<port>\n    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1455:11)\n    at ClientRequest.emit (events.js:198:13)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at Socket.emit (events.js:198:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)",
  "errno":"ENOTFOUND",
  "code":"ENOTFOUND",
  "name":"FetchError"
}
```
