### ISSUE TITLE
node LTS support, dropping babel-runtime

### ISSUE THREAD

**Issue by zkat** [bitinn/node-fetch#258]
Hey! I noticed over at #243 there was some discussion related to node@4. My own use-case (in npm itself) means that in order to use this project, I'd need it to support that version.

Additionally, because this is a CLI app, I try to avoid very large dependencies. Dropping babel-runtime altogether (and, by extension, core-js) would be really nice to that end. :)

I'm perfectly fine contributing a PR to do this, since it's a pretty important bit for me, but I wanted to check in with y'all that the sort of changes needed to do this would be acceptable.

**Comment by TimothyGu** [comment]
Node v4 is still supported and will remain supported until its EOL. babel-runtime was dropped in eb1959ed0945ba184a3b0baab20998dcbfc57f6c :smile_cat:

**Comment by TimothyGu** [comment]
(The changes will be released in v2.0.0 stable. There's a tracking bug for that: #228)

**Comment by zkat** [comment]
Oh! Sorry for the misunderstanding! Thanks for the quick answer, and thanks for the great work so far ^_^ it's been pretty nice using this thing, even with v2 in alpha.
