### ISSUE TITLE
expose response stream directly

### ISSUE THREAD

**Issue by GusCaplan** [bitinn/node-fetch#259]
I was wondering if there was a way i could grab the raw response stream before the promise resolves to handle streaming things like large files etc.

I would be happy to add it if there is no way, but i assume you guys want to stick to fetch spec in some ways, so this could be discussed.

-gus

**Comment by TimothyGu** [comment]
```js
fetch(url).then(res => {
  res.body; // This is a readable stream.
  // res.body.pipe(...)
});
```

**Comment by GusCaplan** [comment]
won't that not allow me to access the stream until the entire request has completed?

**Comment by bitinn** [comment]
But sure which part you are referring to, but:

- before sending request you can access req.body,
- after sending request and *starts* to receive response, you can access res.body

Note my emphasis on *start*, you will have the complete headers, but you can process the response body as stream.

If you just want the streams, as in you don't care about headers, but thinking in term of payloads, I am not sure HTTP level lib is what you are looking for.
