### ISSUE TITLE
FetchError: invalid response body (Gunzip)

### ISSUE THREAD

**Issue by GottZ** [bitinn/node-fetch#261]
the below code will try to request gzip compressed chunked binary data.  
when using curl on that url it will succeed.

```
fetch('http://pxls.space/boarddata').then(res => {
  return res.buffer();
}).then(buffer => {
  // add a debugger statement here or similar
  console.log(buffer.length);
}).catch(e => {
  console.log(e);
});
```
try to run this on node 6.10.2 aswell as with node-fetch 1.6.3

the outcome will be similar to this:
```
{ FetchError: invalid response body at: http://pxls.space/boarddata reason: incorrect data check
    at Gunzip.<anonymous> (/somewhereonmysystem/node_modules/node-fetch/lib/body.js:122:11)
    at emitOne (events.js:101:20)
    at Gunzip.emit (events.js:188:7)
    at Zlib.__dirname.Zlib.mode._handle.onerror (zlib.js:373:10)
  name: 'FetchError',
  message: 'invalid response body at: http://pxls.space/boarddata reason: incorrect data check',
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR' }
```

this will work:
```
fetch('http://pxls.space/boardinfo').then(res => {
    return res.json();
}).then(data => console.log(data));
```

any idea what might be causing this? should i switch to a different node version?
i'm on MacOS at the moment. i'm using a correctly installed instance of nvm.

**Comment by tgandrews** [comment]
I get this on Mac. Node `6.10.2`. But it isn't consistent. 

I added some logging to `node-fetch/lib/body.js:145` and saw that it was output twice when it failed. So it looks as if the stream is ending twice.

**Comment by bitinn** [comment]
Sorry for the late reply. I want to say this is a bug on remote server (or a Node.js core change). `.buffer()`, `.json()` and `.text()` should be doing that same decompression, see:

- https://github.com/bitinn/node-fetch/blob/v1.6.3/index.js#L206-L229
- https://github.com/bitinn/node-fetch/blob/v1.6.3/lib/body.js#L120-L123
