### ISSUE TITLE
browser field in package.json

### ISSUE THREAD

**Issue by m59peacemaker** [bitinn/node-fetch#262]
Since this module is exclusive to the server, what do you think about having it use the browser field in package.json to export `window.fetch` when bundled in the browser?

package.json
```json
"browser": "./browser.js"
```

browser.js
```js
module.exports = window.fetch
```

This just makes it convenient to use for either context (assuming fetch is supported in the targeted browser).

**Comment by TimothyGu** [comment]
You may be looking for [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) module

**Comment by m59peacemaker** [comment]
`fetch` is already implemented in most browsers. I use polyfill.io for others, so there's no need to bundle poly/ponyfills. Projects that want to use native fetch in the browser and `node-fetch` on the server have to use the browser field to ignore node-fetch. It makes sense to me for node-fetch to do that automatically so that it's never bundled for the browser by default.

**Comment by m59peacemaker** [comment]
[form-data has this behavior.](https://github.com/form-data/form-data/blob/master/package.json#L11)

**Comment by bitinn** [comment]
Released as v2 alpha.4, better late than never...
