### ISSUE TITLE
slightly invalid gzip decompression fails on node 5

### ISSUE THREAD

**Issue by m59peacemaker** [bitinn/node-fetch#266]
This test works on node 4, 6, 7, but fails on 5.

https://github.com/bitinn/node-fetch/blob/master/test/test.js#L516-L525

> Z_BUF_ERROR unexpected end of file

**Comment by TimothyGu** [comment]
Node.js v5.x EOL has already passed 10 months ago. You should consider using other releases supported both by Node.js and us.

**Comment by m59peacemaker** [comment]
I'm not using it. I just wanted to let you know since your package.json says `>=4`. Updating that to 6 is perfectly reasonable to me.

**Comment by TimothyGu** [comment]
Hmm, thanks for the reminder. I'll adjust the `engine` accordingly.
