### ISSUE TITLE
Support for passing body as object instead of string?

### ISSUE THREAD

**Issue by anildigital** [bitinn/node-fetch#282]
so instead of 

```
var body = 'hello=world';
```

I need to pass body as 

```
body = {'hello': 'world'}
```

Does this library support that? Thanks.

**Comment by bitinn** [comment]
Nope, Fetch Spec doesn't support object, and we don't intend to cover it.

See v2 code: https://github.com/bitinn/node-fetch/blob/master/src/body.js#L373

But there are tons of solutions to simplify your job:

See example usage in readme: https://github.com/bitinn/node-fetch#usage
