### ISSUE TITLE
wrong url sending in Meteor

### ISSUE THREAD

**Issue by leizard** [bitinn/node-fetch#283]
Hi, I'm using node-fetch in my Meteor project. When I use `fetch('https://github.com/')`, somehow it adding my localhost port into the url so the url becomes `https://github.com:3000` and make the request fail.
Don't know what happened. Could anyone help me on this ?
Thank you

**Comment by bitinn** [comment]
It's not related to `node-fetch`, we never add port number automagically.

**Comment by leizard** [comment]
Could you please create a simple Meteor app then install `node-fetch` and fetch a url. I tried other fetch packages but it only happens with `node-fetch` :(
