### ISSUE TITLE
commit policy for package-lock.json (or yarn.lock etc.)

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#288]
It's pretty annoying neither `npm` nor `yarn` documentation mention these locks are for *applications*, and much less so for *libraries*; they mostly just say: *you shouldn't need to care, just commit them*.

 I am adding them onto `gitignore` for now. If people feel strongly against this, let me know.

**Comment by thasmo** [comment]
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by bitinn** [comment]
@thasmo I feel all of these have been argued before on other platforms, I still don't think they are strong cases for adding lockfiles. Other than *now both package manager does it by default*.
