### ISSUE TITLE
Wrap JSON.parse() SyntaxError with FetchError

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#293]
Just as a reminder.

I did this in [1.7.0](https://github.com/bitinn/node-fetch/blob/1.x/lib/body.js#L45-L49) release when backporting the *204 no-content* commit from 2.x (which revert behaviour of `.json()` to throw when facing an empty response).

Per our standard, this error is wrapped as FetchError, providing the offending url for troubleshooting.

**Comment by leonaves** [comment]
Why was this done? This breaks compatibility with the browser implementations of fetch which throw a SyntaxError.

**Comment by TimothyGu** [comment]
@leonaves Hmm, agreed. Filed an issue at #498.
