### ISSUE TITLE
String Object Required for JSON

### ISSUE THREAD

**Issue by reesmanp** [bitinn/node-fetch#301]
I have noticed that when sending JSON data from my server via this package to another Node server, everything works just fine:
`fetch('http://test.com', { method: 'POST', body: JSON.stringify({ a: 'b' }));`

However when sending to a Java backed server, it fails. What is printed out on the other end is:
`'"{\"a\":\"b\"}"'`
So somewhere (I think inside this package) single quotes are being appended which makes the Java parse fail. However if I turn the body into a string object:
`fetch('http://test.com', { method: 'POST', body: String(JSON.stringify({ a: 'b' })));`
It works like a charm. This is not documented and either should be or a fix to allow primitive strings.

Better JSON post documentation would be nice too.

**Comment by jimmywarting** [comment]
you have an unexpected ' before `body`...

**Comment by reesmanp** [comment]
Sorry, that was freehand coding. Still a problem, I'll fix the code above.

**Comment by bitinn** [comment]
Nope we don't append anything to your body, we have no knowledge of its content really, only the type of input (`string`, `stream`, etc.)

`JSON.stringify` returns an actual string, if you have problem with it, you should check the actual body string you are sending.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
