### ISSUE TITLE
Node Fetch in Electron

### ISSUE THREAD

**Issue by paul321** [bitinn/node-fetch#306]
Hi,

Is there any way to specify how node fetch should work in Electron, we need to switch between XMLHttpRequest and Node?

Thanks

**Comment by bitinn** [comment]
I really think this should be a question for Electron crowd.

If you have something more concrete to ask, let us know. (StackOverflow might serve you better if it's an integration issue.)

**Comment by paul321** [comment]
It was a question related to node-fetch if there is an option to call fetch with xhr or node

**Comment by m4heshd** [comment]
Wow, It's amazing how fast this was ignored. Currently in hell because of this issue. `gaxios` uses `node-fetch` and it forcefully uses the `fetch` API inside renderer process which then messes up streams. Can't use Node streams because of this.
