### ISSUE TITLE
Can not import default member in 2.0.0-alpha.5

### ISSUE THREAD

**Issue by jkeylu** [bitinn/node-fetch#307]
```
import fetch from 'node-fetch';
console.log(typeof fetch); // 'undefined'
```

**Comment by bitinn** [comment]
If `const fetch = require('node-fetch');` works, investigate your transpiler setup first.

**Comment by jkantr** [comment]
Honestly, as the loader syntax is still very much up in the air (and all npm modules should still be distributing CommonJS style exports into the foreseeable future) I highly suggest just using `require` and avoiding the headache. You also get the bonus of being able to destructure on the same line you require.

**Comment by TimothyGu** [comment]
Just checked: node-fetch@2.0.0-alpha.5/lib/index.es.js has

```js
export { Headers, Request, Response, FetchError };export default fetch;
```

so `import fetch from 'node-fetch'` would definitely work with Rollup and [rollup-plugin-node-resolve](https://www.npmjs.com/package/rollup-plugin-node-resolve) with `module` option turned on.

lib/index.js has

```js
module.exports = exports = fetch;
exports.Headers = Headers;
exports.Request = Request;
exports.Response = Response;
exports.FetchError = FetchError;
```

so Babel would work as well.

**Comment by jkeylu** [comment]
@bitinn @TimothyGu 
I'm using Typescript to compile my code.
```typescript
import fetch from 'node-fetch';
```

will compile to

```javascript
var fetch = require('node-fetch').default;
```

but in `lib/index.js` does not export default

**Comment by TimothyGu** [comment]
Argh, another module system. Reopening...

**Comment by TimothyGu** [comment]
For now, you should be able to use

```ts
import fetch = require('node-fetch');
```

as documented at https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

**Comment by bitinn** [comment]
Does Typescript definition file handle this type of things? If so might need to contact its author to support node-fetch 2.0

(From my phone)

**Comment by TimothyGu** [comment]
> Does Typescript definition file handle this type of things?

I don't think so. Just specifying `fetch.default = fetch` should be enough to fix this issue, though I'd prefer handling it in the compiler plugins ([Babel](https://github.com/bitinn/node-fetch/blob/master/build/babel-plugin.js), [Rollup](https://github.com/bitinn/node-fetch/blob/master/build/rollup-plugin.js)).
