### ISSUE TITLE
Node 8+ seems to spawn slower (tests related)

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#314]
I observed this while working on a new release: basically test cases that use `spawn` now often don't finish within 1000ms. Result in Travis CI build failure.

I am not able to reproduce this in earlier version of Node.

For a quick workaround, I think just increasing the timeout for following tests a bit should do:

<img width="808" alt="screen shot 2017-07-22 at 20 49 07" src="https://user-images.githubusercontent.com/1484279/28491190-3890020e-6f1f-11e7-9ddb-8d77aee3129f.png">

Need to look further on whether we can avoid `spawn` altogether.

<img width="916" alt="screen shot 2017-07-22 at 20 51 52" src="https://user-images.githubusercontent.com/1484279/28491213-aafcc1e2-6f1f-11e7-8237-bb783fdae133.png">

**Comment by TimothyGu** [comment]
Might be related to the recent Node.js security releases that disabled startup snapshots: https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

Increasing the timeout seems to be the only thing we can do until snapshots are re-enabled.

**Comment by bitinn** [comment]
Make sense, a quick comparison:

v4

<img width="535" alt="screen shot 2017-07-22 at 21 21 02" src="https://user-images.githubusercontent.com/1484279/28491424-d0f0ba94-6f23-11e7-85c5-194e1ac7a405.png">

v6

<img width="572" alt="screen shot 2017-07-22 at 21 21 36" src="https://user-images.githubusercontent.com/1484279/28491426-d54b1a8a-6f23-11e7-8756-8bc5a71be090.png">

v8

<img width="560" alt="screen shot 2017-07-22 at 21 21 14" src="https://user-images.githubusercontent.com/1484279/28491428-db0df884-6f23-11e7-88a3-cceb27c10c1a.png">

(My next PR should resolve this)
