### ISSUE TITLE
`node-fetch@2.0.0-alpha.6` throws error "Cannot find module 'encoding'"

### ISSUE THREAD

**Issue by TooTallNate** [bitinn/node-fetch#316]
```
$ npm ls
t@1.0.0 /Users/nrajlich/t
└── node-fetch@2.0.0-alpha.6

$ node -e "require('node-fetch')"
module.js:487
    throw err;
    ^

Error: Cannot find module 'encoding'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nrajlich/t/node_modules/node-fetch/lib/index.js:13:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

alpha.5 works as expected.

**Comment by bitinn** [comment]
You need to manually install `encoding`, that's all. We decouple it from dependency list, as only `body.textConverted()` use it, and it's a non-spec extension for back-compat with v1 `text()`.

Also sorry for the trouble, v2 alpha is in flux at the moment (eg. breaking changes might still come), I am thinking about safer ways to release v2 alpha, so suggestions are welcomed!

See #228 #252

**Comment by bitinn** [comment]
Also my result from a plain install:

```
test df$ npm install node-fetch@next
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ node-fetch@2.0.0-alpha.6
added 1 package in 4.038s
```

**Comment by bitinn** [comment]
Oh wait I misread your problem. We do tested for without `encoding` scenario in Travis CI, I have to double check again then...

**Comment by TooTallNate** [comment]
Sure it installs, but did you try requiring it?

**Comment by bitinn** [comment]
Yes I am working on fixing this, I don't understand how it happens really. Give me a few minutes

**Comment by bitinn** [comment]
alpha 7 release should have fixed this

**Comment by bitinn** [comment]
And a brief summary on why it could have happened:

- I was testing another feature which require me to be on node v5
- v5 use npm v3, which doesn't run `npm prepare` by default when you publish
- and somehow in my directory there is an older copy of `index.js` and `index.es.js`
- so while I am on the alpha.6 branch, the published package still contains an older version of node-fetch v2...

**Comment by TooTallNate** [comment]
alpha 7 works for me now. Thanks for the quick turnaround @bitinn!
