### ISSUE TITLE
How to fetch http api from https

### ISSUE THREAD

**Issue by ewinchen** [bitinn/node-fetch#322]
I have a project run in https, when I try to fetch data from a http api, I got this error:

`(node:8572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Protocol "http:" not suppor
ted. Expected "https:"`

Could anyone tell me how to resolve this, thanks a lot.

**Comment by bitinn** [comment]
Show us your code, or try httpbin.org to reproduce your problem.

(From my phone)

**Comment by ewinchen** [comment]
@bitinn thanks, I've solved this problem. I added a self certificate agent in the argument for testing https scenario, all will work well after removing ` { agent: agent }`

` var agent = new https.Agent({
    rejectUnauthorized: false
  })
  fetch('http://localhost:10010/assets/api/list',  { agent: agent })
    .then(function (res) {
      return res.json();
    }).then(function (json) {
      console.log(json);
      res.json(json);
    });`
