### ISSUE TITLE
Problem with headers

### ISSUE THREAD

**Issue by NikxDa** [bitinn/node-fetch#323]
Hello there,

I am experiencing a very weird problem that I need help with. It worked completely fine yesterday and I did not have a version change in node-fetch since then. Even restoring yesterdays version of the code did not solve my problem. I've narrowed it down to the following part. What I am trying to do is request a CSRF-Token from the Spotify Web Helper. A request for this is sent to spotilocal.com, which loops back to localhost. The request has to have the Origin header set to "https://open.spotify.com", otherwise, the site will return a 404. Problem:

```
const headers = { "Origin": "https://open.spotify.com" };
const url = "https://random.spotilocal.com:4370/simplecsrf/token.json";
const result = await fetch (url, { headers: headers });
const text = await result.text ();
console.log (text) // Prints "Not Found", even though the Origin header has clearly been set
```

I thought this might be a problem with the API, so I've sent the same request with Postman:

![postman](https://user-images.githubusercontent.com/3141005/28818071-5ef11752-76aa-11e7-833b-fa2801b68926.png)

This is the completely same request, done in Postman. As you can see, it returns the token just fine. When omitting the Header in Postman, we get the same result that we get with node-fetch: A 404 "Not found". See:

![postman2](https://user-images.githubusercontent.com/3141005/28818146-8c30604c-76aa-11e7-81ff-ce65cb67297c.png)

 Alright, so this might lead us to believe that node-fetch just does not add the header. This is not the case either. When checking for headers with a local express server, the "origin"-header is included just fine.

What causes this behaviour?
Kind regards

**Comment by NikxDa** [comment]
https://random.spotilocal.com:4370 is a URL which depends on multiple factors, the port can vary between 4370 and 4390 and SpotifyWebHelper needs to be running for the URL to work. I can confirm that the WebPage works fine when testing with Postman or Insomnia.

This is the response I get with node-fetch from `http://httpbin.org/headers`:
```
{
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip,deflate", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "Origin": "https://open.spotify.com", 
    "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
  }
}
```

**Comment by TimothyGu** [comment]
So what this shows is that the Origin header is set correctly, i.e. not a node-fetch issue per se. You might want to experiment with changing the User-Agent header, as Postman seems to use Chrome's by default.

**Comment by NikxDa** [comment]
Postman sends "PostManClient 6" or something like this. I know that this is not a node-fetch specific issue, or at least I cannot prove it. Still, it worked completely fine yesterday, and I was using node-fetch then, too. My codebase has changed since, but not the part where the request is sent. I was able to retrieve the tokens, and now I am not - still, it seems that we both cannot see any mistakes in the code above. Where else could the problem live? I even tried copying Postman headers.

**Comment by NikxDa** [comment]
Also, when sending with node-fetch, I cannot find any localhost GET requests via Wireshark, although when sending with Postman, there is a HTTP/1.1 GET and a HTTP 200 OK listed.

**Comment by TimothyGu** [comment]
My Postman installation seems to differ re `User-Agent`:

![screenshot from 2017-08-01 18-29-27](https://user-images.githubusercontent.com/1538624/28821410-dde53c0e-76e7-11e7-8cb0-236c3ab2de0f.png)

Have you tried `curl` or `wget`? Those tools tend to be much better debugging tool than Postman and its ilk.

> when sending with node-fetch, I cannot find any localhost GET requests via Wireshark

Are you sure the node-fetch code path is being taken?

Another thing to try is to replace node-fetch with another module like `require('https').get`.

**Comment by NikxDa** [comment]
I tried with https.get and it works just fine. And yes, the node-fetch path is being taken, otherwise I wouldn't receive the 404. This is getting more and more confusing.

**Comment by bitinn** [comment]
This kind of problem might be related to your `User-Agent` (server has some undocumented gatekeeper etc.), trying overwriting it with your custom one?

**Comment by NikxDa** [comment]
I've solved my problem by using the "request"-package, which does everything right. I do not know why fetch fails.

**Comment by bitinn** [comment]
Life's hard, use whatever you need to :)

**Comment by NikxDa** [comment]
I'd still prefer to use fetch, it has a much nicer API and much less overhead. Should you have any idea what may have caused the problem, please keep me up to date. I'll do my best to help investigating.

**Comment by NikxDa** [comment]
I'd like to request a reopening of this problem. Request produces a lot of overhead, and even the request successor (r2) uses node-fetch, so I am experiencing the same problem there. I'd love to find a solution.

**Comment by bitinn** [comment]
@NikxDa Please open a new issue for this, and use `curl` to reproduce with http://httpbin.org/ . We are only 2 maintainers and neither of us are going to have much time debugging how PostMan extension does its thing.

**Comment by NikxDa** [comment]
I understand, but I cannot reproduce the problem with other tools. PostMan works fine, Insomnia Client works fine, node-fetch works fine when used with httpbin, but it fails on this particular scenario (namely the SpotifyWebHelper token authorization). 

My test code is in the initial post. The same code still will not work, although it should.

**Comment by bitinn** [comment]
@NikxDa You got any way for us to reproduce it reliably?

The reason for a new ticket is: (1) so I don't forget, (2) so we can summarise what's actually happening a bit more concisely.

I think the PostMan test here is noise, if you can get node-fetch to work with httpbin, then the problem is what's happening when you actually do the request (and having a way to reproduce it make helping you easier because people can check where the mishap could be.)
