### ISSUE TITLE
Do not add `charset` parameter to `x-www-form-urlencoded` content-type

### ISSUE THREAD

**Issue by cedx** [bitinn/node-fetch#327]
The `application/x-www-form-urlencoded` MIME type does not support parameters (such as `charset`). If you look at [this section of the HTML5 spec](http://www.w3.org/TR/html5/forms.html#url-encoded-form-data), you will see how charset is determined (it's complicated). In particular, there is a note at the bottom of the section mentioning how charset cannot be specified as a parameter to the MIME type:

> Note: Parameters on the application/x-www-form-urlencoded MIME type are ignored. In particular, this MIME type does not support the charset parameter.

When working with some web services (like Akismet or Smartling), if I send a POST request using a `URLSearchParams` body, I always get an error from these services.

For Smartling, I get the explicit response:
`Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported`.

If I set my own `Content-Type` header to `application/x-www-form-urlencoded` (e.g. without a `charset`), everything works fine.

**Comment by TimothyGu** [comment]
The charset parameter is mandated by the Fetch Standard: https://fetch.spec.whatwg.org/#body-mixin

I believe browsers act the same way, but would be happy to be proven wrong. If you are not okay with that you can always override it yourself.

**Comment by cedx** [comment]
If it is in the spec... That's fine, I think it's better to open an issue at the services not properly parsing such content types. Thanks for the reply :smile:

**Comment by TimothyGu** [comment]
Yeah that's a better idea, though I do think the charset is a bit silly as "urlencoded" kind of implies ASCII-only content…

**Comment by cedx** [comment]
> the charset is a bit silly as "urlencoded" kind of implies ASCII-only content

I think exactly the same thing.
