### ISSUE TITLE
Get response headers while using res.json() always returns undefined

### ISSUE THREAD

**Issue by faidoc** [bitinn/node-fetch#329]
Hi

(using node-fetch@next)

I am trying to get the response headers to obtain a value I need and also I am using the res.json() helper, but the response always returns undefined when I put some code extra like this:

```
Fetch(`https://www.myurl.com.pe/api/catalog_system/${id}`, {
    headers: {
      'Content-Type': 'application/json',
      // eslint-disable-next-line quote-props
      'resources': `${currentPagination}-${nextPagination}`,
    },
  })
    .then((res) => {
      const resPaginationHeader = res.headers.get('resources').split('/');
      currentPagination += 50;
      nextPagination += 50;
      totalPagination = resPaginationHeader[1];
      res.json();
    })
    .then((response) => {
      console.log(response);
    })
    .catch((error) => {
      console.log(error);
    });
```

But if I put the first then to just do the res.json(), the response is correct.

```
Fetch(`https://www.myurl.com.pe/api/catalog_system/${id}`, {
    headers: {
      'Content-Type': 'application/json',
      // eslint-disable-next-line quote-props
      'resources': `${currentPagination}-${nextPagination}`,
    },
  })
    .then(res => res.json())
    .then((response) => {
      console.log(response);
    })
    .catch((error) => {
      console.log(error);
    });
```

Am I doing something wrong? I can't figure it out how to get a response header while keep having the response

I even tried with no res.json(), just getting the header value but the response still gets undefined.

**Comment by TimothyGu** [comment]
You didn't return `res.json()` in the first code fragment, whereas the second one does through the arrow syntax.

**Comment by faidoc** [comment]
-.- yep, that was it

Thank you so much
