### ISSUE TITLE
Response must parse headers from options

### ISSUE THREAD

**Issue by kirill-konshin** [bitinn/node-fetch#33]
According to spec if `options.headers` is not a `Headers` object, then it must be converted.

**Comment by bitinn** [comment]
Not quite sure what you mean by that, we do run `new Headers` when you call `fetch` with an object as options. But I won't expect the input itself be turned into `Header` instance.

Please provide us an example on where you run into this problem?

**Comment by kirill-konshin** [comment]
Test case:

```js
(new Response()).headers instanceof Headers // true
```

**Comment by kirill-konshin** [comment]
Same applies to `Request` class as well. In current implementation it is a simple assignment:

```js
this.headers = init.headers || input.headers || {};
```

How it should be done:

```
this.headers = new Headers(options.headers)
```

**Comment by kirill-konshin** [comment]
Also `Response` may receive it's body as a string, in this case it should be either converted to a stream or stored as string, but in this case `.__decode()` method should be aware of that.

**Comment by bitinn** [comment]
You are right. We didn't follow the spec in these aspects as we don't see any good use-case for it.

**Comment by kirill-konshin** [comment]
Unit tests -- to pass around certain responses and requests since the rest of the code is fetch-based.

**Comment by bitinn** [comment]
You might need to provide a real-world example for it.

The reason we expose Header/Response/Request classes are not because we want this module to be isomorphic as `window.fetch`. But rather there are requests to have them exposed for testing purpose.

I hope there is no confusion here.

**Comment by kirill-konshin** [comment]
It's not about isomorphism, it's about not following the spec. Since you already expose `Header/Response/Request` classes they should be compatible with the latest spec.

It's good that they are exposed for testing purposes because this is the main use case: to have an ability to build a custom `Response` and pass it as a mock w/o calling `fetch`.

**Comment by bitinn** [comment]
Could you show me some code? What were you trying to do that's affected by this issue? I am a bit busy early august so this might not be on my priority list.

**Comment by kirill-konshin** [comment]
Very short example:

```js
function multipartMixedParserToBeTested(response){
    if (response.headers.get('content-type').indexOf('multipart/mixed') !== -1) {
        // ...
    }
}

var responseMock = new Response(body, {{headers:{'content-type': 'multipart/mixed'}});

multipartMixedParserToBeTested(responseMock).then(...);
```

**Comment by bitinn** [comment]
Fair enough, I will look into fixing it next week (parse headers for Response and Request when input is not already a Headers)

**Comment by kirill-konshin** [comment]
Thanks :)

**Comment by bitinn** [comment]
PR welcomed too :)

**Comment by kirill-konshin** [comment]
In the next couple of days you'll get a PR.

**Comment by kirill-konshin** [comment]
PR https://github.com/bitinn/node-fetch/pull/37 has been created
