### ISSUE TITLE
Fetch Error: HPE_HEADER_OVERFLOW

### ISSUE THREAD

**Issue by Chalin-Shi** [bitinn/node-fetch#334]
What's the meaning like this:
```javascript
{
    "name": "FetchError",
    "message": "request to myurl failed, reason: Parse Error",
    "type": "system",
    "errno": "HPE_HEADER_OVERFLOW",
    "code": "HPE_HEADER_OVERFLOW"
}
```

**Comment by jkeylu** [comment]
https://stackoverflow.com/a/35330480/875843

**Comment by bitinn** [comment]
That SO link should have answered this question.

**Comment by Gp2mv3** [comment]
I also get this error and don't understand if it happens on the header of the request, or the response.
Can you clarify ?
