### ISSUE TITLE
Body not registered properly

### ISSUE THREAD

**Issue by nharbo** [bitinn/node-fetch#338]
Hi!
I'm making this request, which works perfectly when sent from PostMan:

    var body = {
      user_id: "ZOZaqB5now",
      custom_attributes: {
        Plan : "changed plan via API",
        Fitcoins: 0
      }
    };
    
    fetch('https://api.intercom.io/users', { 
        method: 'POST',
        body:    JSON.stringify(body),
        headers: {
                'Accept': 'application/json',
                'Content-Type': 'multipart/form-data',
                'Authorization': "Bearer xxxxx"
            },
    })
        .then(res => res.json())
        .then(json => console.log(json));

The response is this:
{ type: 'error.list',
  request_id: 'au9jlm32hb6mskt9vji0',
  errors: 
   [ { code: '400',
       message: 'User email, user_id or anonymous_id must be supplied' } ] }

So it seems like it doesn't register the body - am I doing anything wrong? I'm sure the fields i nthe json object are named properly

Best regards,
Nicolai

**Comment by jimmywarting** [comment]
You are sending a json body with a multipart/form-data?!
That looks wrong to me...

**Comment by bitinn** [comment]
Closing as I don't see further issues.

PS: You can always use https://httpbin.org/ to test out your request.
