### ISSUE TITLE
Feature request: Support URL object as fetch argument

### ISSUE THREAD

**Issue by guybedford** [bitinn/node-fetch#339]
In browsers, `fetch(new URL('https://url.com/path'))` is supported.

Ideally the same could be supported in NodeJS here (especially since URL is supported as the argument for even `readFile` now) - 

```js
const { URL } = require('url');
const fetch = require('node-fetch');

const url = new URL('https://url.com/path');
(async () => {
  const res = await fetch(url); // this would be nice to work
})();
```

Would also avoid unnecessary repeat sanitization and parsing, when in theory is a saving at some micro benchmark level.

**Comment by TimothyGu** [comment]
We already support it in v2.0.0-alpha. See https://github.com/bitinn/node-fetch/issues/175.

Also, browsers don't really support URL objects specifically: they just casts any input to a string.
