### ISSUE TITLE
Support cloning of Responses

### ISSUE THREAD

**Issue by kirill-konshin** [bitinn/node-fetch#34]
According to MDN https://developer.mozilla.org/en-US/docs/Web/API/Response/clone and the spec https://fetch.spec.whatwg.org/#dom-response-clone Response class should have a clone() method, which seems to be missing now.

**Comment by tracker1** [comment]
I'd suggest the [safe-cone-deep](https://www.npmjs.com/package/safe-clone-deep) npm module, but I'm biased.  It's good enough for pm2 ;-)

**Comment by kirill-konshin** [comment]
Don't forget that `clone()` may occur any time, including when original response is being read.

So `clone()` should create a new object with already read data and allow further reading of same (or piped) source.

**Comment by bitinn** [comment]
@kirill-konshin are you using clone? if so, how? I do feel `clone()` is an API that's so rarely used by developers.

**Comment by kirill-konshin** [comment]
It gives an ability to re-read the response. This use-case is even mentioned at MDN.

**Comment by kirill-konshin** [comment]
Here is a simple solution based on your codebase:

```js
// in response.js inside _decode method the following should be moved to constructor
this._raw = [];

// introduce a new flag _ended which should be true on end event of body

// new method
Response.prototype.clone = function() {
    // if body has been captured, 
    var body = (this._ended) ? Buffer.concat(this._raw) : this.body;
    var clone = new Response(body, this);
    clone._raw = this._raw; // provide whatever has been captured already
    return clone;
}
```

This is another example how passing buffers to constructor may help.

**Comment by bitinn** [comment]
v1.4.0 now has `clone` built-in :)
