### ISSUE TITLE
Retry Support

### ISSUE THREAD

**Issue by cggaurav** [bitinn/node-fetch#344]

**Comment by bitinn** [comment]
Nope.

(Or do you want to provide us with more information on why we should add a feature that goes beyond Fetch Spec?)

**Comment by SimenB** [comment]
You can use make-fetch-happen, it adds retry support on top of fetch

**Comment by bitinn** [comment]
@SimenB that's cool, but it uses a fork of node-fetch v2, look closer and you will see.

**Comment by trycontrolmymind** [comment]
I think you just need to give an example of retry-fetch implementation in docs.
It would help some peoples...
