### ISSUE TITLE
Expose FetchError in the public API

### ISSUE THREAD

**Issue by jefflage** [bitinn/node-fetch#352]
To improve the handling for operational vs. code errors, it would be nice if `FetchError` class/prototype was exposed/exported from calling `require('node-fetch')`.  This could be done even just by setting a property on the fetch function:
```javascript
// expose Promise
Fetch.Promise = global.Promise;
Fetch.Response = Response;
Fetch.Headers = Headers;
Fetch.Request = Request;
// this is the new part
Fetch.FetchError = FetchError;
```

**Comment by bitinn** [comment]
FYI, this is in the v2 release. PR welcomed to backport into v1.

**Comment by jefflage** [comment]
Is v2 the GA release yet?  i simply ran `npm install` last week and got 1.7.3

**Comment by bitinn** [comment]
@jefflage see readme, install with @next tag
