### ISSUE TITLE
GET method is not allowed to have a body

### ISSUE THREAD

**Issue by puskin94** [bitinn/node-fetch#357]
Hi all,
I'm trying to make a `GET` request that includes a `body` due to a `Node.Js` [limit on the size](https://github.com/nodejs/node/blob/db1087c9757c31a82c50a1eba368d8cba95b57d0/deps/http_parser/http_parser.h#L56) of the request header (~80kb)

According to the [specifications](https://tools.ietf.org/html/rfc2616#section-4.3) every method should be allowed to contain the `body` except for the `HEAD` method.
Reading the code on [this line](https://github.com/bitinn/node-fetch/blob/v1.7.0/index.js#L93) (version 1.7.0) I can see that the `GET` method is excluded.

Can I ask if there is any reason why this method is excluded from the Regex?
Thanks in advance

**Comment by TimothyGu** [comment]
From a spec perspective:

RFC 2616 has been obsoleted by RFCs 7230-7235, so don't cite it anymore. RFC 7231 "Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content" [specifies](https://tools.ietf.org/html/rfc7231#section-4.3.1):

> A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.

----

For why we don't allow input bodies in node-fetch, we follow the Fetch Standard, the same spec used by web browsers. See https://fetch.spec.whatwg.org/#dom-request step 33:

> If either *init*’s body member is present and is non-null or *inputBody* is non-null, and *request*’s method is \``GET`\` or \``HEAD`\`, then throw a TypeError.
