### ISSUE TITLE
HEAD/head method different behavior (case sensitive)

### ISSUE THREAD

**Issue by vitalets** [bitinn/node-fetch#361]
By spec method [should be in uppercase](https://fetch.spec.whatwg.org/#methods): `GET`, `POST`, etc.
But `node-fetch` works well for me with both lowercase and uppercase.
Until I run the following:
```js
const fetch = require('node-fetch');
(async () => {
  await fetch('https://api.github.com/users/vitalets', {method: 'head'});
  await fetch('https://api.github.com/users/vitalets', {method: 'get'});
  console.log('ok');
})();
```
Inn output there is an error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Gunzip.zlibOnError (zlib.js:152:15)
```
But if I change `head` -> `HEAD`, everything works:
```js
const fetch = require('node-fetch');

(async () => {
  await fetch('https://api.github.com/users/vitalets', {method: 'HEAD'});
  await fetch('https://api.github.com/users/vitalets', {method: 'get'});
  console.log('ok');
})();
```
I think it should be fixed for consistency.

**Comment by bitinn** [comment]
You are using 1.x release?

The issue should be fixed in 2.x, it's pretty stable and more up-to-date with the spec.

And you are welcomed to open a PR to backport this.

**Comment by vitalets** [comment]
> You are using 1.x release?

Yes, I'm on 1.7.3.

> it's pretty stable

Ok, I will try.
Just confused with `alpha` status of 2.x in docs =)

**Comment by bitinn** [comment]
@vitalets Spec is still changing slowly (sometimes with small breaking changes) so we decided to not put 2.x into stable/beta release just yet. But many are using it.

**Comment by vitalets** [comment]
Ok. Thanks for info!
