### ISSUE TITLE
Post body data example doesn't work, Content-Length is not specified

### ISSUE THREAD

**Issue by IjzerenHein** [bitinn/node-fetch#368]
Hi, great library, just found this issue with an example in the README. The `post with stream from file` example states that this should work:

```js
// post with stream from file
import { createReadStream } from 'fs';

const stream = createReadStream('input.txt');
fetch('http://httpbin.org/post', { method: 'POST', body: stream })
	.then(res => res.json())
	.then(json => console.log(json));
```

However, it doesn't. Httpbin returns with an internal error.

After inspection, I found that you'll need to specify `"Content-Length"` in the header. The following does work though:

```js
const fs = require('fs');
const fetch = require('node-fetch');

fs.readFile('test/assets/test.txt', (error, file) => {
	fetch('http://httpbin.org/post', {
		method: 'POST',
		headers: {
			"Content-Length": file.length
		},
		body: file
	})
	.then(res => res.json())
	.then(json => console.log(json));
});
```

Cheers  🤘

**Comment by bitinn** [comment]
Thx for pointing this out, this is an issue for the receiving side though: without content-length you are using chunked transfer-encoding, and httpbin doesn't handle it.

I guess there was an error when moving from 1.x doc to 2.x; no one actually check whether it works.

I think this original code should work; or at least when I was testing it 2 years ago ;)

```
var resumer = require('resumer');
var stream = resumer().queue('a=1').end();
fetch('http://httpbin.org/post', { method: 'POST', body: stream })
	.then(function(res) {
		return res.json();
	}).then(function(json) {
		console.log(json);
	});
```

**Comment by jimmywarting** [comment]
when creating a readableStream from a file it will include a path ([readstream.path](https://nodejs.org/api/fs.html#fs_readstream_path)) and a `readstream.fd`

With the help of path or `fd` it would be possible for node-fetch to retrieve the content size of the file synchronous with `fs.statSync(path)` or `fs.fstatSync(fd)`

**Comment by bitinn** [comment]
readme was updated to address this issue.
