### ISSUE TITLE
Provide separate agents for http and https

### ISSUE THREAD

**Issue by pietermees** [bitinn/node-fetch#371]
Node has different base classes for `http` and `https` requests. Under normal circumstances we can select the appropriate `agent` option to pass to `node-fetch` based on the protocol of the url we're requesting.

But if the response of the initial request results in a redirect to a url with another protocol, the `agent` we passed in no longer matches the new redirect url.

Would it be possible to extend the `agent` option to accept a different agent per protocol, and then select the right agent depending on which url is requested in the redirect chain?

**Comment by bitinn** [comment]
Try handling redirect yourself? Use `redirect: manual` and handle the url with appropriate `agent`.

**Comment by pietermees** [comment]
Ok, will try that, thanks!
