### ISSUE TITLE
Should fetch not accept a URL instance?

### ISSUE THREAD

**Issue by 0x80** [bitinn/node-fetch#372]
I was wondering why I can't pass a WHATWG URL class instance to the fetch method.

From https://github.com/whatwg/fetch/issues/452 I read that it should call toString() on the first parameter.

It would sure be convenient. For example here the last toString() call seems unnecessary:

```javascript
  const params = new URLSearchParams({
    access_token: accessToken,
    fields: ["friends"]
  });

  const url = new URL(params.toString(), facebookEndpoint);
  const result = await fetch(url.toString()).then(res => res.json());
```

**Comment by TimothyGu** [comment]
Can you try out version 2.x, as detailed in the [README](https://github.com/bitinn/node-fetch#install)?

**Comment by 0x80** [comment]
Ah cool thanks. 

But in the meantime I found out that I can't even use the URL API since I'm tied to Node 6.11 because of google cloud functions 😞

**Comment by TimothyGu** [comment]
@0x80 Wait until https://github.com/nodejs/node/pull/17365 gets merged :smile: 

But in the meantime you can consider using [whatwg-url](https://www.npmjs.com/package/whatwg-url), which is basically a reference implementation for the WHATWG URL Standard that I help maintain, that does support v6.x.

I'll close out this issue. Do comment here if you have any additional questions though.

**Comment by 0x80** [comment]
@TimothyGu Sorry to bother you again but I somehow don't see a way to pass URLSearchParams to format a URL instance. What am I missing? I would like to do something like this:

```javascript
 const params = new URLSearchParams({
      access_token: accessToken,
      fields: [
        "picture",
        "first_name",
        "middle_name",
        "last_name",
        "email",
        "gender",
        "locale",
        "name_format",
        "verified",
        "work"
      ].join(","),
      debug: "all"
    });

    const url = new URL(params.toString(), facebookEndpoint);
```

Here I think still need to insert the `?` somewhere, but string interpolation is what I'm trying to avoid with this URL API. The URL constructor doesn't seem to have a way to pass the query part as an option, so I'm not sure how this would work...

**Comment by 0x80** [comment]
On second though I think this will do just fine 😄 

`const url = new URL(`?${params.toString()}`, facebookEndpoint);`

I'm using Typescript and I can't yet find any typing for whatwg-url. Can I grab them from some other repo that you know of?

**Comment by 0x80** [comment]
Aha! It appears that Typescript has the URL standard built in already in its libs. But you have to enable it in tsconfig:

```json
"compilerOptions": {
    "lib": ["dom"]
}
```

**Comment by TimothyGu** [comment]
> On second thought I think this will do just fine 😄 
>
> ```javascript
> const url = new URL(`?${params.toString()}`, facebookEndpoint);
> ```

Yup. Alternatively, this will work too since the `.search` setter will automatically cast the URLSearchParams object to a string:

```js
const url = new URL(facebookEndpoint);
url.search = params;

// or

const url = Object.assign(new URL(facebookEndpoint), { search: params });
```

**Comment by 0x80** [comment]
@TimothyGu Nice, that's what I was looking for!

I am now trying to pass the URL instance to node-fetch@next, but the compiler still doesn't like it because my @types/node-fetch are at v1. I don't see any types for v2?
