### ISSUE TITLE
Download file example

### ISSUE THREAD

**Issue by davideicardi** [bitinn/node-fetch#375]
I'm having some problems downloading file. In your readme file you have written the following example:

```js
fetch('https://assets-cdn.github.com/images/modules/logos_page/Octocat.png')
.then(res => {
  const dest = fs.createWriteStream('./octocat.png');
  res.body.pipe(dest);
});
```
But it my case it seems that destination file remain locked, it is not closed automatically I think. Probably is not related to `node-fetch` library but it is just how stream works. But maybe you can add a more complete example ...

I have written this code:

```js
const res = await fetch('https://assets-cdn.github.com/images/modules/logos_page/Octocat.png');
await new Promise<void>((resolve, reject) => {
  const fileStream = fs.createWriteStream('./octocat.png');
  res.body.pipe(fileStream);
  res.body.on("error", (err) => {
    fileStream.close();
    reject(err);
  });
  fileStream.on("finish", function() {
    fileStream.close();
    resolve();
  });
});
```

I'm right or I missing something?

thanks

**Comment by bitinn** [comment]
Turns out you just need an `autoClose` option :)

https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

PR welcomed to fix this code sample.

**Comment by jkantr** [comment]
er.. was just looking at this for the readme update discussion... `createWriteStream`'s `autoClose` option defaults to `true`. It should be closing the fd itself on `error` or `finish` events. The example as is *should* work.

**Comment by davideicardi** [comment]
The problem I think is that when the promise returns the stream is not actually closed, the pipe is not completed.
So probably a better example (for dummies like me 😄 ) would be:

```
async function download() {
	const res = await fetch('https://assets-cdn.github.com/images/modules/logos_page/Octocat.png');
	await new Promise((resolve, reject) => {
		const fileStream = fs.createWriteStream('./octocat.png');
		res.body.pipe(fileStream);
		res.body.on("error", (err) => {
			reject(err);
		});
		fileStream.on("finish", function() {
			resolve();
		});
	});
}
```

So the example IS correct but if you copy that code you will probably don't get what do you expect.
I'm right?

**Comment by jdleesmiller** [comment]
In node 10+, I think this can be simplified using [stream.pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback):

```js
const util = require('util')
const fs = require('fs')
const streamPipeline = util.promisify(require('stream').pipeline)

const fetch = require('node-fetch')

async function download () {
  const response = await fetch('https://via.placeholder.com/150')
  if (!response.ok) throw new Error(`unexpected response ${response.statusText}`)
  await streamPipeline(response.body, fs.createWriteStream('./placeholder.png'))
}
download()
```

Credit: https://stackoverflow.com/a/53261298/2053820

**Comment by gr2m** [comment]
Thanks for the pointer, @jdleesmiller! Could you maybe open a new issue so that your comment doesn’t get lost?

**Comment by shahriar-shojib** [comment]
> In node 10+, I think this can be simplified using [stream.pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback):
> 
> ```js
> const util = require('util')
> const fs = require('fs')
> const streamPipeline = util.promisify(require('stream').pipeline)
> 
> const fetch = require('node-fetch')
> 
> async function download () {
>   const response = await fetch('https://via.placeholder.com/150')
>   if (!response.ok) throw new Error(`unexpected response ${response.statusText}`)
>   await streamPipeline(response.body, fs.createWriteStream('./placeholder.png'))
> }
> download()
> ```
> 
> Credit: https://stackoverflow.com/a/53261298/2053820

Is there a way to detect the file type even if the extension is not visible in the URL and save the file to disk according to the extension?

**Comment by gr2m** [comment]
Can you use the Content-Type response header?

**Comment by shahriar-shojib** [comment]
Hello, Sorry I forgot to provide an update here. 
Yes, I soon found out that the server provides a content-type header and I am able to use it to download the files with the proper extension.
Thanks for your help.

**Comment by msikma** [comment]
For those who are interested in the above, using the Content-Type header turns out to be very simple. I recommend using a package like `mime-types` to easily get the proper extension. Something like this is an example:

```js
const util = require('util')
const fs = require('fs')
const streamPipeline = util.promisify(require('stream').pipeline)
const mime = require('mime-types')
const fetch = require('node-fetch')

async function download() {
  const response = await fetch('https://via.placeholder.com/150')
  if (!response.ok) throw new Error(`unexpected response ${response.statusText}`)
  const type = response.headers.get('Content-Type')
  await streamPipeline(response.body, fs.createWriteStream(`./placeholder.${mime.extension(type)}`))
}
```
