### ISSUE TITLE
Add option to disable default headers

### ISSUE THREAD

**Issue by danog** [bitinn/node-fetch#376]
Hi there,
I have encountered a small problem while using this lib, namely, there is no way to disable auto-setting of the default headers.
In particular, I am trying to use an API that accepts only requests with no User-Agent header.
Usage of an empty User-Agent is not allowed by the API, and if no User-Agent header is set in the options, node-fetch automatically inserts its own.

I therefor ask you to add an excludeDefaultHeaders option.

**Comment by bitinn** [comment]
Sorry, empty User-Agent request is generally a bad idea (and browsers will always send UA), hopefully the API publisher tells you their preferred User-Agent instead of forcing no User-Agent header at all.

**Comment by TimothyGu** [comment]
Closing per https://github.com/bitinn/node-fetch/issues/376#issuecomment-350660838.

**Comment by jimmywarting** [comment]
PS. might be possible to do it yourself later when node-fetch becomes modular somehow.
some discussion going on here: https://github.com/bitinn/node-fetch/issues/284
