### ISSUE TITLE
clone bug in some website ?

### ISSUE THREAD

**Issue by beginnor** [bitinn/node-fetch#380]
in version  2.0.0-alpha.8  
I find the lib in crawling  some websites ,eg. https://www.baidu.com  .
I locate in the code at `clone` function  ,but cant solve it .

**Comment by bitinn** [comment]
I need more information, what sort of bugs/errors?

Also need a way to reproduce your problem.

**Comment by beginnor** [comment]
you can test use this website  (https://www.baidu.com) ,you can find cannot output any result

**Comment by bitinn** [comment]
I am not going to troubleshoot this myself: but Fetch knows nothing about website or html, it returns what the site returns.

You need to figure out if Baidu is actually returning anything.

Or you can provide actual code and errors.
