### ISSUE TITLE
Allow to set connection timeout

### ISSUE THREAD

**Issue by mantasindrasius** [bitinn/node-fetch#382]
Current API only allows to set the request timeout that includes DNS, new TCP connection and server processing of the issued request.

This makes it impossible to apply different timeout strategies to tackle network issues or slow backend servers separately.

Please consider adding a new timeout option that would reset once `connect` event is issued by the underlying `http` package.

**Comment by bitinn** [comment]
You probably want a more fine-grained control than Fetch is designed to offer.

We *might* expose the native HTTP req/res object for you to hook something similar onto it, but probably not going to expose it through additional API or Fetch options.

Let us know what you have in mind there: https://github.com/bitinn/node-fetch/issues/284#issuecomment-346335804

**Comment by jimmywarting** [comment]
I where just thinking how timeout isn't a standard and a AbortSignal should be sent in instead.
timeout is a extension to node-fetch and thought about making an issue earlier today about taking it away.

Leaving you to do this instead:
```js
var controller = new AbortController()
fetch(url, {signal: controller.signal})
setTimeout(controller.abort, 5000)
```

There is discussion of making node-fetch more modular allowing you to do more with the request. Maybe that is the way to go... Doing it yourself

You would have to 

 1) write some pice of code that hooks into node-fetch requests
 2) pass in a AbortController
 3) listen for the connect event and start a timer from when you want to call AbortController

**Comment by mantasindrasius** [comment]
@bitinn having the more fine-grained control is what I meant. 
@jimmywarting thanks. AbortSignal seems like a pretty powerful concept. Would like to have something like this.

**Comment by jimmywarting** [comment]
Do you wish to close this in favor of having fine-grained control and a AbortController instead of another timeout? (cuz we already have other issues about dose two)

**Comment by mantasindrasius** [comment]
Sure
