### ISSUE TITLE
node-fetch how to attach 'cookie' field to request headers

### ISSUE THREAD

**Issue by sulliwane** [bitinn/node-fetch#383]
Hello,

I'm using node-fetch in a node environment.

I'd like to manually attach a ```cookie``` field to my request header (which is done automagically by browsers I guess?).

I'm trying to do this with no luck:
```js
const headers = { cookie: `manual=mycustomvalue` };
const res = await fetch(uri, { headers });
```
While using node ```https``` module works:
```js
const options = {
  hostname,
  port,
  path,
  method: 'GET',
  headers: { Cookie: `manual=mycustomvalue` },
};

const req = https.request(options, (res) => {
  res.on('data', () => {});
  res.on('end', () => resolve(res.headers));
});
req.on('error', (e) => reject(e));
req.end();
```
Any input on this? Many thanks!

**Comment by bitinn** [comment]
`await fetch(uri, { headers });`

Shouldn't you assign `headers: headers`?

**Comment by sulliwane** [comment]
Thank you @bitinn for your help.

Would you mind being more specific?

If your remark is about the _object shorthand property name_ feature, [it's supported since ECMASCRIPT 2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) so ```{ headers } === { headers: headers }```

Here is another way to set Cookie field using [request](https://www.npmjs.com/package/request) package:

```js
const jar = request.jar();
const url = 'https://'.concat(hostname, ':', port);
const jarCookie = request.cookie('manual=mycustomvalue');
jar.setCookie(jarCookie, url);
await request({ url, jar });
const cookie = jar.getCookies(url);
```

**Comment by bitinn** [comment]
So you are sure your environment allow ES2015 right?

Give http://httpbin.org/ a try then? Do share your full code if you can reproduce it.

**Comment by dominikstoetter** [comment]
while writing a nodeserver to appserver application i ran into this issue which is propably related to https://github.com/bitinn/node-fetch/issues/260
Its the `Cookie` header that gets`.toLowerCase()`'d and becomes `cookie`.

to reproduce, just:

```
const headers = {
  'Cookie': 'fancy-cookie'
}
const body = {}
fetch(url, {headers, body, method: 'POST'})
```

the server will receive `cookie` as a header and not treat it as 'Cookie'.

**Comment by TimothyGu** [comment]
HTTP headers are case-insensitive. You should probably fix your server instead.

Also closing, since the OP has been inactive.
