### ISSUE TITLE
Document size

### ISSUE THREAD

**Issue by nnnikolay** [bitinn/node-fetch#384]
I want to fetch a page specifying that I need exactly compressed version (`compress: true`). But then I don't know how to get the size of the page, and I need exactly the size of the compressed version. 

Right now I can do 

`res.buffer().then(d => console.log(d.length))`

but it shows me the uncompressed size already.

and dealing with the response body stream is also showing me the uncompressed version

`res.body.on('data', (d) => console.log(d.length))`

Is it feasible to achieve?

**Comment by bitinn** [comment]
You do need `compress: false` and decompress it yourself, this is a limit of Fetch API: we can only expose one stream, it can either be decompressed or raw...

**Comment by nnnikolay** [comment]
@bitinn 

I got it, thanks.

here is the way how I've solved it.
I specify header which tells a server to send the compressed response and set `compres: false` to do not do any decompression on the client side. 

```
fetch(url, {
  headers: { 'Accept-Encoding': 'gzip' },
  compress: false
}).then(res => {
    let result = 0;
    res.body.on('data', (d) => result += d.length)
    .on('end', () => console.log('File size is: ' + result));
})
```
