### ISSUE TITLE
how should I get the content of res when `.json()` fail ?

### ISSUE THREAD

**Issue by snadn** [bitinn/node-fetch#385]
I use `_convert` to get the content when `.json()` fail，but `_convert` is inaccessible in 2.x .

Maybe I used a wrong method, so I want to know how to get the response content in 2.x .

Looking forward to your help！

ps:
```javascript
	let resData = null;
	try {
		resData = await res.json();
	} catch (err) { /*  */ }

	log('res data: ', resData);

	if (res.ok) {
		return resData;
	}

	if (resData) {
		throw {
			errInfo: `${NAME}:ERROR`,
			errmsg: resData.resultdesc,
			errno: Number(`${res.status}${resData.resultcode}`),
			info: resData,
		};
	} else {
		const text = res._convert().toString();
		throw {
			errInfo: `${NAME}:ERROR`,
			errmsg: '请求转发响应出错',
			errno: 1,
			text,
		};
	}
```

**Comment by bitinn** [comment]
You need to clone() first and work on the separate response body with text().

And be careful about nodejs high water mark when you do that (search for an open issue where I discuss it).

JSON are UTF so you don’t need to convert it further (the conversion was designed to handle non-UTF HTML page, because Fetch Spec assume UTF-8)

(From my phone)

**Comment by snadn** [comment]
@bitinn I think can not use clone

I used to use the clone. but when I get a large res，since the clone in the else not consumption the clone and the .json will be hold by backpressure , then a timeout will be triggered

**Comment by bitinn** [comment]
You need to pipe the clone() body somewhere (say a stream with higher water mark), this is the cost of using stream. It’s designed so that your nodejs won’t hold more data in memory.

(From my phone)

**Comment by bitinn** [comment]
By the way, if you don't need to clone afterwards (for instance, the response is fine), pipe it to something like https://github.com/Floby/node-stream-blackhole

**Comment by snadn** [comment]
Maybe I can use .text and JSON.stringify by myself when _convert can not be used 😞

thanks!

**Comment by bitinn** [comment]
Yeah, many users do that because they need logging anyway.

We are not doing anything special with json() there so you are not missing much. https://github.com/bitinn/node-fetch/blob/master/src/body.js#L93

**Comment by snadn** [comment]
Do you think it makes sense to add buffer.toString () to the .json FetchError?

**Comment by bitinn** [comment]
Some want the whole response, some just want to know which part of the reponse is broken.

We decide to leave it to users, as Fetch Spec doesn't do any of this.
