### ISSUE TITLE
404 400 500 responses dose not trigger the catch block

### ISSUE THREAD

**Issue by yaronlevi** [bitinn/node-fetch#398]
I have an existing code base which uses **Axois**, and I want to port to node-fetch.
All my calls are wrapped with try-catch blocks, and it's important that an erroneous response (404,400,500...) will reach the catch black and not continue executing code after the call.

```
try{
await axios.get('/user?ID=12345')
//If we got 404, we should not reach this line, and instead go to catch block.
}catch(){
}
```

When using node-fetch instead of Axios, the catch block will not be triggered. How can I change this behavior?

**Comment by TimothyGu** [comment]
You cannot. That's how `fetch()` works, including in browsers. You could throw yourself however:

```js
try {
  const res = await fetch(...);
  if (!res.ok) {
    // All error codes would go into this condition
    throw new Error(...);
  }
} catch (err) {
  // ...
}
```
