### ISSUE TITLE
bodyUsed bug

### ISSUE THREAD

**Issue by jamesplease** [bitinn/node-fetch#399]
Affected `node-fetch` versions: ^1.0, 2.0

**Issue type:**
bug (possibly)

**Summary:**
Passing a used `body` into the constructor of a `Response` does not set the `bodyUsed` property of the new `Response ` to `true`. The native `Response ` _does_ set the `bodyUsed` property as `true`.

**Reproducing:**

Run the following code:

```js
fetch('https://jsonplaceholder.typicode.com/posts/1')
  .then(res => {
    const text = res.text();
    console.log(res.bodyUsed);
    // => true
    
    var newResponse = new Response(res.body, res);
    console.log(newResponse.bodyUsed);
    // => `true` if using Chrome, `false` if using node-fetch, Safari, Firefox
  });
```

Source of this behavior within `node-fetch`: https://github.com/bitinn/node-fetch/blob/c0950b7b9f0720cc9a0915968d5585d87286fba1/src/body.js#L52

This behavior isn't in the MDN docs, so I'm going to dig into the spec to see if it's described there.

----

Interestingly, both Chrome and node-fetch share the underlying stream between the two responses:

```js
fetch('https://jsonplaceholder.typicode.com/posts/1')
  .then(res => {    
    var newResponse = new Response(res.body, res);
    console.log(newResponse.body === res.body);
    // => `true` for Chrome and node-fetch
  });
```

I'm reasonably certain this is a bug but I'm no expert at the fetch spec, so maybe someone more knowledgeable can confirm :v: Thanks!

**Comment by jmeas** [comment]
I sought out an expert opinion on Twitter (thanks @jakearchibald !). He is also thinking it is a bug:

https://twitter.com/jaffathecake/status/962609913305403392

**Comment by bitinn** [comment]
https://streams.spec.whatwg.org/#is-readable-stream-disturbed

I am not sure if Node.js stream has any equivalent.

An interesting question really: What's left of a stream object, after it has been consumed? I have never thought about it.

**Comment by bitinn** [comment]
By the way `res.body` is just a Node.js stream, nothing more. The `disturbed` flag is not in the `res.body`. The stream must provide a way to tell node-fetch it has been consumed. Otherwise we need to figure it out from `res` (but that's not spec compliant?)

**Comment by TimothyGu** [comment]
@jmeas [Sought further clarifications](https://twitter.com/Timothy_Gu/status/962739344640376832) from @jakearchibald. I am not sure I agree with his reading of the spec.

**Comment by jmeas** [comment]
Thanks for the follow-up @TimothyGu ! Further clarification is definitely necessary.

For the record, here is my interpretation (and why I opened this issue):

First, taking a look at the Response constructor in the [Response class definition](https://fetch.spec.whatwg.org/#response-class):

<img width="971" alt="screen shot 2018-02-11 at 9 31 39 am" src="https://user-images.githubusercontent.com/2322305/36076241-63656c00-0f0e-11e8-8e9f-7c4641f06c21.png">

The first argument is a `BodyInit`. Clicking that takes you to the BodyInit definition within the Body mixin section of the spec:

<img width="987" alt="screen shot 2018-02-11 at 9 34 05 am" src="https://user-images.githubusercontent.com/2322305/36076271-bb3f52a6-0f0e-11e8-98d8-16dd06be1da5.png">

A ReadableStream is a valid input here.

Looking at the BodyMixin definition, we can see that `bodyMixin.body` is a getter for the ReadableStream.

<img width="483" alt="screen shot 2018-02-11 at 9 44 59 am" src="https://user-images.githubusercontent.com/2322305/36076385-4bbf929a-0f10-11e8-9a82-a6403d471440.png">

Therefore, `new Response(otherResponse.body)` is valid code.

The last piece of the puzzle is `bodyUsed`, which is defined as:

<img width="602" alt="screen shot 2018-02-11 at 9 46 24 am" src="https://user-images.githubusercontent.com/2322305/36076398-78950462-0f10-11e8-8568-6868ec5682c5.png">

This doesn't explicitly state that it is referring to the ReadableStream exposed by BodyMixin.body, but I think that is a safe assumption to make. 

---

What is your interpretation of the spec, @TimothyGu ?

**Comment by TimothyGu** [comment]
It’s definitely acceptable. The question is whether the original stream should be locked or not. I couldn’t find a step in the spec for the [`body` getter](https://fetch.spec.whatwg.org/#dom-body-body) or the [`Response()` constructor](https://fetch.spec.whatwg.org/#dom-response) that does, and would assume it to be the opposite.

**Comment by TimothyGu** [comment]
Sorry, I meant **disturbed** rather than **locked**. A stream is disturbed [only if the stream has been cancelled or read from](https://streams.spec.whatwg.org/#rs-internal-slots). Therefore my original message stands.

**Comment by TimothyGu** [comment]
https://twitter.com/jaffathecake/status/962761402715901952 answers my question:

> It just references the stream, so if the original is locked, so is the new one

I overlooked the fact that the original stream had been read from.

I don't have a good way of fixing this. Node.js streams just don't really have the concept of being locked or disturbed. One solution that came to mind is using a `WeakSet` for all streams that have been read from, but that is too drastic. @jmeas do you have any ideas?

**Comment by jmeas** [comment]
> I overlooked the fact that the original stream had been read from.

👍 

> ... @jmeas do you have any ideas?

Both of my ideas seem too drastic, as well. The first idea is basically what you proposed: some system where we do bookkeeping to keep track of read streams. The other would be to try and wrap the Node streams to add additional functionality on top of them, but that does not seem great, either (it actually seems worse).

---

At the end of the day, this is an edge case bug that I don't think many people will run into. Until someone can think of a good solution (if one exists), documenting it as a Known Difference will probably be fine for the time being.

For the record, the use cases I have for cloning Responses only make sense in the context of browser environments (which are also buggy with this particular behavior). I'm using node-fetch for the tests so that I don't need to spin up a browser to run my unit tests.

I'll keep thinking about solutions to this. I'll post an update here if I can think of a solution.

In the meantime, would you like me to open a PR to add a note about this in the [Known Differences](https://github.com/bitinn/node-fetch/blob/c0950b7b9f0720cc9a0915968d5585d87286fba1/LIMITS.md) doc?

Also, thanks for all of your help here @bitinn and @TimothyGu ! 👌

**Comment by bitinn** [comment]
@jmeas yep, PR welcomed to document this difference. I would add the part where node stream doesn't have concept of "disturbed". See https://fetch.spec.whatwg.org/#concept-readablestream-disturbed

**Comment by bitinn** [comment]
Closing this as the different is documented and we will wait until web stream is incorporated into nodejs core to fix this properly.

see: https://github.com/nodejs/whatwg-stream

**Comment by jamesplease** [comment]
Update on this issue: some browsers now throw TypeErrors if you try to create a Response with a body that has already been read. Running the same snippet from the opening comment in this issue in latest Chrome/Firefox:

![image](https://user-images.githubusercontent.com/2322305/69302223-c59fb200-0bcd-11ea-89af-bd633985637b.png)

Safari doesn't throw an error, but I trust Firefox/Chrome's behavior more.

I don't see this behavior described in the spec, but I might not be reading the spec right. Assuming this behavior if accurate, then the problem described here isn't real and doesn't need to be revisited.
