### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by romariolopezc** [bitinn/node-fetch#400]
I had a bug: `fetch is not a function`

I was using this:
```js 
const fetch = require('node-fetch');
```
And now that I changed to this:
```js
import fetch from 'node-fetch';
```
And now is working. This is supposed to be for Node, using `const require`, but doesn't work that way

**Comment by jkantr** [comment]
`const fetch = require('node-fetch');` is the only way you should currently be using this package in node (unless you're bundling your server side application, which tends to be uncommon.

Also, `import` currently does not work in node without an experimental flag (which is, well, experimental). So it confuses me that it would work for you..

Can you tell us a little more about your environment, node version, and runtime config env vars / flags? I use this package daily and have never experienced this.

**Comment by TimothyGu** [comment]
What module system are you using that allows you to use `import fetch from 'node-fetch'`? I.e., webpack, Babel, or `node --experimental-modules`?

**Comment by romariolopezc** [comment]
I solved this by using `const fetch = require('node=fetch').default;`
