### ISSUE TITLE
Invalid multi-headers handling on v2

### ISSUE THREAD

**Issue by diegocr** [bitinn/node-fetch#403]
Quoting the changelog as per commit https://github.com/bitinn/node-fetch/commit/a345c398b30d2bccf54abc9c45071dece69a7bba#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR39

> Major: remove `headers.getAll()`; make `get()` return all headers delimited by commas (per spec)

and the upgrade guide, as per commit https://github.com/bitinn/node-fetch/commit/e9db8695232fa502557e0e710c4a02a52d50bc01#diff-4d348e5b5894a12987ac0fec3edfadddR35

```
// `get()` now returns **all** headers, joined by a comma, instead of only the
// first one. Its original behavior can be emulated using
// `get().split(',')[0]`.
```

I may be missing something, but i think that's plain **wrong**... what if the headers does contains commas ?!

E.g. Set-Cookie headers:

> Set-Cookie: PHPSESSID=foo; path=/, eid=rd5a88; expires=Sat, 19-Feb-2028 23:39:06 GMT

@TimothyGu thoughts? :)

Thanks.

**Comment by bitinn** [comment]
Take a look at #251, `set-cookie` is one of a kind thus need special handling outside of Fetch Spec :)

**Comment by diegocr** [comment]
Whoops! Thanks @bitinn, actually i did found the issue while using the `fetch-cookie` package and thought on reporting it here, but i'll rather do it next on their repo due their bogus usage, thanks again.
