### ISSUE TITLE
`timeout` raises a 503, should it not be a 504 or 408?

### ISSUE THREAD

**Issue by cggaurav** [bitinn/node-fetch#404]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408

**Comment by cggaurav** [comment]
The other issue here is that even if its a `ENOUTFOUND`, ie ```fetchrequest to http://112233.com failed, reason: getaddrinfo ENOTFOUND ...```, the promise is not rejected but waits till timeout seconds for an example POST request.

**Comment by cggaurav** [comment]
I am on `"version": "1.7.1"`

**Comment by bitinn** [comment]
@cggaurav you want to use v2. also `network timeout` will be rejected, not resolved, if you get a resolved result, it's not a timeout. https://github.com/bitinn/node-fetch/blob/44c67b11a36f83d2c9e0cf1671043f2a87c058f9/test/test.js#L638-L647
