### ISSUE TITLE
Fetch promise never completes due to swallowed RangeError 

### ISSUE THREAD

**Issue by jmrog** [bitinn/node-fetch#414]
I'm in a scenario where the following happens:

1. I make a request to a particular API using node-fetch, telling the server to do some processing and stream back results as JSON as they become ready.
2. The API responds successfully and begins streaming back data.
3. There is much more data coming back than I expected, so I tell the API (via another HTTP request) to stop the processing.
4. The server complies (stops processing), and closes the initial stream.
5. Because the stream has closed, [the `end` event is emitted on `body`](https://github.com/bitinn/node-fetch/blob/fb86ab34a6e6f00bfae5fd8cbebda9af4a0f412f/src/body.js#L254).
6. While handling the `end` event, node-fetch tries to create a new `ArrayBuffer` from the data that has streamed in so far, but the amount of data is too large, and a `RangeError` exception is thrown.
7. [node-fetch does _not_ `reject` with the error in the `end` event handler](https://github.com/bitinn/node-fetch/blob/fb86ab34a6e6f00bfae5fd8cbebda9af4a0f412f/src/body.js#L260), so the error is effectively lost, and the `Promise` that I received from node-fetch when I made the initial request is never resolved or rejected. The result is that the initial request continues to wait for the `Promise` to complete in some way, and (as a result) my UI currently shows the request as continuously ongoing.

Issue #203 is _somewhat_ similar to this, though not identical. What I'd like to happen here is for node-fetch to `reject` with the error, [as it does for other streaming errors](https://github.com/bitinn/node-fetch/blob/fb86ab34a6e6f00bfae5fd8cbebda9af4a0f412f/src/body.js#L246), so that the `Promise` completes and my UI can update as expected. Is there any reason for that not to happen? If it sounds reasonable, I can submit a simple PR for this.

**Comment by bitinn** [comment]
> While handling the end event, node-fetch tries to create a new ArrayBuffer from the data that has streamed in so far, but the amount of data is too large, and a RangeError exception is thrown.

This definitely sounds like we should handle. So `Buffer.concat(accum)` is throwing the `RangeError` right? If so, I think that's worth catching.

I think you need a bit ingenuity to write a test for [buffer.constants.MAX_LENGTH](https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_length) (the cause of RangeError I suspect), perhaps you can set it before the test and restore it after.

**Comment by jmrog** [comment]
> This definitely sounds like something we should handle. So Buffer.concat(accum) is throwing the RangeError right?

Yep, that's right.

> I think you need a bit ingenuity to write a test for buffer.constants.MAX_LENGTH (the cause of RangeError I suspect), perhaps you can set it before the test and restore it after.

Yes, I believe that is the cause of the RangeError. I'll play around with that a bit and see what comes up. Thanks!
