### ISSUE TITLE
Requests with a `Host` header cause an exception in Node v6

### ISSUE THREAD

**Issue by nathanielw** [bitinn/node-fetch#416]
Hiya, I haven't had a chance to dig into this much, so let me know if any more details are needed. Essentially using node-fetch to send a request with a `Host` header causes an exception in Node v6.13.1:

```javascript
const fetch = require('node-fetch');

fetch('https://api.github.com/users/github', {
		headers: { 'Host': 'api.github.com' }
	});
```

gives:
```
(node:96772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: hostHeader.startsWith is not a function
```

It looks like this was introduced by the changes in 1592ca1 (the above code works fine in the parent commit).

**Comment by gr2m** [comment]
@TimothyGu that was your change, any idea? Here is a runkit snippet showing that the regression was introduced in 2.1.0: https://runkit.com/gr2m/5a9f1c073815fc0012281973

**Comment by TimothyGu** [comment]
I'll look at this. I do have to say though, I would partially consider it a bug in Node.js that no better diagnostic is emitted.

**Comment by Palisand** [comment]
This is happening for me as well (Node v9.2).
