### ISSUE TITLE
weback - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by mitra42** [bitinn/node-fetch#421]
I'm running into this common webpack issue. 

The code of one of our libraries is calling 
```
const nodefetch = require('node-fetch-npm');
```
webpack complains 
```
WARNING in ../node_modules/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
 @ ../node_modules/encoding/lib/iconv-loader.js
 @ ../node_modules/encoding/lib/encoding.js
 @ ../node_modules/node-fetch-npm/src/body.js
 @ ../node_modules/node-fetch-npm/src/index.js
 @ ../js/TransportHTTP.js
 @ ./archive.js
```
Is there a known fix for this ?

**Comment by bitinn** [comment]
ping @zkat 

https://github.com/npm/node-fetch-npm

It's not our code.

**Comment by mitra42** [comment]
Thanks - will try a switch back to yours, I've confirmed that I don't get the webpack error with `node-fetch`, maybe I'll figure out why we picked node-fetch-npm despite being client-side when I run some tests.

**Comment by bitinn** [comment]
Mind you, this is not a browser-side polyfill at all. If you try to bundle it for browser we simply export `window.fetch`, so you can't use any `node-fetch` only features (they only work on server-side).

**Comment by mitra42** [comment]
That's what I want actually - browser style fetch on both browser and node.
