### ISSUE TITLE
Is keep-alive the default behavior?

### ISSUE THREAD

**Issue by zhaoyao91** [bitinn/node-fetch#423]
I thought in server context, keep-alive should be the default option to reuse existing connection. Will I gain this benefit if I use node-fetch?

**Comment by bitinn** [comment]
Not by default, but you can easily create a http agent with keep alive flag enabled to achieve what you want:

https://github.com/bitinn/node-fetch/blob/780598ad72d7205aa5616be2215692785270eda3/test/test.js#L1306-L1318

**Comment by taoqf** [comment]
@bitinn Does this work?
```
const res = await fetch(url, {
	headers: {
		'connection': 'keep-alive',
		'content-type': 'application/json'
	}
});
```

**Comment by skheria** [comment]
> @bitinn Will this work?
> 
> ```
> const res = await fetch(url, {
> 	headers: {
> 		'connection': 'keep-alive',
> 		'content-type': 'application/json'
> 	}
> });
> ```

As per the example provided by @bitinn & also my understanding, you need supply this config in http agent used in the request. Only supplying header won't help.
