### ISSUE TITLE
Too big of a Travis CI matrix

### ISSUE THREAD

**Issue by TimothyGu** [bitinn/node-fetch#431]
[Right now](https://travis-ci.org/bitinn/node-fetch/builds/357188888), our Travis CI matrix consists of 16 different configurations. It's quite huge and scary.

![screenshot from 2018-03-22 19-59-52](https://user-images.githubusercontent.com/1538624/37809262-b20f6d9e-2e0b-11e8-8d77-322a859be14e.png)

I don't think it's time for us to reduce the supported version range of Node.js, so that leaves the form-data and encoding options. Two questions:

1. Do we still want to continue supporting and testing on form-data v1.x? If not, then we can drop `FORMDATA_VERSION=1.0.0` editions. This will shave 50% off the build jobs.
2. Can we merge the `ENCODING=yes` and non-`encoding` runs into one? E.g., run the tests without `encoding` first, then `npm i encoding`, then run the tests again, all on one machine. This will also shave 50% off the number of build jobs.

/cc @bitinn

**Comment by bitinn** [comment]
I have been thinking about the same thing, I think it’s now safe to drop form-data 1.x from CI (can we specify we only support 2.x in package.json somehow? Or do we need to print a warning ourselves?)

As for the encoding package, I am for this move, just not sure how exactly this is done, not through Travis.yml?

(From my phone)

**Comment by TimothyGu** [comment]
> I think it’s now safe to drop form-data 1.x from CI

I'll mark this as on the milestone for node-fetch v3.x.

> As for the encoding package, I am for this move, just not sure how exactly this is done, not through Travis.yml?

It'll probably be through travis.yml. What I have in mind is:

```yaml
script:
  - npm run coverage
  - npm install encoding
  - npm run coverage
```

**Comment by bitinn** [comment]
Haven’t tried calling coverage twice before, but if it works, sure!

(From my phone)

**Comment by Richienb** [comment]
The matrix was reduced to 3 jobs in 3.x
