### ISSUE TITLE
POST redirection

### ISSUE THREAD

**Issue by killfill** [bitinn/node-fetch#44]
Hi there!

Im doing a fetch to an URL with POST (a login), which will redirect to another url if the login is successfull.

When this happends, fetch will try to follow the new url with the POST method too.
Shouldnt it follow the URL with a GET?

like in here: https://github.com/bitinn/node-fetch/blob/master/index.js#L127
Adding options.method='GET' just before that line.

Thanks!

**Comment by bitinn** [comment]
Hmmm, your are right, somehow I didn't test for it.

PS: the spec says: If either actualResponse's status is 301 or 302 and request's method is `POST`, or actualResponse's status is 303, set request's method to `GET`.`

**Comment by bitinn** [comment]
Also it might need to drop body as well (not that you can't send GET request with a body, but it has no semantics meaning in a server context, some servers might act weird).

http://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by killfill** [comment]
Yup,

Im trying to actually get the cookie value after the login (POST request) is success.
Im afraid that as fetch would make the GET request right after it, i will still not be able to get the cookie value anyway :S

Maybe it would be nice to have a dontFollow config variable somewhere, to make fetch not follow the redirect, and and users could just read the response headers of the POST request. That would enable read the cookie value :)

But thats not the behaviour of the browser, as far as i know, node-fetch is trying to mimic it, right?

**Comment by bitinn** [comment]
Yeah, this is actually a limit from the Fetch Spec itself. See #8 item 2 and discussion on #23. I haven't thought of a good solution to this yet...

**Comment by killfill** [comment]
Thanks for the info!

Might be better to copy the options object into a new one and override there the method to GET, instead of making a raw options.method='GET', which will mutate the value. Users might not expect that :)

Thanks!

**Comment by bitinn** [comment]
The POST redirect to GET problem is fixed in v1.3.3 release.

We will track the redirect headers in #8, hopefully a solution soon.
