### ISSUE TITLE
Timeout does not work at all

### ISSUE THREAD

**Issue by tobob** [bitinn/node-fetch#440]
```
import fetch from 'node-fetch';

      fetch('https://www.google.com', {
        method: 'GET',
        options: { timeout: 1 },
        timeout: 1,
      })
        .then(res => console.log(res), err => console.log('err2', err))
```

Am I doing something wrong? That low timeout should return `err2` always, or not? 
it is always success

using ReactNative, but this should not be an issue
axios however works fine with timeout options

**Comment by jdat82** [comment]
Same here. Timeout is not triggered.

**Comment by jdat82** [comment]
Maybe I missed something nevertheless.

It is written : 

> // The following properties are node-fetch extensions
> follow: 20,         // maximum redirect count. 0 to not follow redirect
> timeout: 0,         // req/res timeout in ms, it resets on redirect. 0 to disable (OS limit applies)
> compress: true,     // support gzip/deflate content encoding. false to disable
> size: 0,            // maximum response body size in bytes. 0 to disable
> agent: null         // http(s).Agent instance, allows custom proxy, certificate etc.

What is concretely a "node-fetch extension"?  Is it an external npm package that need to be installed?

**Comment by bitinn** [comment]
`timeout` is commonly used when you write a web crawler or use public api, where you might want to terminate some long running requests. There were no abort mechanism in Fetch back then, and `timeout` was the common solution for other http library.

We got tests for `timeout` if you need some code reference:

https://github.com/bitinn/node-fetch/blob/master/test/test.js#L727-L750

But you can't set it to 1ms and expect it to work, node-fetch use nodejs' built-in `http` module, and `http` module need to assign sockets to a request first, for our timeout to work.

https://nodejs.org/api/http.html#http_event_socket
https://github.com/bitinn/node-fetch/blob/master/src/index.js#L55-L62
https://stackoverflow.com/questions/6214902/how-to-set-a-timeout-on-a-http-request-in-node

That said, OP was using React Native. I have no idea how React Native handle this internally, so you better ask on SO or their forum.

**Comment by gajus** [comment]
> We got tests for timeout if you need some code reference:

I am constantly detecting my scripts hanging on a connection for days even when the timeout is explicitly configured.

Mind you, this happens when connecting through proxy. If that changes anything.

**Comment by bitinn** [comment]
@gajus I recall someone mentioned that nodejs http module sometimes doesn't bubble the right events when the request got stuck. No concrete report so far. If you see any other network library doing extra work in this space, let us know.

It's kinda strange a stalled connection can last that long though (I would think OS will recycle the socket eventually), are you using anything weird settings with http agent or on the OS? are you using continuous object stream? Those are the less tested use cases.

**Comment by gajus** [comment]
Nothing unusual in the setup. Basic request using promises. When successful – returns response under a second.

I am going to test/ look into code of https://github.com/sindresorhus/got – it has different level timeouts (connect, socket, and request). Will see if I can replicate the same issue.

**Comment by bitinn** [comment]
For people in this thread, if `timeout` is somehow not what you want, node-fetch `v2.3.0` now supports `AbortSignal` which should be standard compliant, and should close the stream properly.

**Comment by dsimushkin** [comment]
In case anyone needs to preserve an error stack:
```typescript
import AbortController from "abort-controller";
import nodeFetch, { RequestInfo, RequestInit, Response } from "node-fetch";

const aborter = Symbol("request abort");

export function sleep(ms = 0): Promise<void> {
  return new Promise<void>((resolve) => {
    setTimeout(() => resolve(), ms);
  });
}

export async function fetch(
  resource: RequestInfo,
  options: RequestInit & { timeout: number }
): Promise<Response> {
  const { timeout, signal, ...requestOptions } = options;
  const controller = new AbortController();

  if (signal != null) {
    signal.addEventListener("abort", () => controller.abort());
  }

  const request = nodeFetch(resource, {
    ...requestOptions,
    signal: controller.signal,
  });

  if (timeout == null) {
    return request;
  }

  const timeoutPromise = sleep(timeout).then(() => aborter);
  const result = await Promise.race([timeoutPromise, request]);
  if (result instanceof Response) {
    return result;
  }

  controller.abort();
  return request;
}
```

A full description with reasoning can be found in my [stackoverflow answer](https://stackoverflow.com/questions/46946380/fetch-api-request-timeout/74846086#74846086)
