### ISSUE TITLE
__esModule is not getting set in the built output

### ISSUE THREAD

**Issue by bradleat** [bitinn/node-fetch#442]
Due to some particulars of how your project is built,
Object.defineProperty(exports, "__esModule", { value: true });
 is not getting set in the built output. exports is being overwritten with the variable fetch.

This create some problems with systems that inspect the __esModule property.

**Comment by bitinn** [comment]
I believe we are currently doing the right thing: where `lib/index.js`, the transpiled version, contains the `__esModule` property.

Do let us know if I am missing something :)

**Comment by bradleat** [comment]
However, this line

`module.exports = exports = fetch;` also gets set which overrides 
the previous line `Object.defineProperty(exports, '__esModule', { value: true });`
