### ISSUE TITLE
2 factor authentication using certificates?

### ISSUE THREAD

**Issue by Jakobud** [bitinn/node-fetch#443]
Is it possible to use 2-factor authentication using public/private certificates with this library? This library is used in some webdav client projects, and I'm working to get 2FA support in those.

Essentially, this article on using Curl to connect to a WebDAV drive using 2FA certificates describes the functionality:

https://www.qed42.com/blog/using-curl-webdav-two-factor-authentication

Is this possible with this library? If not, what would it take to make it happen?

**Comment by Jakobud** [comment]
Some more info about this, you can see that the `request.js` library has support for 2 factor auth using certs + passphrase here:

https://github.com/request/request#tlsssl-protocol

This is essentially what I'm trying to see if `node-fetch` would be able to support.

**Comment by bitinn** [comment]
Sorry for the late reply, you can definitely set many of these in a `http.Agent` instance and pass it to node-fetch, see options:

https://github.com/bitinn/node-fetch#options

And if you can do it in plain nodejs https and you can probably do it with node-fetch + http.Agent.

https://engineering.circle.com/https-authorized-certs-with-node-js-315e548354a2
