### ISSUE TITLE
Doesn't work with FormData using a Buffer

### ISSUE THREAD

**Issue by stringbeans** [bitinn/node-fetch#447]
I can't tell exactly where the error stems from, but here is what I'm doing...

```ts
file // this was extracted from multer and is using MemoryStorage

const form = new FormData()
form.append('file', file.buffer)
fetch(<url>, {
  method: 'POST',
  body: formData
})
```

at the endpoint that `fetch` is making the request to, i am using multer to parse the multipart form.

What im noticing is that at my latter endpoint, multer isnt able to recognize any files being uploaded. However, if in my code above, instead of using the `file.buffer` from multer, I change multer to use LocalStorage and use `createReadStream` and pass that in instead, then it works.

**Comment by bitinn** [comment]
We detect FormData body in very specific way, so it could be this is a new feature we haven’t support or somehow FormData isn’t taking that buffer.

You can take a look at our tests it should contain some FormData usage example.

(From my phone)

**Comment by jkantr** [comment]
I didn't see any reason this wouldn't work, so out of curiosity I wrote a test case:

``` javascript

	it.only('should allow POST request with form-data using buffers as body', function() {
		return Promise.resolve().then(() => {
			// readFileAsync is just promisified fs.readFile
			return readFileAsync(path.join(__dirname, 'dummy.txt'));
		}).then((dummyFile) => {
			const form = new FormData();
			form.append('my_field', dummyFile); // this is a buffer

			url = `${base}multipart`;
			opts = {
				method: 'POST'
				, body: form
			};

			return fetch(url, opts).then(res => {
				return res.json();
			}).then(res => {
				console.log(res.body);
				expect(res.method).to.equal('POST');
				expect(res.headers['content-type']).to.startWith('multipart/form-data;boundary=');
				expect(res.body).to.contain('my_field=i am a dummy');
			});
		});
	});
```

and the result

```
    √ should allow POST request with form-data using buffers as body (41ms)

  1 passing (146ms)
```

so you might want to look to another source of the issue... you are saying that `LocalStorage` (or is it DiskStorage?) works with `multer` but not `MemoryStorage` and a Buffer? Have you tried logging the `file.buffer` to make sure there's data?

**Comment by TimothyGu** [comment]
What package did you use for the `FormData` class? And what version?

**Comment by isnifer** [comment]
@TimothyGu https://www.npmjs.com/package/form-data

**Comment by cdaringe** [comment]
@isnifer, what was your solution?  it looks like the `FormData` construct is not part of the `node-fetch` TS types.  i may need to just expand the interface if this lib does indeed support binary streams
