### ISSUE TITLE
rejectUnauthorized option not recognized

### ISSUE THREAD

**Issue by raulggonzalez** [bitinn/node-fetch#451]
I'm passing `rejectUnauthorized` option due to I'm using a self-signed cert, but this isn't being had in mind.

**Comment by bitinn** [comment]
set it through `agent` option, check nodejs about self signed cert.

**Comment by raulggonzalez** [comment]
Thanks @bitinn... Finally, I've used the NODE_TLS_REJECT_UNAUTHORIZED variable.
