### ISSUE TITLE
[HELP] How does node-fetch support 'rejectUnauthorized' with https???

### ISSUE THREAD

**Issue by hong-boy** [bitinn/node-fetch#453]
In my biz, I need support https with my own cert ( which is signed by myself). But node-fetch throws 'self signed certificate' error
![image](https://user-images.githubusercontent.com/28519731/39804882-df805844-53a7-11e8-965f-1156e559e798.png)

I knew 'rejectUnauthorized' property could makes https ignore the error above. So my question is ```how to transfer 'rejectUnauthorized' into node-fetch??? ```

**Comment by bitinn** [comment]
A simple search in issues should give you the answer: use *agent* option to set your self signed cert.

(From my phone)

**Comment by hong-boy** [comment]
@bitinn great!
