### ISSUE TITLE
node-fetch somehow confused two connections

### ISSUE THREAD

**Issue by wmertens** [bitinn/node-fetch#454]
This is very weird and so far a one-off event.

Absolutely not sure what's happening here, except I am sure that it shouldn't be happening. My application connects to two different services, here renamed to service1 and otherservice.

```
FetchError: request to https://service1.com/rest/etc failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: service1.com.com. is not in the cert's altnames: DNS:*.otherservice.com"
    at ClientRequest.<anonymous> (/Users/wmertens/myproject/node_modules/.registry.npmjs.org/node-fetch/2.1.2/node_modules/node-fetch/lib/index.js:1393:11)
```

I encountered this on macOS 10.13.4, with Node v8.9.4 and node-fetch 2.1.2.

Can you think of anything that might cause this? It's the first time this happened AFAIK and normally everything works fine.

**Comment by gr2m** [comment]
Maybe combination of a racing condition and mutated state?

**Comment by bitinn** [comment]
I couldn't imagine why but probably look into your DNS setup.

**Comment by bitinn** [comment]
AFAIK, no caching on our part, underlying code is nodejs http and socket.

(From my phone)

**Comment by wmertens** [comment]
Ok, in that case I'll upgrade node and close this issue, maybe there's a problem with the dns layer in node
