### ISSUE TITLE
throws when a header with an undefined value is specified

### ISSUE THREAD

**Issue by willm** [bitinn/node-fetch#456]
If you run the following in node:

```javascript
const fetch = require('node-fetch');
const Headers = require('node-fetch/lib/headers');
let hed = new Headers();
hed.append('something', undefined);
fetch('https://github.com/', {
    method: 'get',
    headers: hed
}).then(r => r.text())
    .then(console.log);
```

You get the following exception:

 `TypeError: Cannot read property 'toString' of undefined
    at /Users/will.munn/code/api/download-api/node_modules/node-fetch/lib/headers.js:41:28
    at Array.forEach (<anonymous>)
    at new Headers (/Users/will.munn/code/api/download-api/node_modules/node-fetch/lib/headers.js:40:18)
    at new Request (/Users/will.munn/code/api/download-api/node_modules/node-fetch/lib/request.js:40:17)
    at /Users/will.munn/code/api/download-api/node_modules/node-fetch/index.js:52:17`

however if you run the same request with chrome's native fetch, it adds the request header `something: undefined`.

Is this a bug? Could come up with a PR to fix if so, just wanted to check first.

**Comment by TimothyGu** [comment]
> Is this a bug?

Yes, which was fixed in the latest version of node-fetch :wink:

**Comment by willm** [comment]
ah thanks, node-fetch is a dependency of another dependency so I guess I'll carry on hunting to isomorphic-fetch!

**Comment by TimothyGu** [comment]
We now recommend https://github.com/lquixada/cross-fetch, which is [maintained](https://github.com/lquixada/cross-fetch#why-not-isomorphic-fetch) more frequently.
