### ISSUE TITLE
Wrong Content-Length when uploading binary data

### ISSUE THREAD

**Issue by 0xC0DEBA5E** [bitinn/node-fetch#459]
When I'm uploading binary data from a Uint8Array using the POST-Method, more data is uploaded than is contained within the buffer. Instead of 2700000 Bytes there are 9199999 Bytes transfered. Maybe I'm doing something wrong, so here's an example:

```javascript
const fetch = require('node-fetch');

const sendPost = async (data, url) => {
    try {
        console.log(`byteLength of buffered data:`, data.byteLength);
        const response = await fetch(url,
            {
                method: 'POST', body: data,
                headers: {
                    'Content-Type': 'application/x-protobuf'
                }
            });
        console.log(`response`, response);
        return response;
    } catch (e) {
        console.error(e)
    }
};

const data = new Uint8Array(5);

for (let i = 0; i < 5; i++) {
    data[i] = i;
}

console.log(`byteLenght:`, data.byteLength);
sendPost(data, "http:/httpbin.org/post");
```

At the Server side I can see that the `Content-Length`-Header is set to 9 and node-fetch is trying to send this number of bytes to the server.

**Comment by jimmywarting** [comment]
it should work with Uint8Array also...

**Comment by 0xC0DEBA5E** [comment]
Yes, according to the [spec](https://fetch.spec.whatwg.org/#body-mixin) it should accept a `BufferSource` which is defined as `typedef (ArrayBufferView or ArrayBuffer) BufferSource;`.

 `ArrayBufferView` is a helper type that includes typed arrays like `Uint8Array` and therefore it should be supported.

**Comment by 0xC0DEBA5E** [comment]
OK, now I have localized the [line, where the Uint8Array is coerced to string.](https://github.com/bitinn/node-fetch/blob/fa6548ed316a3c512147a3bb4f4d6e986d738be6/src/body.js#L50)

Seems like `Buffer.isBuffer(body)` earlier on line 42 dosen't return true for Uint8Array and maybe we just need another check here to get this right.

**Comment by 0xC0DEBA5E** [comment]
OK, seems like NodeJS Buffers aren't the same as `TypedArray`, but one can convert `TypedArrays` to `Buffer` by using the .buffer property on the TypedArray object:

"It is possible to create a new Buffer that shares the same allocated memory as a TypedArray instance by using the TypeArray object's .buffer property" [NodeJS documentation](https://nodejs.org/api/buffer.html#buffer_buffers_and_typedarray).
