### ISSUE TITLE
Add ability to switch between "follow" and "manual" redirect conditionally

### ISSUE THREAD

**Issue by Visya** [bitinn/node-fetch#467]
Hi!

We have come around an edge case when we need to handle some redirects manually in a specific case and follow the redirects in all other cases.

It would be great to be able to specify `redirect` option as a function of response.

```
fetch(url, {
  redirect: (res) => {
    // Handle manually if X-Replace-Url is set
    return !res.headers.get('X-Replace-Url')
  }
}}
```

**Comment by gr2m** [comment]
The `redirect` option is not part of the Fetch Standard so it can’t be implemented as part of node-fetch I’m afraid. You’ll have to build the feature around `node-fetch`

**Comment by bitinn** [comment]
@Visya Fetch Spec already has a strict definition on how `redirect` flag is handled, so I am less inclined to add more behavior onto it.

Using 2 nested fetch with `redirect: manual` would be your best bet, the `Location` header would be a full url.

https://github.com/bitinn/node-fetch/blob/master/src/index.js#L88-L93

@gr2m Fetch Spec doesn't have a `redirect` option when `node-fetch` was first started, but it now has it, and I believe v2 is spec-compliant here.

https://fetch.spec.whatwg.org/#concept-request-redirect-mode

**Comment by Visya** [comment]
@bitinn Thanks for the reply.
I will close this then.
