### ISSUE TITLE
Add `.npmignore`

### ISSUE THREAD

**Issue by SimonSchick** [bitinn/node-fetch#470]
Please consider adding files such as: 

```
node_modules/node-fetch/.npmignore
node_modules/node-fetch/.travis.yml
node_modules/node-fetch/CHANGELOG.md
node_modules/node-fetch/ERROR-HANDLING.md
node_modules/node-fetch/LIMITS.md
node_modules/node-fetch/test/
node_modules/node-fetch/test/dummy.txt
node_modules/node-fetch/test/server.js
node_modules/node-fetch/test/test.js
```

to the ignore file.

**Comment by TimothyGu** [comment]
Hmm, I thought the `files` property in `package.json` should be enough? Apparently not then.

**Comment by gr2m** [comment]
I don’t see any of these files: https://unpkg.com/node-fetch@2.1.2/. I think the `"files"` property in package.json works as expected.

@SimonSchick did you see these files one of your projects? Did you maybe link node-fetch locally?

**Comment by SimonSchick** [comment]
Ah yes, seems like the package was installed multiple times in the tree, the affected version was 1.7.3
