### ISSUE TITLE
How i can get response HTML page ?

### ISSUE THREAD

**Issue by Xandr2410** [bitinn/node-fetch#471]
Hello guys, I use node-fetch and I make a request to the page of the site, namely I make an authorization request, everything is normally transferred, etc., but the response (on the network in the developer's console in the browser) is given in the form html and not json.
Here is part of my code when responding as json
```js
.then((res) => {
   console.log(res);
    console.log("___________________________________");
    console.log(res.text());
   return res.json();
})
   .then((json) => {
    console.log(json);
    console.log("___________________________________");
  })
```

How do I correctly organize the output of html to check the authorization was successful or there was an error
PS how to determine the error I realized, it is in one of the lines of html, but how to get it out?

**Comment by jimmywarting** [comment]
you should not call both `text()` and `json()`

get the response as text and it will work
```js
.then(res => res.text())
.then(text => {
  try {
    // parse it yourself
    JSON.stringify(text)
  } catch (e) {
    console.log(text)
  }
})
```

**Comment by Xandr2410** [comment]
http://joxi.ru/MAj35zBi4PM7ar

**Comment by TimothyGu** [comment]
So it doesn't seem like JSON is involved at all? Replace the `return res.json()` with `return res.text()`, and remove `console.log(res.text())` should work. Just like `res.json()`, `res.text()` returns a promise.
