### ISSUE TITLE
Error: only absolute urls are supported

### ISSUE THREAD

**Issue by lemoustachiste** [bitinn/node-fetch#481]
This happens when you are trying to get a relative path is `../../my/path/to/myfile.json`. This is supported in browsers (tested on Firefox, Chrome and Safari).

My issue is in testing, tests fail because of the above error, which is annoying because now I have a distinction between the browser and the node environment running the tests.

This is the stack trace beyond my code:
```
      at node_modules/node-fetch/index.js:54:10
      at new Fetch (node_modules/node-fetch/index.js:49:9)
      at Fetch (node_modules/node-fetch/index.js:37:10)
      at Object.<anonymous>.module.exports (node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
```

I have added a comment in `isomorphic-fetch` discussion: https://github.com/matthew-andrews/isomorphic-fetch/issues/76#issuecomment-402784514, but would like to attract attention on this use case here too.

**Comment by nenadjaja** [comment]
I am getting the same error when trying to run tests (using Enzyme and Ava): 
Rejected promise returned by test. Reason:

```
  Error {
    message: 'only absolute urls are supported',
  }

  node_modules/node-fetch/index.js:54:10
  new Fetch (node_modules/node-fetch/index.js:49:9)
  Fetch (node_modules/node-fetch/index.js:37:10)
  node_modules/fetch-ponyfill/fetch-node.js:18:12
  _callee$ (frontend/src/adapters/http.js:28:20)
  makeRequest (frontend/src/adapters/http.js:43:17)
  _callee2$ (frontend/src/adapters/http.js:54:20)
```

**Comment by jimmywarting** [comment]
The server don't have an origin so the default domain name is unknown. Therefore relative url won't work. Hence the error.

Supporting file:// protocol is also out of the question.

I would like to close this issue as relative to 
https://github.com/bitinn/node-fetch/issues/75

**Comment by TimothyGu** [comment]
Ditto. You may want to use `new URL(relativeURL, baseURL)` to resolve the URL before passing it to node-fetch.

**Comment by codevanaco** [comment]
maybe use `fetch('http://localhost:3000',...)` instead of `fetch('/someEndpoint', ...)`

**Comment by kopax** [comment]
I am also experiencing this error and the url is an absolute url.

I am within expo SDK36, how can I troubleshoot?

**Comment by avdaredevil** [comment]
@kopax I was having the same issue, it seems to be some issues with the types files. I fixed my issue which was that I was using it like:
```js
fetch({url, headers: {Authorization: `token ${process.GIT_TOKEN}`}})
```
instead of
```js
fetch(url, {headers: {Authorization: `token ${process.GIT_TOKEN}`}})
```

**Comment by shangan23** [comment]
Refer: https://stackoverflow.com/a/62512796/1929115

https://codeconqueror.com/blog/get-the-current-url-in-next-js

**Comment by ReubenMathew** [comment]
How would you fix this in nextjs when using getStaticPaths() and getStaticProps() ?

**Comment by PriimeTime** [comment]
> Refer: https://stackoverflow.com/a/62512796/1929115
> 
> https://codeconqueror.com/blog/get-the-current-url-in-next-js

that's for next.js only

**Comment by Monster880** [comment]
It looks like there's something wrong with the URL in the fetch method.
For me, it solved by changing url in the fetch method.
Pay attention to the correctness of the URL address.

**Comment by dork1** [comment]
@Monster880  How did you change the url it to make it work? I am having the same problem.

**Comment by jimmywarting** [comment]
@dork1 
```js
const baseURL = 'http://localhost'
fetch(new URL(url, baseURL))
```

**Comment by dork1** [comment]
Thanks @jimmywarting - could you advise what I might be missing? 

`function updateDisplayName() {
  const baseURL = 'http://localhost'; // 'http://localhost:8000';
  const url = process.env.AUTHO_POST_ENDPOINT;

  fetch(new URL(url, baseURL, {
    method: 'POST',
    headers: {authorization: 'Bearer ' + process.env.AUTHO_TOKEN},
    data: '{"user_metadata": {"displayName": "FooName"}',
  }))
      .then(function(response) {
        console.log('update', response.data);
      }).catch(function(error) {
        console.error(error);
      });
};`

**Comment by jimmywarting** [comment]
sry @dork1, i can't see anything wrong with your code.

**Comment by dork1** [comment]
OK, thanks good Sir, I'll keep trying, `response.data` keeps coming back as `undefined` but that's the only clue I can find.

**Comment by jimmywarting** [comment]
Oh... `response.data` is wrong use `response.body` instead if you intend to use the response stream and pipe it
if you need to get the response body then you need to call either
- `await response.json()`,
- `await response.text()` or
- `await response.arrayBuffer()`

there is nothing in the spec that defines `.data`

**Comment by jimmywarting** [comment]
same with request body: it should be 
```diff
    fetch(new URL(url, baseURL, {
        method: 'POST',
        headers: {authorization: 'Bearer ' + process.env.AUTHO_TOKEN},
-        data: '{"user_metadata": {"displayName": "FooName"}',
+        body: '{"user_metadata": {"displayName": "FooName"}',
    }))
```

**Comment by dork1** [comment]
@jimmywarting Thank you! I am now getting a response!

**Comment by hinstw** [comment]
Would be nice if the error message saying `only absolute urls are supported` would include the actual URL and spare a bit of headache for the users

**Comment by heatherKoo07** [comment]
Any idea why axios doesn't raise the same error in testing unlike node-fetch?

**Comment by urmzd** [comment]
@heatherKoo07 It's most likely due to the [default config](https://axios-http.com/docs/config_defaults) provided by axios.

**Comment by jimmywarting** [comment]
axios may run in browser where it has a known origin and where it uses xmlhttprequest that supports relative urls (or absolute without origin)

axios may also be configured to have a origin in node's as a default when instantiating a new axios function
