### ISSUE TITLE
node-fetch doesnt work on web workers

### ISSUE THREAD

**Issue by nahuely** [bitinn/node-fetch#485]
Hi Guys, i created a restful client using node-fetch, but when i try to import it in a web worker it doesnt work, because lib expect window to be defined, but as you know there is no window object inside web workers, you have to use self,
i think it would be very helpful to many people to be able to do this, cheers

**Comment by TimothyGu** [comment]
(I believe https://github.com/bitinn/node-fetch/blob/master/browser.js is being referred to here.)

Ah, the classic `self` vs. `window` issue. Let's go with `self` which should work for both.

**Comment by nahuely** [comment]
thanks for that guys, cheers.
You are great!!
