### ISSUE TITLE
Update dependencies for node-fetch v3.x

### ISSUE THREAD

**Issue by TimothyGu** [bitinn/node-fetch#489]
After #488 we will have two packages (nyc, whatwg-url) pinned to an older version due to the fact that the new version does not support Node.js v4.x, and another one (url-search-params) required only for Node.js v4.x as newer versions of Node.js support URLSearchParams. We should update the list of dependencies for node-fetch v3.x, which will drop compatibility for Node.js v4.x.

**Comment by bitinn** [comment]
Oh god, I guess it’s what we have to do, thx for working on this!

(From my phone)

**Comment by TimothyGu** [comment]
@realityking It’s been backported to v6.x (see https://github.com/nodejs/node/pull/17365)… the docs just need to be updated to reflect that

**Comment by jimmywarting** [comment]
Are we going to remove the dependencies and simply just use the builtin?

```js
import { URL, URLSearchParams } from 'url'
```

**Comment by Richienb** [comment]
The dependencies are updated in 3.x
