### ISSUE TITLE
How to convert a cURL command with the GET and data-urlencode params to node-fetch

### ISSUE THREAD

**Issue by grassland-curing-cfa** [bitinn/node-fetch#492]
I would like to convert the following working cUrl command to javascript using node-fetch in a Node web app.
`
curl -X GET -H "X-Parse-Application-Id: APPLICATION_ID" -H "X-Parse-REST-API-Key: restAPIKey" -G --data-urlencode "count=1" --data-urlencode "limit=0" http://localhost:1337/parse/classes/GCUR_LOCATION`

Where can the data-urlencode sections go into the javascript?

```js
fetch('http://localhost:1337/parse/classes/GCUR_LOCATION', { method: 'GET', headers: {
  'X-Parse-Application-Id': 'APPLICATION_ID',
  'X-Parse-REST-API-Key': 'restAPIKey'
}});
```

**Comment by jimmywarting** [comment]
```js
const query = new URLSearchParams({
  count: 1,
  limit: 0  
})

fetch('http://localhost:1337/parse/classes/GCUR_LOCATION?'+ query, { headers: {
  'X-Parse-Application-Id': 'APPLICATION_ID',
  'X-Parse-REST-API-Key': 'restAPIKey'
}})
```

or simply put inline 

fetch(`http://localhost:1337/parse/classes/GCUR_LOCATION?count=1&limit=1`, { headers: {
  'X-Parse-Application-Id': 'APPLICATION_ID',
  'X-Parse-REST-API-Key': 'restAPIKey'
}})
