### ISSUE TITLE
Getting all headers in 2018

### ISSUE THREAD

**Issue by dandv** [bitinn/node-fetch#495]
I've read the README, #156 and #251, and am still unsure what the recommended way is to get all headers.

* `.getAll()` has been deprecated
* `.get()` throws the toLowerCase error mentioned in #156 
* `.entries()` is [not a function](https://github.com/bitinn/node-fetch/issues/156#issuecomment-242535914)
* `.raw()` is an [internal workaround object](https://github.com/bitinn/node-fetch/issues/156#issuecomment-242628473)

**Comment by TimothyGu** [comment]
> * `.getAll()` has been deprecated

In fact it no longer exists in the latest release.

> * `.get()` throws the toLowerCase error mentioned in #156 

It no longer does (the issue is from two years ago).

> * `.entries()` is [not a function](https://github.com/bitinn/node-fetch/issues/156#issuecomment-242535914)

Ditto.

> * `.raw()` is an [internal workaround object](https://github.com/bitinn/node-fetch/issues/156#issuecomment-242628473)

This is still true.

----

See https://runkit.com/timothygu/iterating-through-headers for some more examples.

**Comment by TimothyGu** [comment]
Also, the way you would use a `Headers` object provided by our module is identical to how you would use it in the browser.

**Comment by klesun** [comment]
I will be digging further, but it seems that none of the methods mentioned in the article works for me for some reason:
```
console.log('ololo headers', fetchRs.headers);
for (const [name, value] of fetchRs.headers) {
   rs.setHeader(name, value);
   console.log('ololo header', {name, value});
}
console.log('ololo done iterating');
```
Outputs:
```
ololo headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    connection: [ 'keep-alive' ],
    'content-length': [ '17' ],
    'content-security-policy': [
      "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';"
    ],
    'content-type': [ 'application/json' ],
    date: [ 'Sat, 07 Nov 2020 11:50:01 GMT' ],
    huj: [ 'sosi' ],
    'referrer-policy': [ 'same-origin' ],
    'set-cookie': [ 'SID=94pUbwgQpZJ/htO33sTDkyET4lLnwIrP; HttpOnly; path=/' ],
    'x-content-type-options': [ 'nosniff' ],
    'x-xss-protection': [ '1; mode=block' ]
  }
}
ololo done iterating
```

**Comment by klesun** [comment]
I found out that `headers` iterator is empty when I require this lib through `ts-node` =/

Will file a repo with minimal test case
