### ISSUE TITLE
Joining headers with a comma is a bad choice

### ISSUE THREAD

**Issue by baldurh** [bitinn/node-fetch#497]
The headers themselves can contain a comma eg. the `'set-cookie'` header: `'AREO=123456789; Expires=Sat, 28 Jul 2018 11:50:47 GMT; Path=/; Domain=.foo.net'`.

So splitting as suggested in the upgrade guide will not work at all. We ended up doing `headers.raw()["set-cookie"]` which returns an array.

**Comment by jimmywarting** [comment]
unfortunately this is how the spec is
more here: https://github.com/bitinn/node-fetch/issues/251

**Comment by jimmywarting** [comment]
closing as dup
