### ISSUE TITLE
POST in fetch and Postman tool has different reponse

### ISSUE THREAD

**Issue by vinodskitster1** [bitinn/node-fetch#500]
fetch() api gives different response compared to postman during POST method.
return fetch(`${_host}${urlPrefix}${uri}`, options).then(res => res.json())
  .catch(error => console.log('error', error))
  .then(response => console.log('success', response));

Above code gives the actual response as in Postman.

fetch(`${_host}${urlPrefix}${uri}`, options).then(res => res.json())
.then(ProcessStatus)
.then(response =>
response.json());
Above code gives a different response that does not have the actual message inside error node.

**Comment by zork-el** [comment]
Maybe you should see the error handling middleware of your node app. It would be more useful if you could post the varying response, as it wold become easier to pinpoint the error or typo in your code.

**Comment by bitinn** [comment]
Besides showing actual code and result, give https://httpbin.org/ a try when you need to test something.
