### ISSUE TITLE
The requested module does not provide an export named 'PassThrough'

### ISSUE THREAD

**Issue by pizza-r0b** [bitinn/node-fetch#502]
Calling fetch gives me the following error
```
node_modules/node-fetch/lib/index.mjs:1
import Stream, { PassThrough } from 'stream';
                 ^^^^^^^^^^^
SyntaxError: The requested module does not provide an export named 'PassThrough'
```

**Comment by KevinTCoughlin** [comment]
Experiencing this also.. thought it worked the other day

**Comment by bitinn** [comment]
We need more info to troubleshoot this, as I cannot reproduce this on my Mac.

**Comment by joakimsandstromfinnair** [comment]
I experienced the same issue when upgrading node-fetch from 2.1.2 to 2.2.0 - rolled back the version.

**Comment by bitinn** [comment]
Hey @TimothyGu, you are the cross-platform guy, please give us a hand? :)

**Comment by ebidel** [comment]
@bitinn I haven't dug into the core issue, but I can confirm 2.1.2 works on App Engine Node JS and 2.2.0 results in the error above. FWIW, the runtime is Node 8 on GAE.

**Comment by jaydenseric** [comment]
[The published ESM in `lib/index.mjs`](https://unpkg.com/node-fetch@2.2.0/lib/index.mjs) contains this line:

```js
import Stream, { PassThrough } from 'stream'
```

Turns out, `PassThrough` is not a named export of `stream` in Node.js v8, but it is in v10:

```js
// test.mjs
import { PassThrough } from 'stream'
```

```
node --experimental-modules test
```

In Node.js v8.12.0:

```
$ node --experimental-modules test
(node:32448) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: The requested module does not provide an export named 'PassThrough'
    at ModuleJob._instantiate (internal/loader/ModuleJob.js:85:17)
    at <anonymous>
```

In Node.js v10.11.0:

```
$ node --experimental-modules test
(node:32605) ExperimentalWarning: The ESM module loader is experimental.
```

**Comment by bitinn** [comment]
Good to know, I don’t exactly know how it got in there but would welcome a fix PR!

(From my phone)

**Comment by jaydenseric** [comment]
Ok, narrowed it down even further… `PassThrough` became a named export of `stream` in Node.js v10.2.0, so this bug will occur for anyone using `--exerimental-modules` with Node.js  versions < 10.2.0.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-05-23-version-1020-current-mylesborins

**Comment by jaydenseric** [comment]
It looks like this works in all the versions:

```js
import Stream from 'stream'
console.log(Stream.PassThrough)
```

**Comment by jaydenseric** [comment]
The plot thickens. node-fetch@2.2.0 imports without emitting an error in Node.js v8.5, but not in v8.12.0. My guess is that it still has the problem, it's just not as smart about emitting an error.

**Comment by bitinn** [comment]
So it looks like a recent change in import style caused this issue. However since I haven’t been looking at this codebase: does changing it affects transpiler?

Neither way I feel we should replace all instances of such import or find a workaround as it’s breaking in too many production environments.

(From my phone)

**Comment by bitinn** [comment]
[2.2.1](https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md#v221) release should address this issue, if not, please let me know :)

**Comment by akaSybe** [comment]
thanks, new version works for me

**Comment by joakimsandstromfinnair** [comment]
also works for me, thx for the fix.
