### ISSUE TITLE
Unnecessary slice calculation?

### ISSUE THREAD

**Issue by jimmywarting** [bitinn/node-fetch#505]
All this calculation where you figure out what to slice:

https://github.com/bitinn/node-fetch/blob/09ef40e8a883344a38f8ebddc58ff0ac129a415c/src/blob.js#L51-L76

Isn't that what `Buffer.slice(start, end)` also does for for you?

can't you just do: 

```js
slice(...args) {
   // ...
   const slicedBuffer = buffer.slice(...args); 
   // ...
}
```

**Comment by TimothyGu** [comment]
Possibly, but the [File API spec](https://w3c.github.io/FileAPI/) specified this, which we reproduce faithfully.
