### ISSUE TITLE
Easily allow family option for requests

### ISSUE THREAD

**Issue by joshuacullen** [bitinn/node-fetch#507]
Hi,

We're using node-fetch extensively throughout our projects. We've identified an issue where we have intermittent request failures. 

After debugging the issue we're pretty sure that node is sometimes trying to use IPv6 to do DNS lookups and failing as described in this issue https://github.com/nodejs/node/issues/7931.

I would like to allow the family option to be passed to the request directly rather than needing to use the http/https agent. Passing the option directly will allow our code to be a lot simpler. We wouldn't need to differentiate between http/https requests etc. 

How do you feel about the following approach? 

https://github.com/bitinn/node-fetch/pull/506

**Comment by bitinn** [comment]
I agree we would like to offer a solution to this for quite a while, I think Timothy could help.

There were PRs and I think they were stuck for some reasons.

(From my phone)

**Comment by joshuacullenlux** [comment]
Awesome. 

@bitinn Want to give Timothy a bump?

**Comment by bitinn** [comment]
Hi @joshuacullen, I have decided against adding more non-spec compliant options.

But for future readers: check this test case, passing `lookup` through Agent should allow you to configure DNS lookup somehow. It's not in the nodejs doc, I am asking nodejs team to add them.

- https://github.com/bitinn/node-fetch/blob/master/test/test.js#L1597-L1608
- https://github.com/nodejs/node/issues/24098
