### ISSUE TITLE
No way to set separate timeouts for network timeout and body timeout

### ISSUE THREAD

**Issue by aakula-edmunds** [bitinn/node-fetch#508]
No way to set separate timeouts for network timeout and body timeout. Body timeout uses the value set for network timeout.

**Comment by aakula-edmunds** [comment]
Pull request to add  separate timeouts for network timeout and body timeout instead of using the same value - https://github.com/bitinn/node-fetch/pull/496

**Comment by jimmywarting** [comment]
Closing this since `AbortController` will be able to solve this problem and the fack that timeout is not an spec standard
