### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by rakesh-makluri** [bitinn/node-fetch#509]
Getting the following error on 'npm install'

118 verbose stack TypeError: Only absolute URLs are supported
118 verbose stack     at getNodeRequestOptions (C:\Users\pramati\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\request.js:131:11)
118 verbose stack     at fetch.Promise (C:\Users\pramati\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:44:21)
118 verbose stack     at new Promise (<anonymous>)
118 verbose stack     at fetch (C:\Users\pramati\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:41:10)
118 verbose stack     at retry (C:\Users\pramati\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\index.js:332:14)
118 verbose stack     at C:\Users\pramati\AppData\Roaming\npm\node_modules\npm\node_modules\promise-retry\index.js:29:24
118 verbose stack     at <anonymous>
119 verbose cwd G:\React\shiva\connect-nav\example
120 verbose Windows_NT 10.0.16299
121 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pramati\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
122 verbose node v8.11.3
123 verbose npm  v6.4.0
124 error Only absolute URLs are supported
125 verbose exit [ 1, true ]

**Comment by TimothyGu** [comment]
This seems to be a bug in the program that called node-fetch rather than in node-fetch itself. In this case it might be npm.
