### ISSUE TITLE
Use case for res.arrayBuffer

### ISSUE THREAD

**Issue by MrOrz** [bitinn/node-fetch#51]
I'm currently working on a `.docx` file parser that should work on both browsers and NodeJS environments.

https://github.com/MrOrz/hacktabl-parser/blob/fcfc7626c533b0434d11215e4c3c1d305990db26/src/fetchDoc.js

`.docx` files are a bunch of XML files archived in a zip format, thus I am using JSZip to extract XML files from `.docx`. Since `node-fetch` does not support `res.arrayBuffer()`, I cannot use `isomorphic-fetch` to grab `.docx` files on NodeJS.

If `node-fetch` were to support `res.arrayBuffer()`, the large if-statement that differentiates server & browser behavior could be gone. `http` and `https` library don't have to be required in the code anymore, leading us to a smaller bundle when the code is compiled using webpack for use in browsers.

**Comment by bitinn** [comment]
Does this help? res.body would be a stream of buffers. http://stackoverflow.com/questions/8609289/convert-a-binary-nodejs-buffer-to-javascript-arraybuffer

**Comment by MrOrz** [comment]
@bitinn Thanks for the timely reply, it is very informative!

I refactored my code using `res.body`, which eliminates the large if-statement and the dependency on `http` / `https` library.

https://github.com/MrOrz/hacktabl-parser/blob/b7dfd402f30b6ff96515993b52ce2a38fa99a29f/src/fetchDoc.js#L53

 However, I found a good resemblance between my code and the `Response.prototype._decode`'s implementation. Maybe I can come up with a little pull request to support `res.arrayBuffer` by just tweaking a few lines of code?

**Comment by bitinn** [comment]
PR welcomed, though maybe you have other options? Does JSZip support stream (basically buffers) on node.js? if so you can problem just pipe res.body to JSZip.

ref: https://github.com/Stuk/jszip/pull/195

**Comment by konsumer** [comment]
`res.arrayBuffer` would also be helpful to me, in this case:

```js
var fs = require('fs')
var fetch = require('node-fetch')

function getZip (url, outfile) {
  return new Promise(function (resolve, reject) {
    fetch(url)
      .then(function (res) {
        return res.arrayBuffer()
      })
      .then(function (buffer) {
        fs.writeFile(outfile, buffer, function (err) {
          if (err) return reject(err)
          return resolve(outfile)
        })
      })
      .catch(reject)
  })
}
```
or should I be downloading binary data some other way?

**Comment by bitinn** [comment]
@konsumer it would be better to use stream (res.body is a transform stream), and pipe it to fs.createWriteStream.

ref: https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

**Comment by konsumer** [comment]
@bitinn: cool. thanks!

**Comment by mbrevda** [comment]
continuing from #11, my use case for body as a buffer (which I'm not sure if thats the same as arrayBuffer) would be crypto:

```js
var p = fetch('http://some/' + image.location)
    .then(function(res){
        var hash = crypto.createHash('sha1').update(res.body).digest('hex')
        fs.createWriteStream(hash).write(res.body)
    })
```

@bitinn I don't follow the SO links. Additionally, it seems like a lot of code would be needed in each instance, vs adding a res.buffer() method as @MrOrz has done. Is that something that can be added?

**Comment by bitinn** [comment]
@mbrevda 

1. It's no more code than what you wrote, and once you understand what `pipe` do, it's not difficult at all.

http://stackoverflow.com/questions/18658612/obtaining-the-hash-of-a-file-using-the-stream-capabilities-of-crypto-module-ie

```
var hash = crypto.createHash('sha1');
res.body.pipe(hash);
```

2. arrayBuffer is not the same as Buffer. and node.js Buffer is not in the fetch spec, so we don't intend to add it.

**Comment by mbrevda** [comment]
Now I understand, thanks! This approach still requires a callback on res.body end, so having a `res.buffer()` helper might still be nice.

**Comment by bitinn** [comment]
FYI, if you need to buffer a small response on Node.js, you can now use `res.buffer()` since v1.6.0; for anything we still strongly recommend using `res.body` as stream. That's the proper and performant way on Node.js.

**Comment by bottleofwater** [comment]
The main issue is that as long as node-fetch doesn't support this, it breaks isomorphic-fetch (since we no longer can assume that the implementation is conform to the standard). Cf https://github.com/matthew-andrews/isomorphic-fetch/issues/96.

**Comment by jimmywarting** [comment]
hmm, maybe think arrayBuffer should exist there as well, even if it means it's a degression from Buffer or stream. The point is that is should be easy to make unit-test and have it work just the same on the browser as well on the server. Should be just as easily to browserify the hole package and have it work in the browser as is without the need for Nodes Buffer

**Comment by TimothyGu** [comment]
I've implemented `arrayBuffer()` for the upcoming v2 in #183.

**Comment by bitinn** [comment]
@TimothyGu just saying, I tend to close cases on release instead of on merge :)

**Comment by konsumer** [comment]
This is awesome!

**Comment by jonaskello** [comment]
Just chiming in here, had a case today where arrayBuffer() would be really useful. Looking forward to 2.0 and hoping that isomorphic-fetch will then also update to 2.0.
