### ISSUE TITLE
Is it possible to pass multiple agents as options?

### ISSUE THREAD

**Issue by bbarani** [bitinn/node-fetch#513]
I am planning to use https proxy agent and keep alive agent and pass it as node-fetch option but was wondering if its ok to pass multiple agents?

agent1=https proxy agent;
agent2=keep alive agent
agents = [agent1, agent2]
 
let options = {
        method: 'POST',
        **agent:agents**
        body: JSON.stringify(body),
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        }
    };

fetch(url, options)

**Comment by bitinn** [comment]
sorry, not possible at the moment, the underlying `http.request` doesn't support multiple agent neither.
