### ISSUE TITLE
response.headers.get('set-cookie') returns string instead of array.

### ISSUE THREAD

**Issue by bergkvist** [bitinn/node-fetch#514]
## This is only a problem when receiving multiple cookies.
*(node-fetch v2.2.0, node v10.5.0)*

Notice below, that 'set-cookie' is an array. Multiple cookies are being set at the same time.
```
> res.headers

Headers {
        [Symbol(map)]:
         { 'x-powered-by': [ 'Express' ],
           'access-control-allow-origin': [ '*' ],
           'set-cookie':
            [ 'session_id=5b959a8774b94f21b3155075; Max-Age=7776000; Path=/; Expires=Sat, 08 Dec 2018 22:11:19 GMT',
              'session_accesstoken=lL4MsO31e1oM7K1kLa_MP; Max-Age=7776000; Path=/; Expires=Sat, 08 Dec 2018 22:11:19 GMT; HttpOnly' ],
           'content-type': [ 'application/json; charset=utf-8' ],
           'content-length': [ '114' ],
           etag: [ 'W/"72-82b1TkWDU2TgdyGanXhgzORXO7k"' ],
           date: [ 'Sun, 09 Sep 2018 22:11:19 GMT' ],
           connection: [ 'close' ] } }
```

When trying to access the array, it is simply turned into a comma-separated string.
```
> res.headers.get('set-cookie')

session_id=5b959a8774b94f21b3155075; Max-Age=7776000; Path=/; Expires=Sat, 08 Dec 2018 22:11:19 GMT, session_accesstoken=lL4MsO31e1oM7K1kLa_MP; Max-Age=7776000; Path=/; Expires=Sat, 08 Dec 2018 22:11:19 GMT; HttpOnly
```

```
> typeof res.headers.get('set-cookie')

string
```

This wouldn't be as annoying if it wasn't for the fact that the 'Expires' property uses a comma. 

Basically, turning the 'Set-Cookie'-header into a 'Cookie'-header for use in later requests becomes a nightmare. None of the cookie-parsing libraries I've tested have been able to parse the cookies correctly either.

**Comment by jimmywarting** [comment]
I agree it sucks but i'm closing this as a dup of #251
