### ISSUE TITLE
User Agent Version

### ISSUE THREAD

**Issue by cristobal** [bitinn/node-fetch#522]
The header `User-Agent` if it's not set, it will default to:

```js
headers.set('User-Agent', 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)')
```

Should it not default to use the current module version?  e.g.:

```js
const pkg = require('package.json')
...
headers.set('User-Agent', `node-fetch/${pkg.version} (+https://github.com/bitinn/node-fetch)`)
```

Or some automated injection of the version?

**Comment by cristobal** [comment]
Ok I see, seems the 🚢 has sailed then.
Most browser clients standardise on the current browser version, would have expected the node-fetch would have done the same.

We now ship our own `user-agent`  header which works fine, but when diving into source we would have expected that it used the version of the node module. That's why i reported it.

Anyways thanks for the fast reply, just closing this issue then 👍

**Comment by jimmywarting** [comment]
Guess it would maybe be interesting to have the version reflect the version in package.json. 
But then again what are the con/pros?

Con:
Servers need to make special handling to figure out that 
`node-fetch/1.0 (+https://github.com/bitinn/node-fetch)` is the same module as
`node-fetch/2.0 (+https://github.com/bitinn/node-fetch)`

If the exact version is sent it leaves information away that you might not want to share.
I have vittnes Wordpress attacks that sends out `X-Powered-By` version and hackers would take on them cuz they know a security flaw in version `x < y`

If they know that NodeJS or node-fetch had a bug in memory handling they could respond with something that would be bad. 

like the [Unicode of Death](https://www.cultofmac.com/324043/apple-confirms-imessage-bug-is-crashing-iphones/) for iMessage for iPhones :P

Pro: 
Can't think of something...

Fingerprinting? Dynamic User Agent

**Comment by jimmywarting** [comment]
I don't care much...
