### ISSUE TITLE
Disable SSL verification

### ISSUE THREAD

**Issue by allancmm** [bitinn/node-fetch#524]
How to disable SSL verification? I have the following code:

    let formBody = [];

    var dataLogin = {
      'username': 'myUser',
      'password': 'myPassword'
    };

    for (var p in dataLogin) {
      var encodedKey = encodeURIComponent(p);
      var encodedValue = encodeURIComponent(dataLogin[p]);
      formBody.push(encodedKey + "=" + encodedValue);
    }

    formBody = formBody.join("&");   
    
    const url = 'https://externalloginapi.com';
    return fetch(url, {
       method: 'POST',
       headers: {
         'Content-Type': 'application/x-www-form-urlencoded',
         'Content-Length': formBody.length         
       },     
       body: formBody
    })

When I run the code I get the following error: 

{"message":"request to https://externalloginapi.com failed, reason: write EPROTO 7316:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:openssl\\ssl\\statem\\statem_clnt.c:1472:\n","type":"system","errno":"EPROTO","code":"EPROTO"}

P.S: I'm able to request successfully the above API from PostMan

**Comment by bitinn** [comment]
depends:

- self-signed cert? pass in a custom https.agent
- just want to ignore cert error and don't care about security? NODE_TLS_REJECT_UNAUTHORIZED

but you should figure out what that error mean, it's from nodejs core and at least worth investigating the cause (likely a server config problem).
