### ISSUE TITLE
Update options.timeout implementation

### ISSUE THREAD

**Issue by montmanu** [bitinn/node-fetch#536]
Would the project be open to a change in how the timeout logic is implemented?

Specifically, there seem to be many cases where the node-fetch timeout callback executes after [a socket is assigned](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_event_socket), but before a connection is fully established, leading to the request being aborted prior to any connection / transfer.

We think it is a reasonable interpretation of the [description for this option](https://github.com/bitinn/node-fetch#options):

> req/res timeout in ms

to expect that the timer would start once a request has been sent, and end upon any of the following:

1. a response having been received
1. an application / transport layer error having occurred
1. the timer having expired

Aside from exposing a reference to the underlying `ClientRequest` instance, we believe that replacing:

https://github.com/bitinn/node-fetch/blob/745a27c38953129ce81f162b23c3d24f4a4d18f3/src/index.js#L55-L62

with a change along the lines of the following: 

```javascript
if (request.timeout) {
  req.once('timeout', () => {
    reject(new FetchError(`network timeout at: ${request.url}`, 'request-timeout'));
    finalize();
  });
}
```

would more closely align with the description of the `timeout` option and better serve most non-browser use cases.

We'd be happy to send a patch if the project is open to the change.

Thanks!

**Comment by jimmywarting** [comment]
I would rather want AbortController to be implemented. then you can abort the request anytime you want

**Comment by montmanu** [comment]
I don't disagree.. is support for that in progress? fwiw, here is the set of changes we'd propose if the project was open to it

https://github.com/bitinn/node-fetch/compare/master...montmanu:issues/536

**Comment by jimmywarting** [comment]
#478 #437

if you like to help you can test or review those PR

**Comment by bitinn** [comment]
Hi @montmanu, can you elaborate on this?

> Specifically, there seem to be many cases where the node-fetch timeout callback executes after a socket is assigned, but before a connection is fully established, leading to the request being aborted prior to any connection / transfer.

Like a slow DNS resolution that delay the request? I consider it a part of `timeout`, but I can see why you might see differently.

We are closed to getting AbortSignal support done, see #539, even though it doesn't expose underlying client request, but you might find it more flexible.

**Comment by montmanu** [comment]
hi @bitinn thanks. yeah, we're in the process of instrumenting what we can to determine where the bottleneck is, but slow DNS resolution would be my best guess. Could also be slow TLS negotiation.. really could be any point along the chain prior to the request headers being flushed. We'll follow #539 . 

Thanks again!
