### ISSUE TITLE
fetch is incompatible with the GlobalFetch['fetch'] type

### ISSUE THREAD

**Issue by grantwwu** [bitinn/node-fetch#543]
```
import fetch from "node-fetch";

let f: GlobalFetch["fetch"] = fetch;
```
This fails with error message:
```
Type '(url: string | Request, init?: RequestInit) => Promise<Response>' is not assignable to type '(input: RequestInfo, init?: RequestInit) => Promise<Response>'.
  Types of parameters 'url' and 'input' are incompatible.
    Type 'RequestInfo' is not assignable to type 'string | Request'.
      Type 'Request' is not assignable to type 'string | Request'.
        Type 'Request' is not assignable to type 'import("/Users/grant.wu/petuum/api-gateway/node_modules/@types/node-fetch/index").Request'.
          Property 'context' is missing in type 'Request'.
```
I'm using typescript 3.1.1 and node-fetch 2.2.0.

https://github.com/apollographql/apollo-link/issues/513 this causes problems with code that assumes that `GlobalFetch['fetch']` is a good type to represent a generic "fetcher".

Do you have any suggestions for how to proceed?

**Comment by bitinn** [comment]
Sorry, I haven't used TypeScript much, but there isn't much we can do, given #359?

**Comment by bitinn** [comment]
I saw `apollo-env` now has a workaround that wrap `node-fetch` into a fetch with compatible type, I think it's the right approach, so I am closing this.

**Comment by cdaringe** [comment]
hmm. i still don't see the solution.

@grantwwu - did you find a working recipe?
@bitinn - have a URL handy?

**Comment by bitinn** [comment]
@cdaringe perhaps best to ask this on `apollo-env` repo?

Also in v3 we are adding our own TypeScript definition, so hopefully we can provide updates better in the future. (v3 is not released yet, so can't solve your problem right now, but keep an eye on it).

https://github.com/bitinn/node-fetch/tree/3.x/types

**Comment by grantwwu** [comment]
@cdaringe Nope, didn't have an alternative to what you came up with in https://github.com/apollographql/apollo-link/issues/513#issuecomment-548219023

**Comment by badsyntax** [comment]
Sorry to comment on an old issue, but i'm working around this issue by overriding node-fetch types with:

```ts
// node-fetch.d.ts
declare module 'node-fetch' {
  export default WindowOrWorkerGlobalScope['fetch'];
}
```
