### ISSUE TITLE
Global namespace

### ISSUE THREAD

**Issue by graham-willis-druid** [bitinn/node-fetch#546]
This module appears to place the following functions into the global namespace which causes errors with some code-quality tools.

fetch, Response, Headers, Request

**Comment by bitinn** [comment]
No we don’t, give us code example and errors.

(From my phone)

**Comment by graham-willis-druid** [comment]
My mistake. Its actually isomorphic-fetch which is apparently doing this by design. This is happening via another dependency airbrake-js.

**Comment by bitinn** [comment]
Cheers, closing this then.
