### ISSUE TITLE
Inconsistent response when comparing with postman

### ISSUE THREAD

**Issue by lethe0690** [bitinn/node-fetch#556]
Hi, I am using node-fetch to communicate with some vendors endpoints which including a payment solution and a third-party service.

I noticed some bugs recently and after debugging, it seems the requests do not comes back with proper response, and on another side, the vendor claim that there is no issue on their side and I have validated that the same call can be processed correctly with Postman without issue.

I am using pretty basic call with node-fetch.

example code like
```ts
return fetch('someURL', {
  'someHttpMethod',
  headers: {
    'Content-Type': 'application/json',
    AccountKey: 'somevalue'
  },
  requestBody
})
.then((res: responseType) => res.json())
.then((response: responseType) => response);
} catch (err) {
  throw err;
}
```

I did not change the code and the request only start failing recently. the version of node-fetch I am using is 1.7.3.

I am wondering if anyone has some insights on this

**Comment by jimmywarting** [comment]
Try making a `Request` and make a examination. Compare the request method/body/headers that are being sent

```js
const req = new fetch.Request('someurl', {
  method: someHttpMethod,
  headers: {
    'Content-Type': 'application/json',
    AccountKey: 'somevalue'
  },
  body: requestBody
})

console.log(req.method, [...req.headers])

fetch(req)
  .then(res => res.json())
  .then(response => response)
```

Try also if you can get a reasonable error message from the response you get back, normally if you get some error status code it don't always return a json response, so try logging the text

```js
if (res.ok) ? res.json() : res.text().then(console.log)
```
