### ISSUE TITLE
Strange error messagee on some failed calls 

### ISSUE THREAD

**Issue by designalchemy** [bitinn/node-fetch#559]
```
2018-12-09T03:01:51.811Z - error: [fetcher] Error
at /var/app/current/node_modules/node-fetch/lib/body.js:48:31
at process._tickCallback (internal/process/next_tick.js:103:7)
```

Keep getting this error message, the code we use is :

```
const fetch = require('node-fetch')
const log = require('../common/logger')('fetcher')

const fetchData = endPoint => async url => {
    try {
        const data = await fetch(`${api}/${endPoint}/${url}`, { headers })
        const json = await data.json()

        if (json.status !== 200) {
            log.warn(`Problem with: ${url}`)
            log.warn(json)
        }
        return _.get(json, 'data') || {}
    } catch (e) {
        log.error(e)
        return {}
    }
}
```

Any ideas ?

**Comment by bitinn** [comment]
Don't know, one thing for sure, the error is from nodejs core.

It's highly unlikely we throw an Error without providing you with more context, but `fetcher` sounds like someone else is wrapping `node-fetch`, you should probably find them and show them your full code and errors instead.

**Comment by designalchemy** [comment]
`fetcher` is just a wrapper on the error handling, nothing else is touching node-fetch

the above function i posted is called directly from a cron job script which gets data and puts it into a database, line 48 in the body.js is :

```		
return Body.Promise.reject(new FetchError('invalid json response body at ' + self.url + ' reason: ' + err.message, 'invalid-json'));
```

I have seen this error before in the logs but presume my try catch would error out a good message?
