### ISSUE TITLE
Encountered error "Error: no window object present" when prerendering

### ISSUE THREAD

**Issue by ywen** [bitinn/node-fetch#56]
Hi,

I use `node-fetch` in a reacts + rails project. I use https://github.com/shakacode/react_on_rails to glue between reactjs and  Rails. Everything works fine except when I do server side rendering it complains the error "Encountered error "Error: no window object present" when prerendering". I know this error is caused by the module because when I not load it the error disappears.

I am willing to work a PR, just need some directions. Thanks!

**Comment by bitinn** [comment]
I would bet that node-fetch is not the cause for your problem, mostly because *no window object present* suggest you are trying to include some package that's designed for client-side browser, where `window` is global.

**Comment by ywen** [comment]
You are correct on that node-fetch doesn't have any reference to `window` whatsoever. However, by not importing node-fetch, the server started to render. Maybe it is one of dependencies. I will investigate more once I have some free time and report back. Thank you!

**Comment by ywen** [comment]
It is actually http-browserify. Sorry about this

**Comment by pherris** [comment]
Hey @ywen how did you resolve this? Trying to use `isomorphic-fetch` on the server and getting the same error.

**Comment by ywen** [comment]
I gave up on server side rendering for now. Too much troubles each step of the way. But I wonder if you use commonjs `require` to require `isomorphic-fetch` just before calling it within a function body (instead of `import` it on the top of your files) it may help

**Comment by anaibol** [comment]
Same probilem here, I think http-browserify comes with webpack, not sure that is an issue related with isomorphic-webpack.

**Comment by anaibol** [comment]
Solved with "target: 'node'" in webpack config!
