### ISSUE TITLE
Help needed making fetch-mock compatible with jest

### ISSUE THREAD

**Issue by wheresrhys** [bitinn/node-fetch#566]
Hello.

I have a compatibility bug between fetch-mock and jest which, in summary, is because fetch-mock requires node-fetch, and jest tries to mock node-fetch using fetch-mock globally, so there is a vicious cycle. https://github.com/wheresrhys/fetch-mock/issues/407

It would probably solve the problem if node-fetch could provide a different path to require its helpers from. Are you open to a PR that puts Headers, Request, etc in a separate file to the main fetch implementation, and documents that they can be required from this path e.g. `node-fetch/lib/classes`?

**Comment by wheresrhys** [comment]
They do kinda. There's a `requestActual` method which is supposed to cater for this kind of issue, but I've filed a bug as it's not working within node_modules https://github.com/facebook/jest/issues/7620. No response yet, but I figure a solution will be slow coming, if at all; 476 open issues, and being able to `requestActual` from within node_modules might well be an edge case they don't care about. Whereas hopefully I can persuade you that making it possible to use one of node-fetch's main complementary test utilities with the fastest growing test framework is something worth fixing.

**Comment by bitinn** [comment]
@wheresrhys can you quickly outline what the changes might look like? because to me it sounds we are working around jest's problem (what I hear: `jest` mock dependency globally so we avoid the mocked api and use another require path?)

To add:

- why are fetch used globally in the first place? isomorphism?
- how does jest handle global modules? just mock them?

how about this doc?

https://github.com/facebook/jest/blob/master/docs/BypassingModuleMocks.md

**Comment by bitinn** [comment]
(I haven't used jest and I might not fully understand your users' problem)

**Comment by wheresrhys** [comment]
Sure, I'll do a PR of the proposed changes and also attempt to explain the problem in a gist. i've not come across that doc you shared before. I will analyse what it says for ideas. Where jest breaks down is in requiring a module as a dependency of the thing that mocks it. they have `requestActual` to get around it, but it's not working in the fetch-mock case for some reason (I guess because some features may deliberately be scoped to the application folder excluding node_modules)

**Comment by wheresrhys** [comment]
Hi, I found a workaround in the end http://www.wheresrhys.co.uk/fetch-mock/#usageusage-with-jest. Thanks for being open to discussion. Still waiting on a reply from jest 🙄
