### ISSUE TITLE
Error "certificate has expired"

### ISSUE THREAD

**Issue by MelyHC** [bitinn/node-fetch#568]
Al ejecutar un modulo que depende de node-fetch encontre este error de autenticación.

![errornodefetch](https://user-images.githubusercontent.com/39412664/51273944-ec80cc80-199b-11e9-95f8-f059463e6d1f.PNG)

**Comment by luispaulorsl** [comment]
This is not an issue.
The TLS/SSL certificate from the server you fetch has actually expired.
Use `.catch()` to handle the `Error`.

**Comment by MelyHC** [comment]
Gracias por la aclaración, lo había intentado colocando un catch pero sali ese error, pero al ver tu respuesta y volverlo a intentar salio, errores, que pasan

**Comment by PierBover** [comment]
I'm having this error in an Electron app using `node-fetch` and I know for certain the certificate has not expired. It's a Heroku app with a Let's Encrypt certificate that expires on `November 2, 2019`.

It only happens to some users so I'm guessing Node or `node-fetch` is not renewing the certificate...

Any idea what might be happening?

**Comment by Richienb** [comment]
@PierBover If you're using Electron, wouldn't the fetch API be natively supported in the browser window?

**Comment by PierBover** [comment]
@Richienb yes but in this case I need to do the request in the Node part since this involves working with the filestystem.

**Comment by PierBover** [comment]
Apparently the default config on the HTTPS agent is to cache 100 TLS sessions:

https://nodejs.org/api/https.html#https_class_https_agent

I will try passing a custom agent to node-fetch and see if that fixes it.

**Comment by promatik** [comment]
Hi @PierBover did you find out the issue?
I'm having that issue right now. Don't know why, the certificate was renews 2 weeks ago, and lasts for almost more 3 months.

And I'm having a `failed, reason: certificate has expired`.

**Comment by pigochu** [comment]
> Hi @PierBover did you find out the issue? I'm having that issue right now. Don't know why, the certificate was renews 2 weeks ago, and lasts for almost more 3 months.
> 
> And I'm having a `failed, reason: certificate has expired`.

@promatik 

Me , too , do u use let's encrypt ?

**Comment by vineet-hawal-better** [comment]
We were facing the same issue. Did the following as a quick fix:

```
const https = require("https");

// custom agent as global variable
const agent = new https.Agent({
  rejectUnauthorized: false,
});
// node-fetch request with custom agent
const response = await fetch(config.get('url'),
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: `data=${JSON.stringify(payload)}`,
  agent,
});
```

**Comment by promatik** [comment]
Hi @pigochu yes, I'm using let's encrypt.
I had to disable TLS validation in the mean time, until I find a proper solution 😕

This started to happen all of the sudden.

```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
```

Note this should **NOT** be done, this is a temporary fix.

**Comment by PierBover** [comment]
Sorry guys, I don't remember how I solved that and don't have access to the repo anymore.

**Comment by promatik** [comment]
For anyone arriving here with a `certificate has expired.` error, [Electron v15.1.0](https://github.com/electron/electron/releases/tag/v15.1.0) was just released, and it fixed my issue.
They merged [Fixed Let's Encrypt DST Root CA X3 certificate expiration](https://github.com/electron/electron/pull/31218).

Thank you Luca for the help ✌

**Comment by Trysystems** [comment]
The same error.

**Comment by Araxeus** [comment]
> For anyone arriving here with a `certificate has expired.` error, [Electron v15.1.0](https://github.com/electron/electron/releases/tag/v15.1.0) was just released, and it fixed my issue. They merged [Fixed Let's Encrypt DST Root CA X3 certificate expiration](https://github.com/electron/electron/pull/31218).
> 
> Thank you Luca for the help ✌

They backported the fix to 12.2.1, 13.5.1, 14.1.0, 15.1.0, and 16 beta

**Comment by dmdum** [comment]
> We were facing the same issue. Did the following as a quick fix:
> 
> ```
> const https = require("https");
> 
> // custom agent as global variable
> const agent = new https.Agent({
>   rejectUnauthorized: false,
> });
> // node-fetch request with custom agent
> const response = await fetch(config.get('url'),
>   method: 'POST',
>   headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
>   body: `data=${JSON.stringify(payload)}`,
>   agent,
> });
> ```

This worked for me. Should this be a temporary solution?

**Comment by kanishkab1** [comment]
> > We were facing the same issue. Did the following as a quick fix:
> > ```js
> > const https = require("https");
> > 
> > // custom agent as global variable
> > const agent = new https.Agent({
> >   rejectUnauthorized: false,
> > });
> > // node-fetch request with custom agent
> > const response = await fetch(config.get('url'),
> >   method: 'POST',
> >   headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
> >   body: `data=${JSON.stringify(payload)}`,
> >   agent,
> > });
> > ```
> 
> This worked for me. Should this be a temporary solution?

Can anyone tell me whether this solution is legal for a production level node.js application, or it is not applicable?

**Comment by ViliusZur** [comment]
@kanishkab1 It probably depends on what kind of product you are building. If it's something that is heavily regulated - there might be legal consequences. You should never use this in production anyways, as it leaves you vulnerable for man in the middle attacks.
