### ISSUE TITLE
Disable timeout

### ISSUE THREAD

**Issue by MystK** [bitinn/node-fetch#57]
I'm trying to make a call to an external API. The response could take up to a couple minutes, so I need to disable the timeout on fetch. Setting the timeout option to 0 does not disable it, and it timeouts after about 20 seconds. Am I missing something?

**Comment by bitinn** [comment]
It could be related to core nodejs or even your OS, we do make sure the timeout is passed to `http.request`, see test cases.

PS: timeout is `0` by default, so if you got that problem without passing a timeout value, try passing a large number? just note that it's `ms`.

**Comment by bitinn** [comment]
closing as it's likely an external factor
