### ISSUE TITLE
Server recieving 3 SYN packets when connection is rejected (Windows but no Linux)

### ISSUE THREAD

**Issue by estebanpanelli** [bitinn/node-fetch#577]
I'm securing a web application and I'm implementing the port knocking technique. The server side implementation is running and i'm making a small desktop application to make the "knocking" on the ports. 
I decided to do this with javascript and the fetch API currently available on most browsers and the **node-fetch** utility. 

To make a test, I opened a browser and wrote the following function:
```
(async function() {
    for ( port of [7000, 8000, 9000] ) { 
       await fetch("https://xx.xx.xx.xx:" + port)
           .catch(() => console.log("packet sent on port ", port)) 
           // I only catch because the server rejects the connection.
           // With the TCP SYN sent it's enough.
    }
})();
```

Running this on Chrome over Ubuntu 18.10 works exactly as expected, but when I copied this function to a Windows 7 computer, **the fetch behavior is somehow random:**

When looking on the server logs I realize that there are multiple connections for every port (not a constant) and sometimes the order changed.

The normal behavior running this on my Linux computer:
```
openWeb: Stage 1
openWeb: Stage 2
openWeb: Stage 3
```
When running on a Windows-based machine:
```
openWeb: Stage 1
openWeb: Stage 1
openWeb: Stage 1
openWeb: Stage 2
openWeb: Stage 1
openWeb: Stage 1
openWeb: Stage 1
closeWeb: Stage 1
closeWeb: Stage 2
closeWeb: Stage 1
closeWeb: Stage 1
```
The order of the connections is important and thus this is not working on the knock listener daemon.

Used Chrome Dev Tools to analize network activity and there is nothing strange in how connections are displayed there.

**Comment by bitinn** [comment]
because the underlying behavior is controlled by nodejs' native http/agent library, you might have better luck asking them.
