### ISSUE TITLE
Response.statusText should not default

### ISSUE THREAD

**Issue by jaydenseric** [bitinn/node-fetch#578]
At the moment, `node-fetch` behavior regarding `Response.statusText` differs from the `fetch` specification and native browser implementations.

If the server does not respond with status text, `node-fetch` incorrectly sets a default message derived from the HTTP status code. I think that happens here:

https://github.com/bitinn/node-fetch/blob/v2.3.0/src/response.js#L34

In fact, for HTTP/2 connections the `statusText` should always be blank because HTTP/2 doesn't support it:

https://fetch.spec.whatwg.org/#concept-response-status-message

Why does this matter, other than spec compliance? If your server side rendered app displays a `fetch` error `statusText` that technically should not exist, you end up with the client render (and `fetch`) producing a correct result that's different:

<img src="https://user-images.githubusercontent.com/1754873/52831515-080cfd80-3129-11e9-9d7f-9782b2276d41.gif" width="245" alt="node-fetch response statusText bug" />

**Comment by bitinn** [comment]
Either we missed this line or the spec has changed (see https://github.com/whatwg/fetch/issues/664), we would keep this behavior in v2 as people might depend on this behavior on server-side.

**Comment by Richienb** [comment]
Fixed in https://github.com/bitinn/node-fetch/commit/48a356c84a23cf5407c7f504e9af8536d602fc4e
