### ISSUE TITLE
Include type declarations

### ISSUE THREAD

**Issue by KamasamaK** [bitinn/node-fetch#579]
When using this package with TypeScript, you can use the [DefinitelyTyped types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node-fetch) but they are outdated. It does not include support for aborting added 3 months ago. To avoid issues like this, it would be nice if this package included the type declarations.

**Comment by bitinn** [comment]
If we ever rewrite node-fetch v3 in TypeScript we will consider this, for now, we are happy to out-source this to third party. (there are subtle signature difference between browser fetch and node-fetch which I see people came up with different solutions.)

**Comment by grumblerchester** [comment]
I suppose the OP hasn't asked for a 'rewriting' the library in TS. `.d.ts` file may be added to the source tree, updated manually and distributed with npm package. Having type declaration in project allows to have it in sync with source code.

**Comment by Richienb** [comment]
Types are now included in https://github.com/bitinn/node-fetch/commit/f947a9f5afcaf941c7f04817a0f7227b906a2f4a.
