### ISSUE TITLE
No error on socket shutdown

### ISSUE THREAD

**Issue by vuwuv** [bitinn/node-fetch#580]
There are no errors if socket is closed forcibly before response is complete (chunked encoding), just partial response body. Do we have any method to check if response is complete (last chunk had 0 bytes or response size matched Content-Length header value)?

**Comment by vuwuv** [comment]
I think actually it is a bug. Error is caught at "req.on('error'" handler and passed to the reject method of the already resolved promise, so it is just ignored. Instead reject should be called for the next call (response.text() or similar).

**Comment by bitinn** [comment]
Are you saying `error` is called after `end` event?
Are you reading from an infinite response?

Would need to see some code to illustrate the issue.

**Comment by vuwuv** [comment]
```
let response = await fetch('https://api.github.com/users/github');
let json = await response.json();
```

If the connection breaks on the second line (after response is successfully resolved), there is no way to catch this error. Could not fix it myself because that needs architecture review, so I've just switched to "request" library.
