### ISSUE TITLE
Curl corresponding request in node-fetch

### ISSUE THREAD

**Issue by Bradzer** [bitinn/node-fetch#583]
I tried many times to achieve this **curl** request in node-fetch without success : 
```
curl -X GET 
-u "<username>:<password>" 
--output hello_world.mp3 
"https://gateway-lon.watsonplatform.net/text-to-speech/api/v1/synthesize/?accept=audio/mpeg&text=hello" 
```

How to make it right ?

Note: I'm using **React Native**.

**Comment by bitinn** [comment]
You might want to read up on how `curl -u` works:

https://stackoverflow.com/questions/35442816/what-is-u-flag-on-curl-actually-doing

Do post your code next time. Also if it's a react-native issue you will have better luck asking react-native users as it could be an implementation details.
