### ISSUE TITLE
Can't use a custom Promise when explicitly constructing a Response

### ISSUE THREAD

**Issue by quasicomputational** [bitinn/node-fetch#585]
`node-fetch` claims to provide the means to use a custom promise implementation, and indeed does when you invoke its `fetch` function - however, if you explicitly construct a `Response` (i.e., `new Response`), its `.text()`, `.json()`, etc methods will use the global `Promise` constructor. It'd be really nice if there was a way to have a `Response` with a non-native promise implementation, for tests where you're faking timers and don't want to involve the native event loop at all.

**Comment by bitinn** [comment]
For production usage, see my reply in #586

For testing, I am wondering if packages like `sinon` allow you to stub the native promise. Otherwise give these packages a try:

https://github.com/taylorhakes/promise-mock
https://github.com/charleshansen/mock-promises

**Comment by quasicomputational** [comment]
The PR ended up redundant after I realised I needed to transpile everything because of `async`/`await` and to swap in Bluebird for `global.Promise` anyway.
