### ISSUE TITLE
How to run the source in the local?

### ISSUE THREAD

**Issue by hanzichi** [bitinn/node-fetch#587]
I wonder how I can run the [src](https://github.com/bitinn/node-fetch/tree/master/src) in the local?

For the source uses es modules, and I do not see the develop settings 

thanks

**Comment by bitinn** [comment]
I am not sure what you meant, but you want to run test, the commands are defined in the package.json

**Comment by hanzichi** [comment]
I wonder how to develop this module in the local using ES6 module

maybe shouldn't ask here, sorry for that
