### ISSUE TITLE
JSON.parse is not wrapped with try/catch

### ISSUE THREAD

**Issue by niftylettuce** [bitinn/node-fetch#59]
<https://github.com/bitinn/node-fetch/blob/master/lib/response.js#L45>

**Comment by niftylettuce** [comment]
I'm trying to fork/patch right now... will submit a PR if I figure it out

**Comment by niftylettuce** [comment]
Before:

```js
/**
 * Decode response as json
 *
 * @return  Promise
 */
Response.prototype.json = function() {

	return this._decode().then(function(text) {
		return JSON.parse(text);
	});

}
```

After:

```js
/**
 * Decode response as json
 *
 * @return  Promise
 */
Response.prototype.json = function() {

  var self = this;

	return this._decode().then(function(text) {
    try {
      var body = text && JSON.parse(text);
    } catch (e) {
      var err = e;
    } finally {
      if (err)
        return Response.Promise.reject(err);
      return body;
    }
	});

}
```

**Comment by TimothyGu** [comment]
With a proper Promises/A+ (or ES2015, which is based on the Promises/A+ spec) implementation (like the one used by this module), this is not needed. In fact, this pattern is exactly the kind Promises are trying to prevent.

Do you have a specific test case where the method is not working properly?

**Comment by TimothyGu** [comment]
Specs:

- [Promises/A+ 2.2.7.2](https://promisesaplus.com/#point-42)
- ECMAScript 2015:

  > **[25.4.1.3.2](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-resolve-functions) Promise Resolve Functions**
  > 8.&nbsp;Let then be Get(*resolution*, "then").
  > 9.&nbsp;If *then* is an abrupt completion, then
  > &nbsp;&nbsp;a.&nbsp;Return RejectPromise(*promise*, *then*.[[value]]).

  > **[25.4.2.1](http://www.ecma-international.org/ecma-262/6.0/#sec-promisereactionjob) PromiseReactionJob ( reaction, argument )**
  > 6.&nbsp;Else, let *handlerResult* be Call(*handler*, **undefined**, «*argument*»).
  > 7.&nbsp;If *handlerResult* is an abrupt completion, then
  > &nbsp;&nbsp;a.&nbsp;Let *status* be Call(*promiseCapability*.[[Reject]], **undefined**, «*handlerResult*.[[value]]»).
  > &nbsp;&nbsp;b.&nbsp;NextJob Completion(*status*).

**Comment by niftylettuce** [comment]
doesn't that spec say if abrupt completion then use reject promise?  isn't
throwing an error an abrupt completion?

**Comment by TimothyGu** [comment]
You are correct. But isn't "rejected promise" exactly what you are trying to do? At least in your implementation you are returning a rejected promise in the onFulfilled callback.

Or am I missing something?

**Comment by bitinn** [comment]
I don't see why we should catch JSON parser error manually, you should be able to handle it in `catch` clause. Maybe an example might help to explain your problem.

**Comment by niftylettuce** [comment]
See <https://github.com/niftylettuce/frisbee/blob/master/src/frisbee.js#L108-L114> for my implementation
