### ISSUE TITLE
Set own default UserAgent

### ISSUE THREAD

**Issue by kmathmann** [bitinn/node-fetch#591]
If i want to use my own user-agent on every request i am doing with node-fetch i currently have to add the header every time i use fetch.
In my opinion there should be a possibility to set a global default user-agent because the user-agent is always static for the lifetime of the application (or not?) and setting it every time is a unnecessary overhead.

Something like:
```javascript
fetch.setDefaultUserAgent('myApp/1.0.1 (MYSERVER; Linux) node-fetch');
```

**Comment by jimmywarting** [comment]
Have been lots of talk about making intercepters where you can always debug and or modify request & responses...

Would something like that be of any interest?

I would just imagen it could work something along the line of express `use` method or how the service worker dose it

kinda like: 
```js
// add agent header to all further request.
onfetch = (evt) => {
  evt.request.headers.set('agent', 'myApp/1.0.1 (MYSERVER; Linux) node-fetch')
}
``` 

it would be more generic and you can modify mostly anything that way.

**Comment by kmathmann** [comment]
Yeah, i like the middleware approach. Like you said, it would be generic and can be used for just any kind of global modification. At this time there is at least one use case apart from the userAgent i could use this for.

But i would say it's enough to give the possibility to modify the request object before the request is executed. Anything more complex, like modifying the response as it's possible in a service worker, is mainly request specific and could better be implemented with functions that are reused in the promise .then method.

``` javascript
fetch.use((req) => {
  req.headers.set('user-agent', 'myApp/1.0.1 (MYSERVER; Linux) node-fetch')
});

fetch('...')
   .then(validateResponseFunction) // validate or modify response
   .then(response=> console.log(response))
```

Are there already plans of implementing something like that?

**Comment by jimmywarting** [comment]
lots of talks but no active development
There are usecases too that involves modifying responses. and knowing when it's done so there are usecases for both

**Comment by kmathmann** [comment]
Okay, sounds like it's still a long way till it can be used.

Is there already an issue or a place where all the ideas and usecases which resulted from that talks are summed up and gets discussed?

**Comment by bitinn** [comment]
Over the years people asked for a `defaults` option where you can specify a set of options/headers that would be used on every fetch.

But I have resisted that idea mostly because in client-side you treat `fetch` like a function that returns a promise, that's it. So really you should be passing in your custom UA header every time.

But of course there are people who are tired of this and wrote their own addons, you might have a go at it (I haven't tried myself, but it's one of the top search result)

https://github.com/moll/js-fetch-defaults

**Comment by jimmywarting** [comment]
have a look at this issue #284

**Comment by kmathmann** [comment]
Okay i can understand that fetch should work like the client-side implementation and without these side effects. 
But the user agent gets already set by this package and i only want to change the default value of it to something meaningful, once at application startup.
At the client-side the browser does the same, he adds information about the browser, its version and the os to the user agent and the fetch implementation uses this user agent. There the user agent is a global value and it is added to every request.

**Comment by jimmywarting** [comment]
easies thing you could do right now is maybe to just build a own wrapper around node-fetch

```js
// fetch.js
const fetch = require('node-fetch')

module.exports = (url, args = {}) => {
  args.headers = args.headers || {}
  args.headers['user-agent'] = 'my own'
  return fetch(url, args)
}


// main.js
const fetch = require('./fetch.js')
fetch('https://httpbin.org/get')
```

**Comment by gugu** [comment]
@jimmywarting will it set default headers in this case?

**Comment by jimmywarting** [comment]
nope

**Comment by gugu** [comment]
Probably we did not understand each other. The documentation says, that if I don't provide `headers` parameter, it will be generated automatically and will include 'Accept', 'Content-Length', ... headers.

It is not clear, what happens if I provide 'User-Agent' header only. Will it still add `Accept`, `Content-Length`, ... headers or not. According to the source code, it will change `User-Agent` and still generate other headers (`Accept`, `Content-Length`). That's what I expected. Sorry for that misunderstanding

**Comment by nik-john** [comment]
@gugu What did you end up doing?

**Comment by etienne-martin** [comment]
I ended up creating a wrapper around node-fetch like @jimmywarting suggested and restricting direct imports of node-fetch throughout the codebase with eslint's `no-restricted-imports` rule.

```typescript
// eslint-disable-next-line no-restricted-imports
import nodeFetch, { RequestInfo, RequestInit } from "node-fetch";
import pkg from "../../package.json";

const USER_AGENT = `puddle/${pkg.version}`;

export const fetch = (url: RequestInfo, { headers, ...options }: RequestInit = {}) => {
  return nodeFetch(url, {
    headers: {
      "user-agent": USER_AGENT,
      ...headers,
    },
    ...options,
  });
};
```

```javascript
// .eslintrc.js

module.exports = {
  ...
  rules: {
    ...
    "no-restricted-imports": [
      "error",
      {
        // Prevent people from importing node-fetch directly
        paths: ["node-fetch"],
      },
    ],
  },
};

```

**Comment by ustun** [comment]
A crude alternative could be to make use of 'patch-package': https://github.com/ds300/patch-package
