### ISSUE TITLE
Fetch over outbound interface?

### ISSUE THREAD

**Issue by CoryGH** [bitinn/node-fetch#594]
Is it possible to control which outbound interface (IP) is being used by node-fetch?

**Comment by bitinn** [comment]
Pass in a custom `agent` should help:

https://nodejs.org/api/http.html#http_agent_getname_options

**Comment by CoryGH** [comment]
Do you have an example of how this would work with node-fetch?  Thus far I can't find anyone on how to initialize the agent for https requests, but some posts here on GitHub seem to suggest an instance of an agent isn't required if I feed fetch() something like { agent: { localAddres: 'LOCAL.IP.ADDRESS' } } - is this right or am I off-base for the fetch() options?

**Comment by bitinn** [comment]
You do need to create an `agent` instance, that's not avoidable.

But be very careful when you read the doc:

https://nodejs.org/api/http.html#http_new_agent_options

Especially this line: `options in socket.connect() are also supported.`

Which means you can pass `localAddress` option when you create an `agent` instance.

As for using it:

https://github.com/bitinn/node-fetch/blob/master/test/test.js#L1730

**Comment by CoryGH** [comment]
Thanks, with the test.js link it was pretty easy, I was worried I would have to deal with certificate management for it.
