### ISSUE TITLE
Textbook streams

### ISSUE THREAD

**Issue by ekkis** [bitinn/node-fetch#595]
the README contains the following code as an example of writing a file fetched:
```javascript
fetch('https://assets-cdn.github.com/images/modules/logos_page/Octocat.png')
    .then(res => {
        const dest = fs.createWriteStream('./octocat.png');
        res.body.pipe(dest);
    });
```
to which I would concatenate another `.then()` to use the file written to disk.  in reality it appears that my code runs before the file has finished writing to disk, so it occurs to me that the promise returned by the above code should take into consideration the issuance of the 'end' event on the stream.  maybe something like this:
```javascript
fetch(url).then(res => new Promise((resolve, reject) => {
                const dest = fs.createWriteStream(fn);
                res.body.pipe(dest);
                res.body.on('end', () => resolve());
                dest.on('error', reject);
            }));
```
but when I try to run this code it complains:
> TypeError: res.body.on is not a function
which makes sense given that `res.body` looks like this:
```javascript
{ pipe: [Function: pipe] }
```
which is to say, is not a stream at all

two questions:
1) how can I get access to the actual stream?
2) if I have no access to it, how can I know when the read stream has closed so I can resolve?

**p.s.**

and no, I can't get the stream from `.pipe()`, which returns undefined

**Comment by ekkis** [comment]
from a review of the node-fetch code I can see that resolution of the promise returned to the caller happens in the 'response' event instead of the 'end'

this seems like a good idea since the caller can start working on the stream straight away, but then the stream itself should be returned so the caller can watch the end.  I'm not sure I understand why I get the object I get from pipe because the return does something like this:
```javascript

let body = res.pipe(new PassThrough());
resolve(new Response(body, response_options))
```
so in my code I should be able to do `.on()` -- help?

**Comment by ekkis** [comment]
I figured it out.  the writeable stream will automatically close when the readable does.  so I can hook on that:
```javascript
fetch(url).then(res => new Promise((resolve, reject) => {
        const dest = fs.createWriteStream(fn);
        res.body.pipe(dest);
        dest.on('close', () => resolve());
        dest.on('error', reject);
}));
```

I'm going to leave this ticket open as a request for someone to update the README with the above code

**Comment by bitinn** [comment]
Yeah if you want to chain the promise further to read the file, you have to write more than `pipe`, our example isn't written to do that.

But this is really a problem with how to use promise chaining, there are enough material out there on that.
