### ISSUE TITLE
Definition as a global

### ISSUE THREAD

**Issue by niftylettuce** [bitinn/node-fetch#60]
Is it possible to set a flag `global: true` to have this `fetch` method exposed?

Reason being is that if we don't have something like this, then writing tests for this is a pain with mocha, and we have to define our own `global.fetch = require('fetch');`

**Comment by TimothyGu** [comment]
Why not just `var fetch = require('fetch')` in all mocha files? That's the standard way of doing testing in Node.js I feel.

Also there's no technical way to set a flag to make this global. Most modules that do pollute the global scope use a separate `require('fetch/global')` for this purpose.

**Comment by niftylettuce** [comment]
what does `require('fetch/global')` do???

**Comment by TimothyGu** [comment]
It does nothing – I'm just pointing out that if you want to implement addition to global scope it must be done in something like this. Right now there's no `fetch/global.js`.

**Comment by bitinn** [comment]
> Reason being is that if we don't have something like this, then writing tests for this is a pain with mocha...

I am not sure what you mean, we use mocha for our test cases as well, check it out.

**Comment by niftylettuce** [comment]
I was able to fix this with https://github.com/niftylettuce/frisbee/blob/master/src/frisbee.js#L11 and https://github.com/niftylettuce/frisbee/blob/master/test/unit/node.test.js#L2-L4
