### ISSUE TITLE
What does importing node-fetch would do?

### ISSUE THREAD

**Issue by MuhammadJamaluddin** [bitinn/node-fetch#602]
I am using `jest` & since it's running in the `node` environment, I had to use the `node-fetch` module to able to test my react components that do use the `fetch` API to send AJAX requests. I currently has 
`import 'node-fetch';` in my test file & it's working, but I am not sure why...

**Comment by FHGDev** [comment]
It imports the default exported function, "fetch"

**Comment by bitinn** [comment]
we recommend using:

`const fetch = require('node-fetch');`

you could also do:

`import fetch from 'node-fetch';`

But this is a question on nodejs usage, not node-fetch, please read:

https://nodejs.org/api/esm.html

**Comment by LiMengyang990726** [comment]
Hi I used `import fetch from 'node-fetch';`, but got this error. Anyone knows why?
![image](https://user-images.githubusercontent.com/34411863/73815122-ef0cc900-481f-11ea-8f37-a02ba706b954.png)
