### ISSUE TITLE
Error when used with fetch-mock: `Cannot read property \'on\' of undefined`

### ISSUE THREAD

**Issue by thehig** [bitinn/node-fetch#606]
I have recently been cleaning up dependencies in an application scaffolded with create-react-app. I recently deleted my package-lock.json and regenerated it, but when I do so I start getting an error in some of my tests: `Cannot read property \'on\' of undefined`

I captured a stack-trace:
```
TypeError: Cannot read property \'on\' of undefined
   at D:\\---SOME-LONG-PATH---\\frontend\\node_modules\\node-fetch\\lib\\body.js:122:13
   at new Promise (<anonymous>)
   at Response.Object.<anonymous>.Body._decode (D:\\---SOME-LONG-PATH---\\frontend\\node_modules\\node-fetch\\lib\\body.js:96:9)
   at Response.Object.<anonymous>.Body.text (D:\\---SOME-LONG-PATH---\\frontend\\node_modules\\node-fetch\\lib\\body.js:61:14)
   at Object.apply (D:\\---SOME-LONG-PATH---\\frontend\\node_modules\\fetch-mock\\src\\lib\\response-builder.js:157:28)
   at callApi (C:\\---SOME-LONG-PATH---\\shared\\api\\duck.js:65:41)
   at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Which led me to the [body.js](https://github.com/bitinn/node-fetch/blob/master/src/body.js) file where I could see statements like `body.on`. This suggested to me that something about the way I was creating the 'body' was causing an issue. I tracked down where the body was coming from in the failing tests, and it was being generated by [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/#api-mockingmock).

`fetchMock.getOnce('end:/dashboard/api/v1/dashboard', 200);`

Changing the `200` to a string makes the tests pass again. It looks to me like when using [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/#api-mockingmock) and specifying a "response-code-only" response, node-fetch craps itself with the error `Cannot read property \'on\' of undefined`

In attempting to log this bug in the node-fetch issues tracker, I came across [this](https://github.com/bitinn/node-fetch/issues/479) bug report, which implies/indicates that fetch-mock should be returning `null` and not `undefined`. 

My question is should this be fixed in node-fetch (by expanding/allowing for undefined as well as null body), or in fetch-mock (by trying to return null, rather than undefined in the appropriate function)

I can basically mark this issue as closed immediately because I found that by changing my fetch-mocks where I was responding with just a status code (eg: 200), to instead respond with `{ body: '', status: 200 }` resolved all my errors. However, after writing all this up, and seeing that there's an existing version of the bug tracked, I thought I'd post this to potentially help anyone else who got stuck on this same issue work around it

**Comment by bitinn** [comment]
`body.on` is how we consume the incoming stream, but the actual call shouldn't happen if you have mocked the Fetch API with `fetch-mock`.

I haven't used `fetch-mock` much myself, so I don't know if `fetch-mock` body is supposed to be used with `node-fetch`, I will give @wheresrhys a ping see if he has any comments to add.

closing for now.
