### ISSUE TITLE
new Response(blob).blob() should preserve `type` of the blob

### ISSUE THREAD

**Issue by Gozala** [bitinn/node-fetch#607]
From what I can tell `Response` ignores `type` field of the blob (assuming it's constructed with blob) causing that information to be lost.

I would expect implementation to match behavior in browsers which is:

```js
var blob = new Blob(['# Hi'], {type:"text/markdown"})

var response = new Response(blob)

response.headers.get('content-type') // "text/markdown"

(await response.blob()).type // "text/markdown"
```

**Comment by Gozala** [comment]
Some relevant test cases in gecko
https://github.com/mozilla/gecko-dev/blob/aaac9a77dd456360551dd764ffba4ca4899dcb56/testing/web-platform/tests/FileAPI/url/url-with-fetch.any.js

**Comment by bitinn** [comment]
we could have done better here by not default to empty string and instead fallback to blob's type:

https://github.com/bitinn/node-fetch/blob/master/src/body.js#L99

**Comment by Richienb** [comment]
Fixed in: https://github.com/bitinn/node-fetch/commit/46be1bd30b187da62e3ef3f2d7628d3c3b6b8e97#diff-f0c01727e5628483090afb5bc8c36be6R100
