### ISSUE TITLE
HTML string response when receiving error from the server but no JSON

### ISSUE THREAD

**Issue by sebRomeo** [bitinn/node-fetch#620]
Hi,
hope my question is relevant. 

When server is throwing a 4xx error, I cannot read response with `await res.json()` because it is an html string. I get the error `Unexpected token < in JSON at position 0`
However, when I try with postman it returns me a json object with my custom error message.

Here are my headers.
``` javascript
{ method: 'GET',
  headers:
   { Accept: 'application/json',
     'Content-Type': 'application/json',
}}
```

Tell me if you need more infos,

Thanks for your time and such a good lib :heart_eyes: 

Here is what I do for the moment:
``` javascript
let msg = await rawResponse.text();
msg = msg.split('ApplicationError: ')[1].split('<br>')[0];
```
:laughing:  :scream:

**Comment by bitinn** [comment]
- You should check `res`.
- JSON API shouldn't return non-JSON response, they need to fix it.
- In the meantime you should use `res.text()` when `response.ok` is false.
- If you can't trust this API to behave correctly, use `res.text()` and try parsing it yourself.
- You could post to StackOverflow if you need more help.

**Comment by jimmywarting** [comment]
- Also if it helps check for what kind of response type it gives

```js
let res = await rawResponse.text()
if (res.headers.get('content-type').includes('json')) {
  // then use
  json = await res.json()
}
```
