### ISSUE TITLE
Upgrade from 2.3.0 to 2.4.0 breaks pouchdb

### ISSUE THREAD

**Issue by pluby** [bitinn/node-fetch#627]
Upgrading from 2.3.0 to 2.4.0 breaks `pouchdb`, a breaking change has slipped in. This includes the latest version. Stack trace as follows:

```
TypeError: this is not a typed array.
    at Function.from (native)
    at Request.Body (/home/vagrant/src/node_modules/node-fetch/lib/index.js:205:17)
    at new Request (/home/vagrant/src/node_modules/node-fetch/lib/index.js:1176:8)
    at /home/vagrant/src/node_modules/node-fetch/lib/index.js:1376:19
    at fetch (/home/vagrant/src/node_modules/node-fetch/lib/index.js:1374:9)
    at /home/vagrant/src/node_modules/fetch-cookie/index.js:16:16
    at process._tickCallback (node.js:368:9)
```

Reverting to 2.3.0 resolves the problem.

**Comment by pluby** [comment]
Perhaps support for Node 4.x been dropped prior to version 3.x of node-fetch.

**Comment by bitinn** [comment]
> Significance of this is that node.js v4.2.6 is the version in the APT repository for Ubuntu Server LTS 16.04.

https://github.com/nodejs/Release#end-of-life-releases

Thx for the report, but even the latest Node v4 release has expired for over a year at this point. We will only test node-fetch 2.x to work with latest v4, not every version currently in used.

Best solution: add a node source to your APT and escape from official APT repository.

**Comment by pluby** [comment]
@bitinn Cheers for the response, I'm of the same mind, the official repositories are preferred but am getting tired of Canonical Inc's policy of holding back minor versions in it's LTS versions.
