### ISSUE TITLE
Unresolved function or method then()

### ISSUE THREAD

**Issue by jeroenpol** [bitinn/node-fetch#628]
Hi all, 

I can't get node-fetch to work. I started a new project and just imported node-fetch. When I try to run the sample function I get the following error:

![image](https://user-images.githubusercontent.com/6681199/56972475-59932900-6b6b-11e9-802c-685d1237756d.png)

Any help?

**Comment by bitinn** [comment]
Your IDE environment likely have some issues.

Try this if you need a quick test: https://npm.runkit.com/node-fetch
