### ISSUE TITLE
How to pass OAuth credentials?

### ISSUE THREAD

**Issue by jasonmendes** [bitinn/node-fetch#63]
Can this module be used with OAuth credentials? I figured out how to do Basic Auth, e.g.

```
fetch('https://awesome-service.com/api/v1/metrics.json', { headers: { Authorization: 'Basic xxxxxxxxxxxxxxxxxxxx' } })
```
But what is the API for OAuth authentication? Thanks :)

**Comment by bitinn** [comment]
Which step in OAuth are you referring to? As it's a 3-legged authorization.

But really you should use one of the existing OAuth module. `node-fetch` won't make the OAuth flow any easier.

**Comment by jasonmendes** [comment]
OK that makes sense. Do you recommend any module?

**Comment by bitinn** [comment]
I have used https://github.com/simov/grant before with good result, but you might want a generic one that's more popular:

https://github.com/search?l=JavaScript&o=desc&q=oauth&s=stars&type=Repositories&utf8=%E2%9C%93

closing this issue for now.
