### ISSUE TITLE
Publish our Blob implementation as a separate package

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#631]
With 2.5.0 release, we now support third-party Blob implementation.

There is just one problem: AFAIK, there isn' one in the wild.

Technically, node-blob could use our implementation easily, but if the author doesn't have time to maintain it, then we should publish our own.

https://github.com/shaneharris/node-blob

This should solve issues with the testing, mocking and isomorphic use case.

Also the Blob implementation needs better test coverage, which we currently don't do because we didn't intend to expose our own `Blob` implementation as a part of `node-fetch`.

**Comment by jimmywarting** [comment]
pinging @shaneharris to let him know

I also did a PR shaneharris/node-blob#1 to solve some things for the blob implementation

**Comment by bitinn** [comment]
Since there isn't any response, I have published our own version here:

https://github.com/bitinn/fetch-blob
https://www.npmjs.com/package/fetch-blob

Future fix and tests should move towards this package.
