### ISSUE TITLE
Support custom status text

### ISSUE THREAD

**Issue by moll** [bitinn/node-fetch#64]
Hey,

I see https://github.com/bitinn/node-fetch/blob/master/lib/response.js#L27 overwrites the status text returned by the server with the default set of Node. It'd be nice to preserve what the server responds as those might be more descriptive readable than the generic ones. Browsers' `fetch` does preserve it as far as I can tell.

Cheers

**Comment by bitinn** [comment]
That makes sense, maybe we can use the remote response by default and fallback to node's default (I just hope no one is depending on the status message being consistent).

In my experience, most API provide additional information through response body instead of status message though.

**Comment by moll** [comment]
Response body formats aren't standardized, but the status message is at least bound to be a text string. I've been introducing them more and more and it works great as an error title: e.g., instead of "412 Precondition Failed", send "412 Invalid CSRF Token".

Probably no need to add a fall back. I'd let Node's IncomingMessage handle edge cases and just use its `statusMessage`.

**Comment by bitinn** [comment]
> Response body formats aren't standardized

Yeah, but there should already be some sort of contract between developer and provider, that's how API work most of the time. Status message is more of a troubleshooting message (not really user friendly unless you design it to be).

**Comment by bitinn** [comment]
release v1.4.0 now prefers remote server status message instead of built-in messages
