### ISSUE TITLE
Plans to drop babel in v3

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#643]
I have been thinking about this lately, once we dropped node v4 and v6 support in 3.x release, do we still need `babel`?

My gut feeling is node v8+ are modern enough that all of our code are covered, so there is no value in transpiling (and I want to change back to CommonJS syntax)

https://node.green

If possible I want to drop our build step (`rollup`) altogether.

**Comment by jimmywarting** [comment]
I'm on board with that too.

**Comment by gr2m** [comment]
I guess a build step would still be needed as modules are not the same in Node & web.

I ended up using [`@pika/pack`](https://github.com/pikapkg/builders), which is using rollup under the hood. I see it as a polyfill until we can have the same modules work in both, node & browser.

I wrote about my setup here: https://gist.github.com/gr2m/5dd2ec6e3a04c3dc79f0cbb46decbe46

**Comment by dmitriz** [comment]
@bitin
> My gut feeling is node v8+ are modern enough that all of our code are covered, so there is no value in transpiling (and I want to change back to CommonJS syntax)

The PR https://github.com/bitinn/node-fetch/pull/649 is meant as the first step in this direction. It deals with single exports. 

My question is now, what should be the strategy for multiple exports?
A possible way could be to avoid them altogether, 
to prevent the modules from doing "too much".
Would that be desired or is some other strategy preferred?

**Comment by TimothyGu** [comment]
I’m very much onboard with removing Babel. The time has come for that. I still prefer to keep our source in ES module form though. It’s much easier to transform from ESM to CommonJS style than vice versa, and with the dust settling on Node.js’ support for ESM more people would want to use it, rather than relying on CJS-ES interop.

**Comment by bitinn** [comment]
@TimothyGu I hear you, but the status quo seems to be that many bundling tools are better at transforming from CommonJS to ESM? We have had a lot of problem with people trying to package up node-fetch for AWS using Webpack.

(My guess is most of them are confused about how Webpack/ESM work, but my anecdote observation remains that Webpack seem to just work with CommonJS?)

I love the named export from ESM, for sure, just that it seems to cause some troubles for users at the moment.

**Comment by TimothyGu** [comment]
> many bundling tools are better at transforming from CommonJS to ESM

Well I meant like actually transforming the source, rather than providing interoperability. But if that's the difficulty people are having, then I'm all for it :)

**Comment by dmitriz** [comment]
@TimothyGu 
Just trying to understand, if is there an example of a specific benefit for this project from using CommonJS mixed along with ESM?

If yes, maybe I shouldn't have been wasting my time on
https://github.com/bitinn/node-fetch/pull/649 :)

**Comment by TimothyGu** [comment]
@dmitriz, I think I'll defer to other people in the thread as I haven't been as active.

**Comment by Richienb** [comment]
Babel and rollup have been dropped in favour of microbundle in 3.x
