### ISSUE TITLE
Capture Raw HTTPS Request/Response Data

### ISSUE THREAD

**Issue by bradharms** [bitinn/node-fetch#651]
What is the simplest way to capture the full, raw, unencoded HTTPS request and response text as sent and received between the Node client and the server? The intent is to store the raw text in a database for logging purposes. I have to communicate with a finicky server and I need to see the exact binary messages being sent and received.

I am currently looking into the use of custom versions of https.Agent and net.Socket that capture raw binary data and pass it into callbacks, but the process seems involved an unintuitive. I was wondering if there was a simpler way.

To be clear, looking at only the body is not enough, nor is looking at the headers dictionary of the response object. I need the actual binary data.

**Comment by jimmywarting** [comment]
if that's the case then node-fetch isn't a good fit for you...

**Comment by bitinn** [comment]
Yep, `Fetch` is designed to make request easier, not inspecting the full network request.

**Comment by bradharms** [comment]
Could you offer an alternative?

**Comment by bitinn** [comment]
@bradharms I haven't used this, but this sounds like what you might want:

https://github.com/exogen/node-fetch-har

**Comment by bradharms** [comment]
@bitinn Thanks for the suggestion, but from what I discern from the docs this library doesn't provide any more direct access to the raw request/response text than fetch itself. It seems to just present it in an abstracted json format.
