### ISSUE TITLE
[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by sagilo** [bitinn/node-fetch#656]
My usage is pretty basic:

    import fetch from 'node-fetch';
    const res = await fetch(url, GenerateRequestOptions(token));

and the `fetch` call yields a warning:

    [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

As I'm not accessing `headers` directly, so I guess the fix should be in the package?

**Comment by dnalborczyk** [comment]
@sagilo I don't think this module uses `OutgoingMessage.prototype._headers` directly.

**Comment by bitinn** [comment]
closing, I doubt this error originated from `node-fetch`, provide complete stack if otherwise (and actual repro code would help)

**Comment by hosseinse1919** [comment]
i got this error on run node fetch 
u shoud change using this lib in `node-fetch`

 OutgoingMessage.prototype._headers is deprecated
