### ISSUE TITLE
Use w3c defined message for AbortError

### ISSUE THREAD

**Issue by wheresrhys** [bitinn/node-fetch#657]
The w3c draft IDL defines the expected message for AbortError to be `The operation was aborted.` (https://heycam.github.io/webidl/#aborterror)

But this library uses a different string:

https://github.com/bitinn/node-fetch/blob/0c2294ec48fa5b84519f8bdd60f4e2672ebd9b06/src/index.js#L54

While node-fetch doesn't aim to replicate whatwg fetch in every aspect, this seems like an unnecessary divergence.

**Comment by jimmywarting** [comment]
word... it's true that it isn't always the "user" that aborts the request.
it could have been a timeout also.

**Comment by Richienb** [comment]
Fixed in https://github.com/bitinn/node-fetch/commit/886277fc4349c98e3d44d75d8151120341f1e9e5.
