### ISSUE TITLE
ENETUNREACH error for ipv6

### ISSUE THREAD

**Issue by pocketjoso** [bitinn/node-fetch#66]
Hi there, new issue unfortunately with this library.

Node: `v0.12.7`

On `Linux` (`Linux version 3.13.0-57-generic (buildd@brownie) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015`) when I `fetch` url: `http://healthy-america.com.co/` I get error code `ENETUNREACH` - whereas on `osx` it works fine with same code.

Going back to `curl` I get `Network is unreachable` on my Linux server, unless I add flag `--ipv4` - then it _works_. Any suggestions on what I need to do in `node-fetch` to make requests like these succeed on my Linux server?

Thanks

**Comment by pocketjoso** [comment]
Reading [this](https://github.com/npm/npm/issues/6857) I might try upgrading Node unless another suggestion pops up.

**Comment by pocketjoso** [comment]
Presume it's a bug in the underlying http(s) libraries, f.e. https://github.com/nodejs/node-v0.x-archive/issues/7637.

If that means there's nothing `node-fetch` can do about it, I guess close this. If you have any input on how to solve the issue though that would still be great! Cheers

**Comment by bitinn** [comment]
Sorry I haven't faced such a problem myself, I guess writing a short test code using `http.request` might be enough to verify the problem.

**Comment by pocketjoso** [comment]
Yeah it is underlying libraries, closing. Upgraded to `Node 4` but that did not help. :/ Will continue looking into it.
