### ISSUE TITLE
Single quotation marks in HTTP headers cause an error

### ISSUE THREAD

**Issue by thebeatlecoder** [bitinn/node-fetch#666]
If a HTTP header value contains a `‘` (U+2018: left single quotation mark) or a `’` (U+2019: right single quotation mark), `node-fetch` returns an error saying `not a legal HTTP header value`.

**Comment by ammanvedi** [comment]
i am also seeing this issue

**Comment by jimmywarting** [comment]
Well, that is because it isn't valid
try it in the browser and see for yourself: https://jsfiddle.net/crLtp78d/

**Comment by jimmywarting** [comment]
Still wonder doe if you can receiveinvalid  header but not create them
Is it logical that a response should fail b/c of that?
