### ISSUE TITLE
Do not use constructor.name to check object

### ISSUE THREAD

**Issue by yumetodo** [bitinn/node-fetch#667]
`isAbortSignal` and `isBlob` use `constructor.name` only to check.

https://github.com/bitinn/node-fetch/blob/bf8b4e8db350ec76dbb9236620f774fcc21b8c12/src/request.js#L36-L43

https://github.com/bitinn/node-fetch/blob/95286f52bb866283bc69521a04efe1de37b26a33/src/body.js#L364-L378

However, `constructor.name`  can be rewrited. So, for example, webpack4 with production mode will break `constructor.name` of AbortSignal that will be rewritten to `"s"`.

![image](https://user-images.githubusercontent.com/10869046/63650727-e8fec080-c788-11e9-8101-39c5f52015f3.png)

So, `Expected signal to be an instanceof AbortSignal` Error was occured (ref: https://github.com/yumetodo/vscode-google-photos-uploader/issues/11 )

`isURLSearchParams` is adopting good implementation (ref: https://github.com/bitinn/node-fetch/issues/296#issuecomment-307598143, https://github.com/bitinn/node-fetch/pull/297/commits/302992d68e75748a7781c52e868b4fde7925325f ).  `Object.prototype.toString()` will call `Symbol.toStringTag` propaty which is not writable(see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag))

https://github.com/bitinn/node-fetch/blob/95286f52bb866283bc69521a04efe1de37b26a33/src/body.js#L346-L362

Of course, I know that there are two workarounds for webpack4:

1. Set `optimization.minimize` to `false` (ref: https://github.com/webpack/webpack/issues/6841#issuecomment-376129163)
2. Specify minimizer manually and set `keep_fnames` to `true` (ref: https://github.com/CartoDB/carto-vl/pull/1066)

However, rely on `constructor.name` is a bad idea, I think.

**Comment by bitinn** [comment]
Thx for the detailed report, since `AbortSignal` and `Blob` are essentially built-in API, so you are using are essentially polyfill for these API, I think it's fair to say `webpack` should consider leaving them intact?

I wouldn't say checking `constructor.name` is great but it's perhaps what we expect from a polyfill :)

**Comment by jimmywarting** [comment]
checking constructor.name might be overkill also?

**Comment by bitinn** [comment]
@jimmywarting javascript doesn't have an object type, so I thought we should enforce at least a bit of common sense here, but if tools like `webpack` have to go that extreme, I am fine with removing those checks.

**Comment by yumetodo** [comment]
> javascript doesn't have an object type, so I thought we should enforce at least a bit of common sense here

Why don't you use `Symbol.toStringTag`? That is the only way to check type because rewriting `constructor.name` is generally permitted.

This issue was triggered by webpack's optimization([webpack-contrib/terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin)) but node-fetch's matter, I think. There is no reason for `terser-webpack-plugin` not to rewrite `constructor.name` of `AbortSignal`.

[mysticatea/abort-controller](https://github.com/mysticatea/abort-controller), polyfill of `AbortController`  that you suggested, implement `Symbol.toStringTag` correctly.

https://github.com/mysticatea/abort-controller/blob/91e4291b414b5c713c62acd447d27744231b7739/src/abort-signal.ts#L81-L87

**Comment by bitinn** [comment]
OK, we will drop `constructor.name` in favor of `toStringTag` in v3 release where applicable.

**Comment by jimmywarting** [comment]
+1 for Symbol.toStringTag

**Comment by Richienb** [comment]
Fixed in #673
