### ISSUE TITLE
The `encoding` module should be an `optionalDependencies`

### ISSUE THREAD

**Issue by ehmicky** [bitinn/node-fetch#675]
The [`encoding`](https://github.com/bitinn/node-fetch/blob/95286f52bb866283bc69521a04efe1de37b26a33/src/body.js#L14) module is conditionally required, i.e. should be an `optionalDependencies` in the `package.json`. 

Doing so allows libraries that parse `require()` statements (using JavaScript AST) such as [`precinct`](https://github.com/dependents/node-precinct) to know whether a `require()` statement that cannot be resolved indicates an error or not.

This causes problems on our library `zip-it-and-ship-it`: https://github.com/netlify/zip-it-and-ship-it/issues/16, https://github.com/netlify/zip-it-and-ship-it/issues/30

**Comment by Richienb** [comment]
https://github.com/bitinn/node-fetch/commit/d68d0ef2dc4bd0afc5ddbd2110b5509b7d17c5f8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R66

**Comment by ehmicky** [comment]
Great, thanks!
