### ISSUE TITLE
Suggestion: add example on how to patch node

### ISSUE THREAD

**Issue by GrosSacASac** [bitinn/node-fetch#683]
```js
import fetch from "node-fetch";


if (!global.fetch) {
    global.fetch = fetch;
}
```

**Comment by xxczaki** [comment]
Note to anyone who want to take on this PR: Please create it against the `3.x` branch.

Thanks :smile:

**Comment by Richienb** [comment]
Added in https://github.com/bitinn/node-fetch/commit/7e5a483dbe481c6c4df4a8a74ba446bafad031eb.

**Comment by dannypaz** [comment]
@xxczaki what would be the reasoning to patch fetch in nodejs?

**Comment by GrosSacASac** [comment]
Use libraries that were initially made for the browser that depend on the fetch global
