### ISSUE TITLE
Can one custom agent serve all fetches?

### ISSUE THREAD

**Issue by Lonniebiz** [bitinn/node-fetch#695]
The documentation on using a custom agent is located here:
https://github.com/bitinn/node-fetch#custom-agent

There, it seems to instruct that you must create a new custom agent for each fetch you do. However, I see that it also works to create one custom agent (in an outer scope) and then simply reference that exact same custom agent for all succeeding fetches.

**Example:**
```
import { default as fetch } from 'node-fetch';
import { default as http } from 'http';
import { default as https } from 'https';

const httpAgent = new http.Agent({ keepAlive: true });
const httpsAgent = new https.Agent({ keepAlive: true, rejectUnauthorized: false });

export async function post(obj, toURL)
{
	let options = {};
	options.method = "POST";
	// Other options are omitted here for the sake of brevity
	// The pertinent option is agent. Notice that the http and
	// https agents were created outside the scope of this function,
	// and are therfore reused each time this fucntion is called.
	options.agent = function (_parsedURL)
	{
		if (_parsedURL.protocol === 'http:')
		{
			return httpAgent;
		}
		else
		{
			return httpsAgent;
		}
	};	
	return fetch(toURL, options);
}
```
Are there any draw-backs to only creating one custom https.agent, and thereafter referencing that singleton in the options of all succeeding fetches?

**Comment by bitinn** [comment]
You can use the same Agent instance, in fact it's designed to be used this way. It's a nodejs core feature, you will learn more from their doc:

https://nodejs.org/api/http.html#http_class_http_agent
