### ISSUE TITLE
node domains are not being propagated within promises.

### ISSUE THREAD

**Issue by viliusl** [bitinn/node-fetch#71]
Ok, so in my app I use deprecated node domains (I know, but until valid substitution is proposed I kinda need them) and it seems that node-fetch looses current domain within promise.

given I substitute native promise with bluebird:

```js
fetch.Promise = require('bluebird');
```

node domains become available within promise.

I can produce a proper test + a fix, but the question will you accept this fix given node domains are deprecated?

**Comment by bitinn** [comment]
Sorry for the delay in reply, I have little knowledge of domain, but is it something we can do to fix? We are just using native promise as-is.

**Comment by viliusl** [comment]
Ah, sorry for not closing it after doing some discovery. Problem is that native promises do not work with node domains properly, but well this is not an issue with node-fetch (amazing thing btw) and node-fetch gives nice extension point to use other promise library which imho is more than enough. I mean there is no need to hack library and try to fix issues in node itself when it allows you to do your own thing (use custom promise lib).

So closing this one:)
