### ISSUE TITLE
Request for Collaborators

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#73]
There are quite a few issues and minor features I intend to work on or review (eg. #8 and existing PRs) but haven't had the time, I guess being CEO of a startup has finally taken its toll on me.

Yes, we still heavily use `node-fetch` in production, and I still intend to drive its development. But I would much appreciate your help on this effort.

Given the number of projects depending on `node-fetch`, I believe it's the right thing to do.

My hope for this change:
- We continue to stick with our feature guideline, Fetch as described in spec: we are not going to replace `request` anytime soon. https://github.com/bitinn/node-fetch#features
- We continue to heavily test our implementation when adding features and bugfixes, my contribution during 1.x development was mostly answering issues, adding more edgecase tests, and document new code.

If you are interested in becoming a collaborator, leave a message to let me know :)

PS: I think next release warrants a minor version bump?

**Comment by kirill-konshin** [comment]
Since we use `node-fetch` in production for our https://github.com/ringcentral/js-sdk I can provide some help in covering missing spec features that we need. Primarily -- req/res cloning.

**Comment by bitinn** [comment]
@kirill-konshin thx! added you as a collaborator :)

**Comment by kirill-konshin** [comment]
Wow, thanks!

**Comment by funkjunky** [comment]
I looked through the issues list and I couldn't tell if there were any issues that are definitely within the scope of isomorphic-fetch and unsolved.

Could you link me to some issues that you simply need man power to solve, and not necessarily need to decide which route to take.
I've been feeling guilty for years, for not contributing to a worthy open source cause; I use isomorphic fetch and after a decade of web dev, I'm quite confident in my usefulness and want to help.

**Comment by bitinn** [comment]
@funkjunky Thx a lot, many isomorphic issues were resolved in v2 alpha release, what you can help might be to test it out :)

**Comment by ahmadnassri** [comment]
throwing my hat in the ring ... small PRs where I can.

**Comment by bitinn** [comment]
continue in #252 (sorry for notification spam)
