### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by Sjors** [bitinn/node-fetch#74]
E.g. for the latest release, this will do the trick:

```sh
git tag -a v1.3.3 fd3f89fcd94
git push --tags
```

This makes it easier to tell which commit corresponds to which NPM release.

**Comment by bitinn** [comment]
I will get to it but for now, check:

https://github.com/bitinn/node-fetch/commits/master (`npm version` creates a commit on version change)
https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md

**Comment by bitinn** [comment]
done for v1.4.0
