### ISSUE TITLE
 Support of http proxy

### ISSUE THREAD

**Issue by jimliang** [bitinn/node-fetch#79]
If I want to use http proxy，I will

     require('http').request({
        host:'127.0.0.1',
        port:8580,
        method:'POST',
        path:'https://www.google.com',
    },function(res){
        //...
    })

But I use node-fetch，

    fetch(obj).then(function(res){
        ...
    })

It throw `TypeError: Parameter 'url' must be a string, not object`

It does not support URL objects

**Comment by bitinn** [comment]
You can pass it a `http.Agent` with custom proxy settings: https://github.com/bitinn/node-fetch#options

**Comment by jimliang** [comment]
It resolved, I used https://github.com/TooTallNate/node-https-proxy-agent

    fetch('https://www.google.com',{ agent:new HttpsProxyAgent('http://127.0.0.1:8580')}).then(function(res){
        ...
    })

**Comment by jimliang** [comment]
use https://github.com/zjael/simple-proxy-agent to support more proxy type. http、socks5.

**Comment by satnam2019** [comment]
https-proxy-agent is not working with node-fetch, giving same IP and not the proxy IP.
Where as https.get with https-proxy-agent' gives proxy IP. 
But both code attached one is working and another not

const HttpsProxyAgent = require('https-proxy-agent');
const fetch = require('node-fetch');
var url = require('url');

const handler = async () => {
  var agent = new HttpsProxyAgent('http://174.71.185.194:48678')
  var options = url.parse('https://56113c989282e5d7d19ab5471476d254.m.pipedream.net');
  options.agent = agent;
  console.log(options)
  let response2 = await fetch('https://56113c989282e5d7d19ab5471476d254.m.pipedream.net', { options })
  let json = await response2.text();
  console.log(json)
};

Below is working code gives proxy ip.
var url = require('url');
var https = require('https');
var HttpsProxyAgent = require('https-proxy-agent');

const handler = async () => {
// HTTP/HTTPS proxy to connect to
var proxy = process.env.http_proxy || 'http://174.71.185.194:48678';
//console.log('using proxy server %j', proxy);

// HTTPS endpoint for the proxy to connect to
var endpoint = process.argv[2] || 'https://xxxxxxx.m.pipedream.net';
//console.log('attempting to GET %j', endpoint);
var options = url.parse(endpoint);

// create an instance of the `HttpsProxyAgent` class with the proxy server information
var agent = new HttpsProxyAgent(proxy);
options.agent = agent;
console.log(options);
https.get(options, function (res) {
  //console.log('"response" event!', res.headers);
  res.pipe(process.stdout);
});

}

**Comment by lisonge** [comment]
> It resolved, I used https://github.com/TooTallNate/node-https-proxy-agent
> 
> ```
> fetch('https://www.google.com',{ agent:new HttpsProxyAgent('http://127.0.0.1:8580')}).then(function(res){
>     ...
> })
> ```

i use typescript, and it type is incompatible
```typescript
import { HttpProxyAgent } from 'http-proxy-agent';
import fetch from 'node-fetch';

fetch('', {
    method:'GET',
    agent:new HttpProxyAgent('http://127.0.0.1:10809')
})
```
`
Type 'HttpProxyAgent' is not assignable to type 'Agent | ((parsedUrl: URL) => Agent) | undefined'.
  Property 'freeSockets' is missing in type 'HttpProxyAgent' but required in type 'Agent'.
`

**Comment by kics223w1** [comment]
You can use package [tunnel](https://www.npmjs.com/package/tunnel) to support node fetch with proxy.
Example Implement:
```
   const tunnel = require('tunnel');  
   const fetch = require('node-fetch');
   import fs from 'fs';
  
    const configTunnel = {
      ca: [fs.readFileSync(
      "YOUR_CERTIFICATE_PATH"
    )],
      proxy: {
        host: this.currentIP,
        port: proxyPort,
      },
    };

    const tunnelHTTPS = tunnel.httpsOverHttp(configTunnel);

    const tunnelHTTP = tunnel.httpOverHttp(configTunnel);

    let config: Record<string, any> = {
      url: flow.request.url,
      method: method,
      headers: headers,
      agent: flow.isSSL ? tunnelHTTPS : tunnelHTTP,
    };
    if (flow.request.bodySize > 0 && method !== 'GET' && method !== 'HEAD') {
      config.body = flow.request.body;
    }

   try {
      const response = await fetch(flow.request.url, config);
    } catch (e: any) {
      throw new Error(e.message);
    }

```
Note that: node fetch with proxy doesn't work if Method GET contains body.
