### ISSUE TITLE
tasks for considering (2.0 release)

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#8]
just collecting some common complain about 1.x release
- [x] provide some guideline on how to handle rejected promise (failed fetch), this can be caused by many reasons: url, headers.location, network timeout, request config etc; currently the only way to distinguish them is to check error message.
- [x] provide some alternatives to extract redirect headers, it's not possible with current fetch spec, only the final url will be expose to user when following redirects.
- [ ] some way for cookies to persist when you do a POST request that redirects (which should be followed by a GET request, often with cookie as credential). Though if we implement extraction for redirect headers we can make this possible (keep the cookie headers for your next GET request).
- [x] expose Request/Headers/Response interfaces, we don't currently have a Request interface due to the fact that no one are using them.
- [x] normalize Headers `.set` and `.append` to prevent non-string input, it's recommended to already cast your input to `String` type first.
- [x] Headers/Response interface should support ES6 features, such as `keys()` and `entries()`

**Comment by tracker1** [comment]
* handling rejected promises, does the public specification provide any guidelines on this... ideally this module should match the error signatures used by the public version.  Perhaps a complimentary module that can interrogate the error to give a more useful sub-type for the given error message?

* Redirect headers, perhaps a `history` on the response, containing any response objects through a history chain the first entry being the first response then the redirect chain, until the final result.
  * each entry in history is a response object
  * entries in history do not have a `history` property, only the final response
  * the final response is not included in `history`
  * history will be `undefined` unless there are values (will never be a 0 array)
    * this will allow a simpler `if (res.history)` kind of check instead of `if (res.history && res.history.length)` ... not really required, but an idea

Note: neither of the above suggestions would require a 2.0 bump as they would be additive... for the history, once implemented, would put forward an issue to chromium/safari/ie/firefox to add the feature and to whatwg to extend the standard.

**Comment by bitinn** [comment]
@tracker1 Thx for the suggestions.

Just to clarity, item 2 isn't possible with Fetch spec because of security issue, so I don't expect spec to change. see https://fetch.spec.whatwg.org/#atomic-http-redirect-handling

For item 1 there isn't a standard, if we are to tackle it, we will have to come up with ours. see https://github.com/whatwg/fetch/issues/25

Good news is there are many alternatives to workaround these Fetch limits, so I am not jumping to solve them now.

**Comment by bitinn** [comment]
We are now collecting feedbacks on what sort of data a rejected `Error` should contain (besides current `err.message`), suggestion much appreciated.

For example, we can give it:

- `err.status` for easier debugging
- `err.headers` for peeking into redirection headers when you are not following redirects.

As we don't see such needs ourselves (we don't write special case for different errors, so `err.message` is simply a hint for debugging), wonder what else ppl are interested in.

Note: `Error` here refer to Network error, Redirection error or Parser error etc., remote server errors such 4xx, 5xx are resolved per Fetch spec.

**Comment by bitinn** [comment]
cc @matthew-andrews @rricard

**Comment by weijarz** [comment]
Are there plans to add http proxy support?

**Comment by bitinn** [comment]
@weijarz you will need to create a custom http.Agent or https.Agent with proxy support, and pass it as options `agent`.

**Comment by aarongreenwald** [comment]
@bitinn Regarding the error reporting - is there any possibility we'd pass the server's rejection along with the error so that it can be handled? Right now we're forcing the server to put all relevant information in `message` because we're ignoring everything else. I'd like to be able to catch the server's response and do something with it myself. 

I'd be happy to help with a PR if this is something we can.

**Comment by bitinn** [comment]
@aarongreenwald may I double-check your use-case? if your server is returning something, you should be able catch it (body and headers). it's only when you encounter network error, you will see a rejected promise. even 4xx and 5xx are fulfilled promise (per spec).

**Comment by bitinn** [comment]
@aarongreenwald looking at `nock` document, I assume you are returning a JSON? it's in the `res.body` stream, but you can call `return res.json()` to get your JSON object on the next `then` call. See if examples in readme help you.

**Comment by aarongreenwald** [comment]
@bitinn It's not hitting the `.then`, it's going straight to `.catch`. To be honest I don't fully understand how `nock` is returning the data, but `request` is grabbing the response and passing it to the callback as an object in the `error` argument.

The following is from the `nock` tests. Notice how the test gets the supplied object in `req.on('error'...`. `node-fetch` is throwing a new error in `req.on('error'...`

```
test("replyWithError allows json response", function(t) {
    var scope = nock('http://www.google.com')
        .post('/echo')
        .replyWithError({message: "Service not found", code: 'test'});

    var req = http.request({
        host: "www.google.com"
        , method: 'POST'
        , path: '/echo'
        , port: 80
    });

    // An error should have have been raised
    req.on('error', function(e) {
      scope.done();
      t.equal(e.message, 'Service not found');
      t.equal(e.code, 'test');
      t.end();
    });

    req.end();
});

```

**Comment by bitinn** [comment]
@aarongreenwald It's key for you to figure out what nock is returning, if you are unsure, do ask its developer. And you should look at the error message you get in `catch`, it will help you figure out what go wrong.

**Comment by aarongreenwald** [comment]
The error I'm catching is what I'm trying to change. It's coming from here: 

https://github.com/bitinn/node-fetch/blob/master/index.js#L115-L118

```
	req.on('error', function(err) {
			clearTimeout(reqTimeout);
			reject(new Error('request to ' + options.url + ' failed, reason: ' + err.message));
	});
```

My problem is that `node-fetch` throws away whatever error data might have been supplied and wraps it in a new error, using only the `message` property. I’m asking why not pass the error back up, the way `request` lets me handle the error without intercepting and re-throwing it. 

Maybe it doesn't matter because in reality there won't be anything interesting in those errors. I'm beginning to suspect I'm barking up the wrong tree because this is only a problem in testing and I can work around it.

**Comment by bitinn** [comment]
> I’m asking why not pass the error back up, the way request lets me handle the error without intercepting and re-throwing it.

This is a failed promise, likely due to network error (note that 4xx and 5xx are not network errors; if you don't expect it to be a network error, then maybe `nock` is returning something you don't expect)

As defined in Fetch Spec, on client-side you won't know why fetch failed due to security (again, *failed* as in promise, not server response), we are providing additional message for debugging purpose only.

ref: https://github.com/whatwg/fetch/issues/25

**Comment by aarongreenwald** [comment]
Fair enough, thanks for clarifying.

**Comment by tracker1** [comment]
@bitinn @aarongreenwald maybe add a `details` or `sourceError` property for the original internal error if there is/was one?  I know it's not spec compliant, but this module is used in a server environment, where additional details may well be needed and invaluable.

**Comment by gajus** [comment]
> @weijarz you will need to create a custom http.Agent or https.Agent with proxy support, and pass it as options agent.
> ref:
> https://github.com/bitinn/node-fetch#options
> https://github.com/TooTallNate/node-http-proxy-agent

Would be useful to add this to the docs. @bitinn

**Comment by stevenvachon** [comment]
Could use [tunnel](https://github.com/koichik/node-tunnel) too for proxies.

**Comment by TimothyGu** [comment]
@bitinn said:

> - [ ] Though if we implement extraction for redirect headers we can make this possible (keep the cookie headers for your next GET request).

Is there anything that makes this impossible? As far as I could tell, the only reason for Fetch Standard to have the opaque-redirect filtered response type is preventing XSS resulting from the violation of [atomic HTTP redirect handling](https://fetch.spec.whatwg.org/#atomic-http-redirect-handling). Since XSS isn't a concern on Node.js, is there any other reason why we haven't implemented it?

**Comment by TimothyGu** [comment]
Or actually, isn't that already the case?

```js
fetch('http://127.0.0.1:30001/redirect/301', { headers: { Cookie: 'supersecret=123' } })
  .then(res => res.json())
  .then(console.log);

=>
{ method: 'GET',
  url: '/inspect',
  headers: 
   { cookie: 'supersecret=123',
     'accept-encoding': 'gzip,deflate',
     'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
     connection: 'close',
     accept: '*/*',
     host: '127.0.0.1:30001' },
  body: '' }
```

**Comment by bitinn** [comment]
@TimothyGu by persists I mean the inclusion of a cookie jar, so the whole process: POST then FOLLOW REDIRECT then GET, is done in one single request. That's how browsers handle it.

**Comment by jimmywarting** [comment]
Is there any chance of a pre release?

**Comment by bitinn** [comment]
@jimmywarting I am sure if it's anywhere near ready for RC, Timothy will let us know. Note that besides ES6 features, all of these are in the 1.x release already.

**Comment by bitinn** [comment]
Thx @TimothyGu for getting 2.0 alpha out! Just a quick note that you should read [the upgrade guide](https://github.com/bitinn/node-fetch/blob/master/UPGRADE-GUIDE.md) and [changelog](https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md).
