### ISSUE TITLE
Add status process method

### ISSUE THREAD

**Issue by yckart** [bitinn/node-fetch#80]
Would nice to have that handy `checkStatus` function included for [Handling HTTP error statuses](https://github.com/github/fetch/blob/97e32630f217de820bfbbf3b724022d90390a1f1/README.md#handling-http-error-statuses)...

```js
function checkStatus(response) {
  if (response.status >= 200 && response.status < 300) {
    return response
  } else {
    var error = new Error(response.statusText)
    error.response = response
    throw error
  }
}
```

**Comment by bitinn** [comment]
While we don't have that exact feature, we do have `res.ok`, which is in the Fetch Spec.

https://github.com/bitinn/node-fetch/blob/master/lib/response.js#L29

There are a few features not in the Fetch Spec but we are interested in, see #8

**Comment by bitinn** [comment]
close this for now, `ok` should be enough for now and user can certainly make a small module if they prefer :)
