### ISSUE TITLE
res.text() doesn't work after res.json() fail

### ISSUE THREAD

**Issue by coderofsalvation** [bitinn/node-fetch#85]
Hi, I would like to get the response raw text when res.json() throws an error.

Example scenario: expected json response is not json but an html error. Therefore, res.json() throws an error. 

    var response;
    fetch(url, {
      headers: headers,                                                                                                                                                                           
      body: JSON.stringify(payload),
      method: method.toUpperCase()
    }).then(function(res) {
      response = res;
      return res.json();
    }).then(function(json) {
         // do stuff
      }
    }).catch(function(err) {
       response.text().then(function(html) {                               // <---- doesnt work
        console.log("instead of json, I got this response:");
        return console.log(html);
      });
      return console.error(err);
    });

What's the best way of printing 'corrupt json' responses?

> Note #1 : Im not asking how to check the header (http status codes etc)
> Note #2 : This is a pretty straightforward scenario imho, so an example of this would be very handy in README.md

**Comment by bitinn** [comment]
Can checking content header be a good solution? My hope is the API is returning proper content type at least...

**Comment by coderofsalvation** [comment]
Thanks for your answer, but no that is not my point (hence my note on checking the header).
It is a very common practice to be able to log requests/responses when things go wrong.
So far node-fetch only shows 'Syntax Error' in the console.

**Comment by coderofsalvation** [comment]
hold on..think I got it..1 sec

**Comment by kirill-konshin** [comment]
By design, you can only use body once (e.g. one call of either `text()` or `json()` method). You can clone your response and use it for `text()`.

**Comment by m14t** [comment]
:+1: for Clone functionality!

I have a similar issue where the API returns an empty string when there is an error.

The content-type is still `application/json;charset=UTF-8`.
The status code is still `200`

Calling `.json()` on a response with a body like this will result in a `Unexpected end of input` error being thrown, and so I'd like to be able to check for this state first (and if the result of `.text()` is `''` I can throw a meaningful error), but if I do so, I am then later unable to call `.json()`.

I realize that this API design is non-standard, but it is out of my hands and would be great if I could still work around it's misgivings.

Thanks for this library! If there's any way to help with this, I'd be happy to lend some time.

**Comment by bitinn** [comment]
Not sure `clone` is the recommended solution for this problem, since this is a workaround, how about checking for `content-length`? empty string (0 byte) is never valid json.

**Comment by kirill-konshin** [comment]
Well, these are 2 separate topics. Getting `text()` and `json()` on one `Response` is forbidden per spec, so here `clone()` can help. Checking of length or any other property of `Response` is a responsibility of client code, since library does not know what to do and what to check, it just rejects a `json()` promise with certain `JSON.parse()` error.

From network standpoint, HTTP 200 OK and no content is not a best practice since there is a HTTP 204 No Content status for that.

**Comment by bitinn** [comment]
@kirill-konshin yeah not try to dismiss `clone` here, for OP's logging requirement it's the better solution. I was replying to @m14t

**Comment by coderofsalvation** [comment]
@bitinn can you merge my PR? It adds the example code below to README.md:

     // post with capturing (json) error(output)
     function myreq( url, opts ){
       var response = null;
       fetch( url, opts )
         .then(function(res) {
           response = res;
           return res.json();
         }).then(function(json) {
           console.log(json);
         }).catch(function(err) {
           console.log( err+ "\n\n" + response._raw.toString() )
         });
     }

I don't really see why we need a clone function as this does the job without any modifications..

**Comment by bitinn** [comment]
> I don't really see why we need a clone function as this does the job

Mainly because `_raw` is internal and not within Fetch Spec, so it's subject to change.

**Comment by m14t** [comment]
@bitinn Thanks for the suggestion, unfortunately the `Content-Length` header is also not set. I understand that this API is the worst.

I just confirmed that @kirill-konshin's PR #88 allows me to do what I'm looking for.

**Comment by bitinn** [comment]
release v1.4.0 has `clone` which will cover both the problem mentioned here :)

**Comment by m14t** [comment]
@bitinn (and @kirill-konshin) Thank you for the speedy turn around and tagged release.  I know working on OSS can be tiring and frustrating some times, but wanted to let you know I really appreciate your work here. The `1.4.0` release works perfectly for my needs.
