### ISSUE TITLE
Should node-fetch 2.0 require a minimum of Node.js 4?

### ISSUE THREAD

**Issue by jimmywarting** [bitinn/node-fetch#97]
Would be happy to help and contribute with PR
But I want to work with es6 classes wish require a minimum node version of 4

**Comment by kirill-konshin** [comment]
Absolutely not. 0.x are still widely used: https://semaphoreci.com/blog/2015/12/15/nodejs-version-usage-in-commercial-projects-2015-edition.html. Why should we make such a constraint if everything works OK now?
